# Generated by tools/gen_stubs.py from the encoder tables. Do not edit.
"""Module-level riscv64 mnemonic functions, generated from the template table.

Every mnemonic in `jita.riscv64.table.MAP_OP` becomes a function
`name(*ops, asm=None)` that encodes into `asm`, or into the current
Assembler when `asm` is None. `and`, `or` and `not` are spelled `and_`,
`or_` and `not_` (Python keywords), `min` and `max` are `min_` and `max_`
(builtins); `a.min(...)` and `a.max(...)` also work as methods.

Mnemonics with dots are attributes: `fadd.d(fa0, fa1, fa2)`,
`fcvt.w.d(a0, fa0, rm="rtz")`, `lr.w.aq(a0, mem[a1])`, `fence.i()`.
`fadd`, `fcvt` and the other prefixes that are not instructions
themselves are namespaces; `fence`, `fmv.d` and `lr.w` are both an
instruction and a namespace.

Floating point instructions that round take the rounding mode as the
keyword `rm` ("rne", "rtz", "rdn", "rup", "rmm" or "dyn", the default).

Type checkers read `insns.pyi` next to this module, which
`tools/gen_stubs.py` generates with one overload per accepted combination
of operand classes.
"""

from collections.abc import Callable
from typing import Protocol, overload

from ..core.assembler import Assembler
from ..core.labels import Extern, Label
from ..core.operand import Imm
from .mem import MemExpr
from .regs import CsrName, F, FenceSet, Rm, X

# Annotations inside Riscv64Assembler go through these aliases, as on
# the other architectures.
type _Imm = int | Imm
type _Target = Label | Extern | str

PY_NAMES: dict[str, str]
INSNS: dict[str, Callable[..., None]]
MNEMONICS: dict[str, Callable[..., None]]

class Group:
    """The mnemonics that share a dotted prefix, `fadd` of `fadd.s` and `fadd.d`, as attributes. Calling it is an error: the prefix is not an instruction."""

    def __init__(self, name: str) -> None: ...
    def __call__(self, *ops: object, **kw: object) -> None: ...


class _add(Protocol):
    """Emit `add` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
        """Emit `add` (3 operands)."""
    def uw(self, op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
        """Emit `add.uw` (3 operands)."""

class _amoadd(Protocol):
    """Namespace of the `amoadd.*` mnemonics."""

    d: _amoadd_d
    w: _amoadd_w

class _amoadd_d(Protocol):
    """Emit `amoadd.d` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoadd.d` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoadd.d.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoadd.d.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoadd.d.rl` (3 operands)."""

class _amoadd_w(Protocol):
    """Emit `amoadd.w` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoadd.w` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoadd.w.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoadd.w.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoadd.w.rl` (3 operands)."""

class _amoand(Protocol):
    """Namespace of the `amoand.*` mnemonics."""

    d: _amoand_d
    w: _amoand_w

class _amoand_d(Protocol):
    """Emit `amoand.d` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoand.d` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoand.d.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoand.d.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoand.d.rl` (3 operands)."""

class _amoand_w(Protocol):
    """Emit `amoand.w` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoand.w` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoand.w.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoand.w.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoand.w.rl` (3 operands)."""

class _amomax(Protocol):
    """Namespace of the `amomax.*` mnemonics."""

    d: _amomax_d
    w: _amomax_w

class _amomax_d(Protocol):
    """Emit `amomax.d` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amomax.d` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amomax.d.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amomax.d.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amomax.d.rl` (3 operands)."""

class _amomax_w(Protocol):
    """Emit `amomax.w` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amomax.w` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amomax.w.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amomax.w.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amomax.w.rl` (3 operands)."""

class _amomaxu(Protocol):
    """Namespace of the `amomaxu.*` mnemonics."""

    d: _amomaxu_d
    w: _amomaxu_w

class _amomaxu_d(Protocol):
    """Emit `amomaxu.d` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amomaxu.d` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amomaxu.d.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amomaxu.d.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amomaxu.d.rl` (3 operands)."""

class _amomaxu_w(Protocol):
    """Emit `amomaxu.w` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amomaxu.w` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amomaxu.w.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amomaxu.w.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amomaxu.w.rl` (3 operands)."""

class _amomin(Protocol):
    """Namespace of the `amomin.*` mnemonics."""

    d: _amomin_d
    w: _amomin_w

class _amomin_d(Protocol):
    """Emit `amomin.d` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amomin.d` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amomin.d.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amomin.d.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amomin.d.rl` (3 operands)."""

class _amomin_w(Protocol):
    """Emit `amomin.w` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amomin.w` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amomin.w.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amomin.w.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amomin.w.rl` (3 operands)."""

class _amominu(Protocol):
    """Namespace of the `amominu.*` mnemonics."""

    d: _amominu_d
    w: _amominu_w

class _amominu_d(Protocol):
    """Emit `amominu.d` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amominu.d` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amominu.d.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amominu.d.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amominu.d.rl` (3 operands)."""

class _amominu_w(Protocol):
    """Emit `amominu.w` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amominu.w` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amominu.w.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amominu.w.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amominu.w.rl` (3 operands)."""

class _amoor(Protocol):
    """Namespace of the `amoor.*` mnemonics."""

    d: _amoor_d
    w: _amoor_w

class _amoor_d(Protocol):
    """Emit `amoor.d` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoor.d` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoor.d.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoor.d.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoor.d.rl` (3 operands)."""

class _amoor_w(Protocol):
    """Emit `amoor.w` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoor.w` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoor.w.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoor.w.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoor.w.rl` (3 operands)."""

class _amoswap(Protocol):
    """Namespace of the `amoswap.*` mnemonics."""

    d: _amoswap_d
    w: _amoswap_w

class _amoswap_d(Protocol):
    """Emit `amoswap.d` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoswap.d` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoswap.d.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoswap.d.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoswap.d.rl` (3 operands)."""

class _amoswap_w(Protocol):
    """Emit `amoswap.w` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoswap.w` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoswap.w.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoswap.w.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoswap.w.rl` (3 operands)."""

class _amoxor(Protocol):
    """Namespace of the `amoxor.*` mnemonics."""

    d: _amoxor_d
    w: _amoxor_w

class _amoxor_d(Protocol):
    """Emit `amoxor.d` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoxor.d` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoxor.d.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoxor.d.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoxor.d.rl` (3 operands)."""

class _amoxor_w(Protocol):
    """Emit `amoxor.w` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoxor.w` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoxor.w.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoxor.w.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `amoxor.w.rl` (3 operands)."""

class _fabs(Protocol):
    """Namespace of the `fabs.*` mnemonics."""

    def d(self, op0: F, op1: F, /, *, asm: Assembler | None = None) -> None:
        """Emit `fabs.d` (2 operands)."""
    def s(self, op0: F, op1: F, /, *, asm: Assembler | None = None) -> None:
        """Emit `fabs.s` (2 operands)."""

class _fadd(Protocol):
    """Namespace of the `fadd.*` mnemonics."""

    def d(self, op0: F, op1: F, op2: F, /, *, rm: Rm | None = None, asm: Assembler | None = None) -> None:
        """Emit `fadd.d` (3 operands, rounding mode `rm=`)."""
    def s(self, op0: F, op1: F, op2: F, /, *, rm: Rm | None = None, asm: Assembler | None = None) -> None:
        """Emit `fadd.s` (3 operands, rounding mode `rm=`)."""

class _fclass(Protocol):
    """Namespace of the `fclass.*` mnemonics."""

    def d(self, op0: X, op1: F, /, *, asm: Assembler | None = None) -> None:
        """Emit `fclass.d` (2 operands)."""
    def s(self, op0: X, op1: F, /, *, asm: Assembler | None = None) -> None:
        """Emit `fclass.s` (2 operands)."""

class _fcvt(Protocol):
    """Namespace of the `fcvt.*` mnemonics."""

    d: _fcvt_d
    l: _fcvt_l
    lu: _fcvt_lu
    s: _fcvt_s
    w: _fcvt_w
    wu: _fcvt_wu

class _fcvt_d(Protocol):
    """Namespace of the `fcvt.d.*` mnemonics."""

    def l(self, op0: F, op1: X, /, *, rm: Rm | None = None, asm: Assembler | None = None) -> None:
        """Emit `fcvt.d.l` (2 operands, rounding mode `rm=`)."""
    def lu(self, op0: F, op1: X, /, *, rm: Rm | None = None, asm: Assembler | None = None) -> None:
        """Emit `fcvt.d.lu` (2 operands, rounding mode `rm=`)."""
    def s(self, op0: F, op1: F, /, *, asm: Assembler | None = None) -> None:
        """Emit `fcvt.d.s` (2 operands)."""
    def w(self, op0: F, op1: X, /, *, asm: Assembler | None = None) -> None:
        """Emit `fcvt.d.w` (2 operands)."""
    def wu(self, op0: F, op1: X, /, *, asm: Assembler | None = None) -> None:
        """Emit `fcvt.d.wu` (2 operands)."""

class _fcvt_l(Protocol):
    """Namespace of the `fcvt.l.*` mnemonics."""

    def d(self, op0: X, op1: F, /, *, rm: Rm | None = None, asm: Assembler | None = None) -> None:
        """Emit `fcvt.l.d` (2 operands, rounding mode `rm=`)."""
    def s(self, op0: X, op1: F, /, *, rm: Rm | None = None, asm: Assembler | None = None) -> None:
        """Emit `fcvt.l.s` (2 operands, rounding mode `rm=`)."""

class _fcvt_lu(Protocol):
    """Namespace of the `fcvt.lu.*` mnemonics."""

    def d(self, op0: X, op1: F, /, *, rm: Rm | None = None, asm: Assembler | None = None) -> None:
        """Emit `fcvt.lu.d` (2 operands, rounding mode `rm=`)."""
    def s(self, op0: X, op1: F, /, *, rm: Rm | None = None, asm: Assembler | None = None) -> None:
        """Emit `fcvt.lu.s` (2 operands, rounding mode `rm=`)."""

class _fcvt_s(Protocol):
    """Namespace of the `fcvt.s.*` mnemonics."""

    def d(self, op0: F, op1: F, /, *, rm: Rm | None = None, asm: Assembler | None = None) -> None:
        """Emit `fcvt.s.d` (2 operands, rounding mode `rm=`)."""
    def l(self, op0: F, op1: X, /, *, rm: Rm | None = None, asm: Assembler | None = None) -> None:
        """Emit `fcvt.s.l` (2 operands, rounding mode `rm=`)."""
    def lu(self, op0: F, op1: X, /, *, rm: Rm | None = None, asm: Assembler | None = None) -> None:
        """Emit `fcvt.s.lu` (2 operands, rounding mode `rm=`)."""
    def w(self, op0: F, op1: X, /, *, rm: Rm | None = None, asm: Assembler | None = None) -> None:
        """Emit `fcvt.s.w` (2 operands, rounding mode `rm=`)."""
    def wu(self, op0: F, op1: X, /, *, rm: Rm | None = None, asm: Assembler | None = None) -> None:
        """Emit `fcvt.s.wu` (2 operands, rounding mode `rm=`)."""

class _fcvt_w(Protocol):
    """Namespace of the `fcvt.w.*` mnemonics."""

    def d(self, op0: X, op1: F, /, *, rm: Rm | None = None, asm: Assembler | None = None) -> None:
        """Emit `fcvt.w.d` (2 operands, rounding mode `rm=`)."""
    def s(self, op0: X, op1: F, /, *, rm: Rm | None = None, asm: Assembler | None = None) -> None:
        """Emit `fcvt.w.s` (2 operands, rounding mode `rm=`)."""

class _fcvt_wu(Protocol):
    """Namespace of the `fcvt.wu.*` mnemonics."""

    def d(self, op0: X, op1: F, /, *, rm: Rm | None = None, asm: Assembler | None = None) -> None:
        """Emit `fcvt.wu.d` (2 operands, rounding mode `rm=`)."""
    def s(self, op0: X, op1: F, /, *, rm: Rm | None = None, asm: Assembler | None = None) -> None:
        """Emit `fcvt.wu.s` (2 operands, rounding mode `rm=`)."""

class _fdiv(Protocol):
    """Namespace of the `fdiv.*` mnemonics."""

    def d(self, op0: F, op1: F, op2: F, /, *, rm: Rm | None = None, asm: Assembler | None = None) -> None:
        """Emit `fdiv.d` (3 operands, rounding mode `rm=`)."""
    def s(self, op0: F, op1: F, op2: F, /, *, rm: Rm | None = None, asm: Assembler | None = None) -> None:
        """Emit `fdiv.s` (3 operands, rounding mode `rm=`)."""

class _fence(Protocol):
    """Emit `fence` (0 or 2 operands)."""

    @overload
    def __call__(self, *, asm: Assembler | None = None) -> None:
        """Emit `fence` (0 or 2 operands)."""
    @overload
    def __call__(self, op0: FenceSet, op1: FenceSet, /, *, asm: Assembler | None = None) -> None: ...
    def i(self, *, asm: Assembler | None = None) -> None:
        """Emit `fence.i` (0 operands)."""
    def tso(self, *, asm: Assembler | None = None) -> None:
        """Emit `fence.tso` (0 operands)."""

class _feq(Protocol):
    """Namespace of the `feq.*` mnemonics."""

    def d(self, op0: X, op1: F, op2: F, /, *, asm: Assembler | None = None) -> None:
        """Emit `feq.d` (3 operands)."""
    def s(self, op0: X, op1: F, op2: F, /, *, asm: Assembler | None = None) -> None:
        """Emit `feq.s` (3 operands)."""

class _fge(Protocol):
    """Namespace of the `fge.*` mnemonics."""

    def d(self, op0: X, op1: F, op2: F, /, *, asm: Assembler | None = None) -> None:
        """Emit `fge.d` (3 operands)."""
    def s(self, op0: X, op1: F, op2: F, /, *, asm: Assembler | None = None) -> None:
        """Emit `fge.s` (3 operands)."""

class _fgt(Protocol):
    """Namespace of the `fgt.*` mnemonics."""

    def d(self, op0: X, op1: F, op2: F, /, *, asm: Assembler | None = None) -> None:
        """Emit `fgt.d` (3 operands)."""
    def s(self, op0: X, op1: F, op2: F, /, *, asm: Assembler | None = None) -> None:
        """Emit `fgt.s` (3 operands)."""

class _fle(Protocol):
    """Namespace of the `fle.*` mnemonics."""

    def d(self, op0: X, op1: F, op2: F, /, *, asm: Assembler | None = None) -> None:
        """Emit `fle.d` (3 operands)."""
    def s(self, op0: X, op1: F, op2: F, /, *, asm: Assembler | None = None) -> None:
        """Emit `fle.s` (3 operands)."""

class _flt(Protocol):
    """Namespace of the `flt.*` mnemonics."""

    def d(self, op0: X, op1: F, op2: F, /, *, asm: Assembler | None = None) -> None:
        """Emit `flt.d` (3 operands)."""
    def s(self, op0: X, op1: F, op2: F, /, *, asm: Assembler | None = None) -> None:
        """Emit `flt.s` (3 operands)."""

class _fmadd(Protocol):
    """Namespace of the `fmadd.*` mnemonics."""

    def d(self, op0: F, op1: F, op2: F, op3: F, /, *, rm: Rm | None = None, asm: Assembler | None = None) -> None:
        """Emit `fmadd.d` (4 operands, rounding mode `rm=`)."""
    def s(self, op0: F, op1: F, op2: F, op3: F, /, *, rm: Rm | None = None, asm: Assembler | None = None) -> None:
        """Emit `fmadd.s` (4 operands, rounding mode `rm=`)."""

class _fmax(Protocol):
    """Namespace of the `fmax.*` mnemonics."""

    def d(self, op0: F, op1: F, op2: F, /, *, asm: Assembler | None = None) -> None:
        """Emit `fmax.d` (3 operands)."""
    def s(self, op0: F, op1: F, op2: F, /, *, asm: Assembler | None = None) -> None:
        """Emit `fmax.s` (3 operands)."""

class _fmin(Protocol):
    """Namespace of the `fmin.*` mnemonics."""

    def d(self, op0: F, op1: F, op2: F, /, *, asm: Assembler | None = None) -> None:
        """Emit `fmin.d` (3 operands)."""
    def s(self, op0: F, op1: F, op2: F, /, *, asm: Assembler | None = None) -> None:
        """Emit `fmin.s` (3 operands)."""

class _fmsub(Protocol):
    """Namespace of the `fmsub.*` mnemonics."""

    def d(self, op0: F, op1: F, op2: F, op3: F, /, *, rm: Rm | None = None, asm: Assembler | None = None) -> None:
        """Emit `fmsub.d` (4 operands, rounding mode `rm=`)."""
    def s(self, op0: F, op1: F, op2: F, op3: F, /, *, rm: Rm | None = None, asm: Assembler | None = None) -> None:
        """Emit `fmsub.s` (4 operands, rounding mode `rm=`)."""

class _fmul(Protocol):
    """Namespace of the `fmul.*` mnemonics."""

    def d(self, op0: F, op1: F, op2: F, /, *, rm: Rm | None = None, asm: Assembler | None = None) -> None:
        """Emit `fmul.d` (3 operands, rounding mode `rm=`)."""
    def s(self, op0: F, op1: F, op2: F, /, *, rm: Rm | None = None, asm: Assembler | None = None) -> None:
        """Emit `fmul.s` (3 operands, rounding mode `rm=`)."""

class _fmv(Protocol):
    """Namespace of the `fmv.*` mnemonics."""

    d: _fmv_d
    s: _fmv_s
    w: _fmv_w
    x: _fmv_x

class _fmv_d(Protocol):
    """Emit `fmv.d` (2 operands)."""

    def __call__(self, op0: F, op1: F, /, *, asm: Assembler | None = None) -> None:
        """Emit `fmv.d` (2 operands)."""
    def x(self, op0: F, op1: X, /, *, asm: Assembler | None = None) -> None:
        """Emit `fmv.d.x` (2 operands)."""

class _fmv_s(Protocol):
    """Emit `fmv.s` (2 operands)."""

    def __call__(self, op0: F, op1: F, /, *, asm: Assembler | None = None) -> None:
        """Emit `fmv.s` (2 operands)."""
    def x(self, op0: F, op1: X, /, *, asm: Assembler | None = None) -> None:
        """Emit `fmv.s.x` (2 operands)."""

class _fmv_w(Protocol):
    """Namespace of the `fmv.w.*` mnemonics."""

    def x(self, op0: F, op1: X, /, *, asm: Assembler | None = None) -> None:
        """Emit `fmv.w.x` (2 operands)."""

class _fmv_x(Protocol):
    """Namespace of the `fmv.x.*` mnemonics."""

    def d(self, op0: X, op1: F, /, *, asm: Assembler | None = None) -> None:
        """Emit `fmv.x.d` (2 operands)."""
    def s(self, op0: X, op1: F, /, *, asm: Assembler | None = None) -> None:
        """Emit `fmv.x.s` (2 operands)."""
    def w(self, op0: X, op1: F, /, *, asm: Assembler | None = None) -> None:
        """Emit `fmv.x.w` (2 operands)."""

class _fneg(Protocol):
    """Namespace of the `fneg.*` mnemonics."""

    def d(self, op0: F, op1: F, /, *, asm: Assembler | None = None) -> None:
        """Emit `fneg.d` (2 operands)."""
    def s(self, op0: F, op1: F, /, *, asm: Assembler | None = None) -> None:
        """Emit `fneg.s` (2 operands)."""

class _fnmadd(Protocol):
    """Namespace of the `fnmadd.*` mnemonics."""

    def d(self, op0: F, op1: F, op2: F, op3: F, /, *, rm: Rm | None = None, asm: Assembler | None = None) -> None:
        """Emit `fnmadd.d` (4 operands, rounding mode `rm=`)."""
    def s(self, op0: F, op1: F, op2: F, op3: F, /, *, rm: Rm | None = None, asm: Assembler | None = None) -> None:
        """Emit `fnmadd.s` (4 operands, rounding mode `rm=`)."""

class _fnmsub(Protocol):
    """Namespace of the `fnmsub.*` mnemonics."""

    def d(self, op0: F, op1: F, op2: F, op3: F, /, *, rm: Rm | None = None, asm: Assembler | None = None) -> None:
        """Emit `fnmsub.d` (4 operands, rounding mode `rm=`)."""
    def s(self, op0: F, op1: F, op2: F, op3: F, /, *, rm: Rm | None = None, asm: Assembler | None = None) -> None:
        """Emit `fnmsub.s` (4 operands, rounding mode `rm=`)."""

class _fsgnj(Protocol):
    """Namespace of the `fsgnj.*` mnemonics."""

    def d(self, op0: F, op1: F, op2: F, /, *, asm: Assembler | None = None) -> None:
        """Emit `fsgnj.d` (3 operands)."""
    def s(self, op0: F, op1: F, op2: F, /, *, asm: Assembler | None = None) -> None:
        """Emit `fsgnj.s` (3 operands)."""

class _fsgnjn(Protocol):
    """Namespace of the `fsgnjn.*` mnemonics."""

    def d(self, op0: F, op1: F, op2: F, /, *, asm: Assembler | None = None) -> None:
        """Emit `fsgnjn.d` (3 operands)."""
    def s(self, op0: F, op1: F, op2: F, /, *, asm: Assembler | None = None) -> None:
        """Emit `fsgnjn.s` (3 operands)."""

class _fsgnjx(Protocol):
    """Namespace of the `fsgnjx.*` mnemonics."""

    def d(self, op0: F, op1: F, op2: F, /, *, asm: Assembler | None = None) -> None:
        """Emit `fsgnjx.d` (3 operands)."""
    def s(self, op0: F, op1: F, op2: F, /, *, asm: Assembler | None = None) -> None:
        """Emit `fsgnjx.s` (3 operands)."""

class _fsqrt(Protocol):
    """Namespace of the `fsqrt.*` mnemonics."""

    def d(self, op0: F, op1: F, /, *, rm: Rm | None = None, asm: Assembler | None = None) -> None:
        """Emit `fsqrt.d` (2 operands, rounding mode `rm=`)."""
    def s(self, op0: F, op1: F, /, *, rm: Rm | None = None, asm: Assembler | None = None) -> None:
        """Emit `fsqrt.s` (2 operands, rounding mode `rm=`)."""

class _fsub(Protocol):
    """Namespace of the `fsub.*` mnemonics."""

    def d(self, op0: F, op1: F, op2: F, /, *, rm: Rm | None = None, asm: Assembler | None = None) -> None:
        """Emit `fsub.d` (3 operands, rounding mode `rm=`)."""
    def s(self, op0: F, op1: F, op2: F, /, *, rm: Rm | None = None, asm: Assembler | None = None) -> None:
        """Emit `fsub.s` (3 operands, rounding mode `rm=`)."""

class _lr(Protocol):
    """Namespace of the `lr.*` mnemonics."""

    d: _lr_d
    w: _lr_w

class _lr_d(Protocol):
    """Emit `lr.d` (2 operands)."""

    def __call__(self, op0: X, op1: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `lr.d` (2 operands)."""
    def aq(self, op0: X, op1: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `lr.d.aq` (2 operands)."""
    def aqrl(self, op0: X, op1: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `lr.d.aqrl` (2 operands)."""
    def rl(self, op0: X, op1: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `lr.d.rl` (2 operands)."""

class _lr_w(Protocol):
    """Emit `lr.w` (2 operands)."""

    def __call__(self, op0: X, op1: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `lr.w` (2 operands)."""
    def aq(self, op0: X, op1: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `lr.w.aq` (2 operands)."""
    def aqrl(self, op0: X, op1: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `lr.w.aqrl` (2 operands)."""
    def rl(self, op0: X, op1: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `lr.w.rl` (2 operands)."""

class _orc(Protocol):
    """Namespace of the `orc.*` mnemonics."""

    def b(self, op0: X, op1: X, /, *, asm: Assembler | None = None) -> None:
        """Emit `orc.b` (2 operands)."""

class _sc(Protocol):
    """Namespace of the `sc.*` mnemonics."""

    d: _sc_d
    w: _sc_w

class _sc_d(Protocol):
    """Emit `sc.d` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `sc.d` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `sc.d.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `sc.d.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `sc.d.rl` (3 operands)."""

class _sc_w(Protocol):
    """Emit `sc.w` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `sc.w` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `sc.w.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `sc.w.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
        """Emit `sc.w.rl` (3 operands)."""

class _sext(Protocol):
    """Namespace of the `sext.*` mnemonics."""

    def b(self, op0: X, op1: X, /, *, asm: Assembler | None = None) -> None:
        """Emit `sext.b` (2 operands)."""
    def h(self, op0: X, op1: X, /, *, asm: Assembler | None = None) -> None:
        """Emit `sext.h` (2 operands)."""
    def w(self, op0: X, op1: X, /, *, asm: Assembler | None = None) -> None:
        """Emit `sext.w` (2 operands)."""

class _sh1add(Protocol):
    """Emit `sh1add` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
        """Emit `sh1add` (3 operands)."""
    def uw(self, op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
        """Emit `sh1add.uw` (3 operands)."""

class _sh2add(Protocol):
    """Emit `sh2add` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
        """Emit `sh2add` (3 operands)."""
    def uw(self, op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
        """Emit `sh2add.uw` (3 operands)."""

class _sh3add(Protocol):
    """Emit `sh3add` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
        """Emit `sh3add` (3 operands)."""
    def uw(self, op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
        """Emit `sh3add.uw` (3 operands)."""

class _slli(Protocol):
    """Emit `slli` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: _Imm, /, *, asm: Assembler | None = None) -> None:
        """Emit `slli` (3 operands)."""
    def uw(self, op0: X, op1: X, op2: _Imm, /, *, asm: Assembler | None = None) -> None:
        """Emit `slli.uw` (3 operands)."""

class _zext(Protocol):
    """Namespace of the `zext.*` mnemonics."""

    def b(self, op0: X, op1: X, /, *, asm: Assembler | None = None) -> None:
        """Emit `zext.b` (2 operands)."""
    def h(self, op0: X, op1: X, /, *, asm: Assembler | None = None) -> None:
        """Emit `zext.h` (2 operands)."""
    def w(self, op0: X, op1: X, /, *, asm: Assembler | None = None) -> None:
        """Emit `zext.w` (2 operands)."""

class _add_method(Protocol):
    """Emit `add` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `add` (3 operands)."""
    def uw(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `add.uw` (3 operands)."""

class _amoadd_method(Protocol):
    """Namespace of the `amoadd.*` mnemonics."""

    d: _amoadd_d_method
    w: _amoadd_w_method

class _amoadd_d_method(Protocol):
    """Emit `amoadd.d` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoadd.d` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoadd.d.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoadd.d.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoadd.d.rl` (3 operands)."""

class _amoadd_w_method(Protocol):
    """Emit `amoadd.w` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoadd.w` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoadd.w.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoadd.w.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoadd.w.rl` (3 operands)."""

class _amoand_method(Protocol):
    """Namespace of the `amoand.*` mnemonics."""

    d: _amoand_d_method
    w: _amoand_w_method

class _amoand_d_method(Protocol):
    """Emit `amoand.d` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoand.d` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoand.d.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoand.d.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoand.d.rl` (3 operands)."""

class _amoand_w_method(Protocol):
    """Emit `amoand.w` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoand.w` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoand.w.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoand.w.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoand.w.rl` (3 operands)."""

class _amomax_method(Protocol):
    """Namespace of the `amomax.*` mnemonics."""

    d: _amomax_d_method
    w: _amomax_w_method

class _amomax_d_method(Protocol):
    """Emit `amomax.d` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amomax.d` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amomax.d.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amomax.d.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amomax.d.rl` (3 operands)."""

class _amomax_w_method(Protocol):
    """Emit `amomax.w` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amomax.w` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amomax.w.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amomax.w.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amomax.w.rl` (3 operands)."""

class _amomaxu_method(Protocol):
    """Namespace of the `amomaxu.*` mnemonics."""

    d: _amomaxu_d_method
    w: _amomaxu_w_method

class _amomaxu_d_method(Protocol):
    """Emit `amomaxu.d` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amomaxu.d` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amomaxu.d.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amomaxu.d.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amomaxu.d.rl` (3 operands)."""

class _amomaxu_w_method(Protocol):
    """Emit `amomaxu.w` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amomaxu.w` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amomaxu.w.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amomaxu.w.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amomaxu.w.rl` (3 operands)."""

class _amomin_method(Protocol):
    """Namespace of the `amomin.*` mnemonics."""

    d: _amomin_d_method
    w: _amomin_w_method

class _amomin_d_method(Protocol):
    """Emit `amomin.d` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amomin.d` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amomin.d.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amomin.d.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amomin.d.rl` (3 operands)."""

class _amomin_w_method(Protocol):
    """Emit `amomin.w` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amomin.w` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amomin.w.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amomin.w.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amomin.w.rl` (3 operands)."""

class _amominu_method(Protocol):
    """Namespace of the `amominu.*` mnemonics."""

    d: _amominu_d_method
    w: _amominu_w_method

class _amominu_d_method(Protocol):
    """Emit `amominu.d` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amominu.d` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amominu.d.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amominu.d.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amominu.d.rl` (3 operands)."""

class _amominu_w_method(Protocol):
    """Emit `amominu.w` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amominu.w` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amominu.w.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amominu.w.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amominu.w.rl` (3 operands)."""

class _amoor_method(Protocol):
    """Namespace of the `amoor.*` mnemonics."""

    d: _amoor_d_method
    w: _amoor_w_method

class _amoor_d_method(Protocol):
    """Emit `amoor.d` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoor.d` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoor.d.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoor.d.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoor.d.rl` (3 operands)."""

class _amoor_w_method(Protocol):
    """Emit `amoor.w` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoor.w` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoor.w.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoor.w.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoor.w.rl` (3 operands)."""

class _amoswap_method(Protocol):
    """Namespace of the `amoswap.*` mnemonics."""

    d: _amoswap_d_method
    w: _amoswap_w_method

class _amoswap_d_method(Protocol):
    """Emit `amoswap.d` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoswap.d` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoswap.d.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoswap.d.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoswap.d.rl` (3 operands)."""

class _amoswap_w_method(Protocol):
    """Emit `amoswap.w` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoswap.w` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoswap.w.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoswap.w.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoswap.w.rl` (3 operands)."""

class _amoxor_method(Protocol):
    """Namespace of the `amoxor.*` mnemonics."""

    d: _amoxor_d_method
    w: _amoxor_w_method

class _amoxor_d_method(Protocol):
    """Emit `amoxor.d` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoxor.d` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoxor.d.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoxor.d.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoxor.d.rl` (3 operands)."""

class _amoxor_w_method(Protocol):
    """Emit `amoxor.w` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoxor.w` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoxor.w.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoxor.w.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `amoxor.w.rl` (3 operands)."""

class _fabs_method(Protocol):
    """Namespace of the `fabs.*` mnemonics."""

    def d(self, op0: F, op1: F, /) -> None:
        """Emit `fabs.d` (2 operands)."""
    def s(self, op0: F, op1: F, /) -> None:
        """Emit `fabs.s` (2 operands)."""

class _fadd_method(Protocol):
    """Namespace of the `fadd.*` mnemonics."""

    def d(self, op0: F, op1: F, op2: F, /, *, rm: Rm | None = None) -> None:
        """Emit `fadd.d` (3 operands, rounding mode `rm=`)."""
    def s(self, op0: F, op1: F, op2: F, /, *, rm: Rm | None = None) -> None:
        """Emit `fadd.s` (3 operands, rounding mode `rm=`)."""

class _fclass_method(Protocol):
    """Namespace of the `fclass.*` mnemonics."""

    def d(self, op0: X, op1: F, /) -> None:
        """Emit `fclass.d` (2 operands)."""
    def s(self, op0: X, op1: F, /) -> None:
        """Emit `fclass.s` (2 operands)."""

class _fcvt_method(Protocol):
    """Namespace of the `fcvt.*` mnemonics."""

    d: _fcvt_d_method
    l: _fcvt_l_method
    lu: _fcvt_lu_method
    s: _fcvt_s_method
    w: _fcvt_w_method
    wu: _fcvt_wu_method

class _fcvt_d_method(Protocol):
    """Namespace of the `fcvt.d.*` mnemonics."""

    def l(self, op0: F, op1: X, /, *, rm: Rm | None = None) -> None:
        """Emit `fcvt.d.l` (2 operands, rounding mode `rm=`)."""
    def lu(self, op0: F, op1: X, /, *, rm: Rm | None = None) -> None:
        """Emit `fcvt.d.lu` (2 operands, rounding mode `rm=`)."""
    def s(self, op0: F, op1: F, /) -> None:
        """Emit `fcvt.d.s` (2 operands)."""
    def w(self, op0: F, op1: X, /) -> None:
        """Emit `fcvt.d.w` (2 operands)."""
    def wu(self, op0: F, op1: X, /) -> None:
        """Emit `fcvt.d.wu` (2 operands)."""

class _fcvt_l_method(Protocol):
    """Namespace of the `fcvt.l.*` mnemonics."""

    def d(self, op0: X, op1: F, /, *, rm: Rm | None = None) -> None:
        """Emit `fcvt.l.d` (2 operands, rounding mode `rm=`)."""
    def s(self, op0: X, op1: F, /, *, rm: Rm | None = None) -> None:
        """Emit `fcvt.l.s` (2 operands, rounding mode `rm=`)."""

class _fcvt_lu_method(Protocol):
    """Namespace of the `fcvt.lu.*` mnemonics."""

    def d(self, op0: X, op1: F, /, *, rm: Rm | None = None) -> None:
        """Emit `fcvt.lu.d` (2 operands, rounding mode `rm=`)."""
    def s(self, op0: X, op1: F, /, *, rm: Rm | None = None) -> None:
        """Emit `fcvt.lu.s` (2 operands, rounding mode `rm=`)."""

class _fcvt_s_method(Protocol):
    """Namespace of the `fcvt.s.*` mnemonics."""

    def d(self, op0: F, op1: F, /, *, rm: Rm | None = None) -> None:
        """Emit `fcvt.s.d` (2 operands, rounding mode `rm=`)."""
    def l(self, op0: F, op1: X, /, *, rm: Rm | None = None) -> None:
        """Emit `fcvt.s.l` (2 operands, rounding mode `rm=`)."""
    def lu(self, op0: F, op1: X, /, *, rm: Rm | None = None) -> None:
        """Emit `fcvt.s.lu` (2 operands, rounding mode `rm=`)."""
    def w(self, op0: F, op1: X, /, *, rm: Rm | None = None) -> None:
        """Emit `fcvt.s.w` (2 operands, rounding mode `rm=`)."""
    def wu(self, op0: F, op1: X, /, *, rm: Rm | None = None) -> None:
        """Emit `fcvt.s.wu` (2 operands, rounding mode `rm=`)."""

class _fcvt_w_method(Protocol):
    """Namespace of the `fcvt.w.*` mnemonics."""

    def d(self, op0: X, op1: F, /, *, rm: Rm | None = None) -> None:
        """Emit `fcvt.w.d` (2 operands, rounding mode `rm=`)."""
    def s(self, op0: X, op1: F, /, *, rm: Rm | None = None) -> None:
        """Emit `fcvt.w.s` (2 operands, rounding mode `rm=`)."""

class _fcvt_wu_method(Protocol):
    """Namespace of the `fcvt.wu.*` mnemonics."""

    def d(self, op0: X, op1: F, /, *, rm: Rm | None = None) -> None:
        """Emit `fcvt.wu.d` (2 operands, rounding mode `rm=`)."""
    def s(self, op0: X, op1: F, /, *, rm: Rm | None = None) -> None:
        """Emit `fcvt.wu.s` (2 operands, rounding mode `rm=`)."""

class _fdiv_method(Protocol):
    """Namespace of the `fdiv.*` mnemonics."""

    def d(self, op0: F, op1: F, op2: F, /, *, rm: Rm | None = None) -> None:
        """Emit `fdiv.d` (3 operands, rounding mode `rm=`)."""
    def s(self, op0: F, op1: F, op2: F, /, *, rm: Rm | None = None) -> None:
        """Emit `fdiv.s` (3 operands, rounding mode `rm=`)."""

class _fence_method(Protocol):
    """Emit `fence` (0 or 2 operands)."""

    @overload
    def __call__(self) -> None:
        """Emit `fence` (0 or 2 operands)."""
    @overload
    def __call__(self, op0: FenceSet, op1: FenceSet, /) -> None: ...
    def i(self) -> None:
        """Emit `fence.i` (0 operands)."""
    def tso(self) -> None:
        """Emit `fence.tso` (0 operands)."""

class _feq_method(Protocol):
    """Namespace of the `feq.*` mnemonics."""

    def d(self, op0: X, op1: F, op2: F, /) -> None:
        """Emit `feq.d` (3 operands)."""
    def s(self, op0: X, op1: F, op2: F, /) -> None:
        """Emit `feq.s` (3 operands)."""

class _fge_method(Protocol):
    """Namespace of the `fge.*` mnemonics."""

    def d(self, op0: X, op1: F, op2: F, /) -> None:
        """Emit `fge.d` (3 operands)."""
    def s(self, op0: X, op1: F, op2: F, /) -> None:
        """Emit `fge.s` (3 operands)."""

class _fgt_method(Protocol):
    """Namespace of the `fgt.*` mnemonics."""

    def d(self, op0: X, op1: F, op2: F, /) -> None:
        """Emit `fgt.d` (3 operands)."""
    def s(self, op0: X, op1: F, op2: F, /) -> None:
        """Emit `fgt.s` (3 operands)."""

class _fle_method(Protocol):
    """Namespace of the `fle.*` mnemonics."""

    def d(self, op0: X, op1: F, op2: F, /) -> None:
        """Emit `fle.d` (3 operands)."""
    def s(self, op0: X, op1: F, op2: F, /) -> None:
        """Emit `fle.s` (3 operands)."""

class _flt_method(Protocol):
    """Namespace of the `flt.*` mnemonics."""

    def d(self, op0: X, op1: F, op2: F, /) -> None:
        """Emit `flt.d` (3 operands)."""
    def s(self, op0: X, op1: F, op2: F, /) -> None:
        """Emit `flt.s` (3 operands)."""

class _fmadd_method(Protocol):
    """Namespace of the `fmadd.*` mnemonics."""

    def d(self, op0: F, op1: F, op2: F, op3: F, /, *, rm: Rm | None = None) -> None:
        """Emit `fmadd.d` (4 operands, rounding mode `rm=`)."""
    def s(self, op0: F, op1: F, op2: F, op3: F, /, *, rm: Rm | None = None) -> None:
        """Emit `fmadd.s` (4 operands, rounding mode `rm=`)."""

class _fmax_method(Protocol):
    """Namespace of the `fmax.*` mnemonics."""

    def d(self, op0: F, op1: F, op2: F, /) -> None:
        """Emit `fmax.d` (3 operands)."""
    def s(self, op0: F, op1: F, op2: F, /) -> None:
        """Emit `fmax.s` (3 operands)."""

class _fmin_method(Protocol):
    """Namespace of the `fmin.*` mnemonics."""

    def d(self, op0: F, op1: F, op2: F, /) -> None:
        """Emit `fmin.d` (3 operands)."""
    def s(self, op0: F, op1: F, op2: F, /) -> None:
        """Emit `fmin.s` (3 operands)."""

class _fmsub_method(Protocol):
    """Namespace of the `fmsub.*` mnemonics."""

    def d(self, op0: F, op1: F, op2: F, op3: F, /, *, rm: Rm | None = None) -> None:
        """Emit `fmsub.d` (4 operands, rounding mode `rm=`)."""
    def s(self, op0: F, op1: F, op2: F, op3: F, /, *, rm: Rm | None = None) -> None:
        """Emit `fmsub.s` (4 operands, rounding mode `rm=`)."""

class _fmul_method(Protocol):
    """Namespace of the `fmul.*` mnemonics."""

    def d(self, op0: F, op1: F, op2: F, /, *, rm: Rm | None = None) -> None:
        """Emit `fmul.d` (3 operands, rounding mode `rm=`)."""
    def s(self, op0: F, op1: F, op2: F, /, *, rm: Rm | None = None) -> None:
        """Emit `fmul.s` (3 operands, rounding mode `rm=`)."""

class _fmv_method(Protocol):
    """Namespace of the `fmv.*` mnemonics."""

    d: _fmv_d_method
    s: _fmv_s_method
    w: _fmv_w_method
    x: _fmv_x_method

class _fmv_d_method(Protocol):
    """Emit `fmv.d` (2 operands)."""

    def __call__(self, op0: F, op1: F, /) -> None:
        """Emit `fmv.d` (2 operands)."""
    def x(self, op0: F, op1: X, /) -> None:
        """Emit `fmv.d.x` (2 operands)."""

class _fmv_s_method(Protocol):
    """Emit `fmv.s` (2 operands)."""

    def __call__(self, op0: F, op1: F, /) -> None:
        """Emit `fmv.s` (2 operands)."""
    def x(self, op0: F, op1: X, /) -> None:
        """Emit `fmv.s.x` (2 operands)."""

class _fmv_w_method(Protocol):
    """Namespace of the `fmv.w.*` mnemonics."""

    def x(self, op0: F, op1: X, /) -> None:
        """Emit `fmv.w.x` (2 operands)."""

class _fmv_x_method(Protocol):
    """Namespace of the `fmv.x.*` mnemonics."""

    def d(self, op0: X, op1: F, /) -> None:
        """Emit `fmv.x.d` (2 operands)."""
    def s(self, op0: X, op1: F, /) -> None:
        """Emit `fmv.x.s` (2 operands)."""
    def w(self, op0: X, op1: F, /) -> None:
        """Emit `fmv.x.w` (2 operands)."""

class _fneg_method(Protocol):
    """Namespace of the `fneg.*` mnemonics."""

    def d(self, op0: F, op1: F, /) -> None:
        """Emit `fneg.d` (2 operands)."""
    def s(self, op0: F, op1: F, /) -> None:
        """Emit `fneg.s` (2 operands)."""

class _fnmadd_method(Protocol):
    """Namespace of the `fnmadd.*` mnemonics."""

    def d(self, op0: F, op1: F, op2: F, op3: F, /, *, rm: Rm | None = None) -> None:
        """Emit `fnmadd.d` (4 operands, rounding mode `rm=`)."""
    def s(self, op0: F, op1: F, op2: F, op3: F, /, *, rm: Rm | None = None) -> None:
        """Emit `fnmadd.s` (4 operands, rounding mode `rm=`)."""

class _fnmsub_method(Protocol):
    """Namespace of the `fnmsub.*` mnemonics."""

    def d(self, op0: F, op1: F, op2: F, op3: F, /, *, rm: Rm | None = None) -> None:
        """Emit `fnmsub.d` (4 operands, rounding mode `rm=`)."""
    def s(self, op0: F, op1: F, op2: F, op3: F, /, *, rm: Rm | None = None) -> None:
        """Emit `fnmsub.s` (4 operands, rounding mode `rm=`)."""

class _fsgnj_method(Protocol):
    """Namespace of the `fsgnj.*` mnemonics."""

    def d(self, op0: F, op1: F, op2: F, /) -> None:
        """Emit `fsgnj.d` (3 operands)."""
    def s(self, op0: F, op1: F, op2: F, /) -> None:
        """Emit `fsgnj.s` (3 operands)."""

class _fsgnjn_method(Protocol):
    """Namespace of the `fsgnjn.*` mnemonics."""

    def d(self, op0: F, op1: F, op2: F, /) -> None:
        """Emit `fsgnjn.d` (3 operands)."""
    def s(self, op0: F, op1: F, op2: F, /) -> None:
        """Emit `fsgnjn.s` (3 operands)."""

class _fsgnjx_method(Protocol):
    """Namespace of the `fsgnjx.*` mnemonics."""

    def d(self, op0: F, op1: F, op2: F, /) -> None:
        """Emit `fsgnjx.d` (3 operands)."""
    def s(self, op0: F, op1: F, op2: F, /) -> None:
        """Emit `fsgnjx.s` (3 operands)."""

class _fsqrt_method(Protocol):
    """Namespace of the `fsqrt.*` mnemonics."""

    def d(self, op0: F, op1: F, /, *, rm: Rm | None = None) -> None:
        """Emit `fsqrt.d` (2 operands, rounding mode `rm=`)."""
    def s(self, op0: F, op1: F, /, *, rm: Rm | None = None) -> None:
        """Emit `fsqrt.s` (2 operands, rounding mode `rm=`)."""

class _fsub_method(Protocol):
    """Namespace of the `fsub.*` mnemonics."""

    def d(self, op0: F, op1: F, op2: F, /, *, rm: Rm | None = None) -> None:
        """Emit `fsub.d` (3 operands, rounding mode `rm=`)."""
    def s(self, op0: F, op1: F, op2: F, /, *, rm: Rm | None = None) -> None:
        """Emit `fsub.s` (3 operands, rounding mode `rm=`)."""

class _lr_method(Protocol):
    """Namespace of the `lr.*` mnemonics."""

    d: _lr_d_method
    w: _lr_w_method

class _lr_d_method(Protocol):
    """Emit `lr.d` (2 operands)."""

    def __call__(self, op0: X, op1: MemExpr, /) -> None:
        """Emit `lr.d` (2 operands)."""
    def aq(self, op0: X, op1: MemExpr, /) -> None:
        """Emit `lr.d.aq` (2 operands)."""
    def aqrl(self, op0: X, op1: MemExpr, /) -> None:
        """Emit `lr.d.aqrl` (2 operands)."""
    def rl(self, op0: X, op1: MemExpr, /) -> None:
        """Emit `lr.d.rl` (2 operands)."""

class _lr_w_method(Protocol):
    """Emit `lr.w` (2 operands)."""

    def __call__(self, op0: X, op1: MemExpr, /) -> None:
        """Emit `lr.w` (2 operands)."""
    def aq(self, op0: X, op1: MemExpr, /) -> None:
        """Emit `lr.w.aq` (2 operands)."""
    def aqrl(self, op0: X, op1: MemExpr, /) -> None:
        """Emit `lr.w.aqrl` (2 operands)."""
    def rl(self, op0: X, op1: MemExpr, /) -> None:
        """Emit `lr.w.rl` (2 operands)."""

class _orc_method(Protocol):
    """Namespace of the `orc.*` mnemonics."""

    def b(self, op0: X, op1: X, /) -> None:
        """Emit `orc.b` (2 operands)."""

class _sc_method(Protocol):
    """Namespace of the `sc.*` mnemonics."""

    d: _sc_d_method
    w: _sc_w_method

class _sc_d_method(Protocol):
    """Emit `sc.d` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `sc.d` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `sc.d.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `sc.d.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `sc.d.rl` (3 operands)."""

class _sc_w_method(Protocol):
    """Emit `sc.w` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `sc.w` (3 operands)."""
    def aq(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `sc.w.aq` (3 operands)."""
    def aqrl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `sc.w.aqrl` (3 operands)."""
    def rl(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `sc.w.rl` (3 operands)."""

class _sext_method(Protocol):
    """Namespace of the `sext.*` mnemonics."""

    def b(self, op0: X, op1: X, /) -> None:
        """Emit `sext.b` (2 operands)."""
    def h(self, op0: X, op1: X, /) -> None:
        """Emit `sext.h` (2 operands)."""
    def w(self, op0: X, op1: X, /) -> None:
        """Emit `sext.w` (2 operands)."""

class _sh1add_method(Protocol):
    """Emit `sh1add` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `sh1add` (3 operands)."""
    def uw(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `sh1add.uw` (3 operands)."""

class _sh2add_method(Protocol):
    """Emit `sh2add` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `sh2add` (3 operands)."""
    def uw(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `sh2add.uw` (3 operands)."""

class _sh3add_method(Protocol):
    """Emit `sh3add` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `sh3add` (3 operands)."""
    def uw(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `sh3add.uw` (3 operands)."""

class _slli_method(Protocol):
    """Emit `slli` (3 operands)."""

    def __call__(self, op0: X, op1: X, op2: _Imm, /) -> None:
        """Emit `slli` (3 operands)."""
    def uw(self, op0: X, op1: X, op2: _Imm, /) -> None:
        """Emit `slli.uw` (3 operands)."""

class _zext_method(Protocol):
    """Namespace of the `zext.*` mnemonics."""

    def b(self, op0: X, op1: X, /) -> None:
        """Emit `zext.b` (2 operands)."""
    def h(self, op0: X, op1: X, /) -> None:
        """Emit `zext.h` (2 operands)."""
    def w(self, op0: X, op1: X, /) -> None:
        """Emit `zext.w` (2 operands)."""

class _NotAnInstruction:
    """What an unknown attribute of an arch assembler is to a type checker:
    not callable, so `a.movv(...)` is reported."""


class Riscv64Assembler(Assembler):
    """An Assembler for riscv64. `Assembler("riscv64")` returns one; its
    mnemonic methods are typed in the stub."""

    def __getattr__(self, name: str) -> _NotAnInstruction:  # type: ignore[override]  # pyright: ignore[reportIncompatibleMethodOverride]
        """Unknown names are not instructions."""

    add: _add_method
    def addi(self, op0: X, op1: X, op2: _Imm, /) -> None:
        """Emit `addi` (3 operands)."""
    def addiw(self, op0: X, op1: X, op2: _Imm, /) -> None:
        """Emit `addiw` (3 operands)."""
    def addw(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `addw` (3 operands)."""
    amoadd: _amoadd_method
    amoand: _amoand_method
    amomax: _amomax_method
    amomaxu: _amomaxu_method
    amomin: _amomin_method
    amominu: _amominu_method
    amoor: _amoor_method
    amoswap: _amoswap_method
    amoxor: _amoxor_method
    def and_(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `and` (3 operands)."""
    def andi(self, op0: X, op1: X, op2: _Imm, /) -> None:
        """Emit `andi` (3 operands)."""
    def andn(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `andn` (3 operands)."""
    def auipc(self, op0: X, op1: _Imm, /) -> None:
        """Emit `auipc` (2 operands)."""
    def beq(self, op0: X, op1: X, op2: _Target, /) -> None:
        """Emit `beq` (3 operands)."""
    def beqz(self, op0: X, op1: _Target, /) -> None:
        """Emit `beqz` (2 operands)."""
    def bge(self, op0: X, op1: X, op2: _Target, /) -> None:
        """Emit `bge` (3 operands)."""
    def bgeu(self, op0: X, op1: X, op2: _Target, /) -> None:
        """Emit `bgeu` (3 operands)."""
    def bgez(self, op0: X, op1: _Target, /) -> None:
        """Emit `bgez` (2 operands)."""
    def bgt(self, op0: X, op1: X, op2: _Target, /) -> None:
        """Emit `bgt` (3 operands)."""
    def bgtu(self, op0: X, op1: X, op2: _Target, /) -> None:
        """Emit `bgtu` (3 operands)."""
    def bgtz(self, op0: X, op1: _Target, /) -> None:
        """Emit `bgtz` (2 operands)."""
    def ble(self, op0: X, op1: X, op2: _Target, /) -> None:
        """Emit `ble` (3 operands)."""
    def bleu(self, op0: X, op1: X, op2: _Target, /) -> None:
        """Emit `bleu` (3 operands)."""
    def blez(self, op0: X, op1: _Target, /) -> None:
        """Emit `blez` (2 operands)."""
    def blt(self, op0: X, op1: X, op2: _Target, /) -> None:
        """Emit `blt` (3 operands)."""
    def bltu(self, op0: X, op1: X, op2: _Target, /) -> None:
        """Emit `bltu` (3 operands)."""
    def bltz(self, op0: X, op1: _Target, /) -> None:
        """Emit `bltz` (2 operands)."""
    def bne(self, op0: X, op1: X, op2: _Target, /) -> None:
        """Emit `bne` (3 operands)."""
    def bnez(self, op0: X, op1: _Target, /) -> None:
        """Emit `bnez` (2 operands)."""
    def call(self, op0: _Target, /) -> None:
        """Emit `call` (1 operands)."""
    def clz(self, op0: X, op1: X, /) -> None:
        """Emit `clz` (2 operands)."""
    def clzw(self, op0: X, op1: X, /) -> None:
        """Emit `clzw` (2 operands)."""
    def cpop(self, op0: X, op1: X, /) -> None:
        """Emit `cpop` (2 operands)."""
    def cpopw(self, op0: X, op1: X, /) -> None:
        """Emit `cpopw` (2 operands)."""
    def csrc(self, op0: _Imm | CsrName, op1: X, /) -> None:
        """Emit `csrc` (2 operands)."""
    def csrci(self, op0: _Imm | CsrName, op1: _Imm, /) -> None:
        """Emit `csrci` (2 operands)."""
    def csrr(self, op0: X, op1: _Imm | CsrName, /) -> None:
        """Emit `csrr` (2 operands)."""
    def csrrc(self, op0: X, op1: _Imm | CsrName, op2: X, /) -> None:
        """Emit `csrrc` (3 operands)."""
    def csrrci(self, op0: X, op1: _Imm | CsrName, op2: _Imm, /) -> None:
        """Emit `csrrci` (3 operands)."""
    def csrrs(self, op0: X, op1: _Imm | CsrName, op2: X, /) -> None:
        """Emit `csrrs` (3 operands)."""
    def csrrsi(self, op0: X, op1: _Imm | CsrName, op2: _Imm, /) -> None:
        """Emit `csrrsi` (3 operands)."""
    def csrrw(self, op0: X, op1: _Imm | CsrName, op2: X, /) -> None:
        """Emit `csrrw` (3 operands)."""
    def csrrwi(self, op0: X, op1: _Imm | CsrName, op2: _Imm, /) -> None:
        """Emit `csrrwi` (3 operands)."""
    def csrs(self, op0: _Imm | CsrName, op1: X, /) -> None:
        """Emit `csrs` (2 operands)."""
    def csrsi(self, op0: _Imm | CsrName, op1: _Imm, /) -> None:
        """Emit `csrsi` (2 operands)."""
    def csrw(self, op0: _Imm | CsrName, op1: X, /) -> None:
        """Emit `csrw` (2 operands)."""
    def csrwi(self, op0: _Imm | CsrName, op1: _Imm, /) -> None:
        """Emit `csrwi` (2 operands)."""
    def ctz(self, op0: X, op1: X, /) -> None:
        """Emit `ctz` (2 operands)."""
    def ctzw(self, op0: X, op1: X, /) -> None:
        """Emit `ctzw` (2 operands)."""
    def div(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `div` (3 operands)."""
    def divu(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `divu` (3 operands)."""
    def divuw(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `divuw` (3 operands)."""
    def divw(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `divw` (3 operands)."""
    def ebreak(self) -> None:
        """Emit `ebreak` (0 operands)."""
    def ecall(self) -> None:
        """Emit `ecall` (0 operands)."""
    fabs: _fabs_method
    fadd: _fadd_method
    fclass: _fclass_method
    fcvt: _fcvt_method
    fdiv: _fdiv_method
    fence: _fence_method
    feq: _feq_method
    fge: _fge_method
    fgt: _fgt_method
    @overload
    def fld(self, op0: F, op1: MemExpr, /) -> None:
        """Emit `fld` (2 or 3 operands)."""
    @overload
    def fld(self, op0: F, op1: _Target, op2: X, /) -> None: ...
    fle: _fle_method
    flt: _flt_method
    @overload
    def flw(self, op0: F, op1: MemExpr, /) -> None:
        """Emit `flw` (2 or 3 operands)."""
    @overload
    def flw(self, op0: F, op1: _Target, op2: X, /) -> None: ...
    fmadd: _fmadd_method
    fmax: _fmax_method
    fmin: _fmin_method
    fmsub: _fmsub_method
    fmul: _fmul_method
    fmv: _fmv_method
    fneg: _fneg_method
    fnmadd: _fnmadd_method
    fnmsub: _fnmsub_method
    def frcsr(self, op0: X, /) -> None:
        """Emit `frcsr` (1 operands)."""
    def frflags(self, op0: X, /) -> None:
        """Emit `frflags` (1 operands)."""
    def frrm(self, op0: X, /) -> None:
        """Emit `frrm` (1 operands)."""
    @overload
    def fscsr(self, op0: X, /) -> None:
        """Emit `fscsr` (1 or 2 operands)."""
    @overload
    def fscsr(self, op0: X, op1: X, /) -> None: ...
    @overload
    def fsd(self, op0: F, op1: MemExpr, /) -> None:
        """Emit `fsd` (2 or 3 operands)."""
    @overload
    def fsd(self, op0: F, op1: _Target, op2: X, /) -> None: ...
    @overload
    def fsflags(self, op0: X, /) -> None:
        """Emit `fsflags` (1 or 2 operands)."""
    @overload
    def fsflags(self, op0: X, op1: X, /) -> None: ...
    @overload
    def fsflagsi(self, op0: _Imm, /) -> None:
        """Emit `fsflagsi` (1 or 2 operands)."""
    @overload
    def fsflagsi(self, op0: X, op1: _Imm, /) -> None: ...
    fsgnj: _fsgnj_method
    fsgnjn: _fsgnjn_method
    fsgnjx: _fsgnjx_method
    fsqrt: _fsqrt_method
    @overload
    def fsrm(self, op0: X, /) -> None:
        """Emit `fsrm` (1 or 2 operands)."""
    @overload
    def fsrm(self, op0: X, op1: X, /) -> None: ...
    @overload
    def fsrmi(self, op0: _Imm, /) -> None:
        """Emit `fsrmi` (1 or 2 operands)."""
    @overload
    def fsrmi(self, op0: X, op1: _Imm, /) -> None: ...
    fsub: _fsub_method
    @overload
    def fsw(self, op0: F, op1: MemExpr, /) -> None:
        """Emit `fsw` (2 or 3 operands)."""
    @overload
    def fsw(self, op0: F, op1: _Target, op2: X, /) -> None: ...
    def j(self, op0: _Target, /) -> None:
        """Emit `j` (1 operands)."""
    @overload
    def jal(self, op0: _Target, /) -> None:
        """Emit `jal` (1 or 2 operands)."""
    @overload
    def jal(self, op0: X, op1: _Target, /) -> None: ...
    @overload
    def jalr(self, op0: X, /) -> None:
        """Emit `jalr` (1 or 2 or 3 operands)."""
    @overload
    def jalr(self, op0: X, op1: X | _Imm | MemExpr, /) -> None: ...
    @overload
    def jalr(self, op0: X, op1: X, op2: _Imm, /) -> None: ...
    @overload
    def jr(self, op0: X, /) -> None:
        """Emit `jr` (1 or 2 operands)."""
    @overload
    def jr(self, op0: X, op1: _Imm, /) -> None: ...
    def la(self, op0: X, op1: _Target, /) -> None:
        """Emit `la` (2 operands)."""
    def lb(self, op0: X, op1: MemExpr | _Target, /) -> None:
        """Emit `lb` (2 operands)."""
    def lbu(self, op0: X, op1: MemExpr | _Target, /) -> None:
        """Emit `lbu` (2 operands)."""
    def ld(self, op0: X, op1: MemExpr | _Target, /) -> None:
        """Emit `ld` (2 operands)."""
    def lh(self, op0: X, op1: MemExpr | _Target, /) -> None:
        """Emit `lh` (2 operands)."""
    def lhu(self, op0: X, op1: MemExpr | _Target, /) -> None:
        """Emit `lhu` (2 operands)."""
    def li(self, op0: X, op1: _Imm, /) -> None:
        """Emit `li` (2 operands)."""
    def lla(self, op0: X, op1: _Target, /) -> None:
        """Emit `lla` (2 operands)."""
    lr: _lr_method
    def lui(self, op0: X, op1: _Imm, /) -> None:
        """Emit `lui` (2 operands)."""
    def lw(self, op0: X, op1: MemExpr | _Target, /) -> None:
        """Emit `lw` (2 operands)."""
    def lwu(self, op0: X, op1: MemExpr | _Target, /) -> None:
        """Emit `lwu` (2 operands)."""
    def max(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `max` (3 operands)."""
    def max_(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `max` (3 operands)."""
    def maxu(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `maxu` (3 operands)."""
    def min(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `min` (3 operands)."""
    def min_(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `min` (3 operands)."""
    def minu(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `minu` (3 operands)."""
    def mul(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `mul` (3 operands)."""
    def mulh(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `mulh` (3 operands)."""
    def mulhsu(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `mulhsu` (3 operands)."""
    def mulhu(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `mulhu` (3 operands)."""
    def mulw(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `mulw` (3 operands)."""
    def mv(self, op0: X, op1: X, /) -> None:
        """Emit `mv` (2 operands)."""
    def neg(self, op0: X, op1: X, /) -> None:
        """Emit `neg` (2 operands)."""
    def negw(self, op0: X, op1: X, /) -> None:
        """Emit `negw` (2 operands)."""
    def nop(self) -> None:
        """Emit `nop` (0 operands)."""
    def not_(self, op0: X, op1: X, /) -> None:
        """Emit `not` (2 operands)."""
    def or_(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `or` (3 operands)."""
    orc: _orc_method
    def ori(self, op0: X, op1: X, op2: _Imm, /) -> None:
        """Emit `ori` (3 operands)."""
    def orn(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `orn` (3 operands)."""
    def rdcycle(self, op0: X, /) -> None:
        """Emit `rdcycle` (1 operands)."""
    def rdinstret(self, op0: X, /) -> None:
        """Emit `rdinstret` (1 operands)."""
    def rdtime(self, op0: X, /) -> None:
        """Emit `rdtime` (1 operands)."""
    def rem(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `rem` (3 operands)."""
    def remu(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `remu` (3 operands)."""
    def remuw(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `remuw` (3 operands)."""
    def remw(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `remw` (3 operands)."""
    def ret(self) -> None:
        """Emit `ret` (0 operands)."""
    def rev8(self, op0: X, op1: X, /) -> None:
        """Emit `rev8` (2 operands)."""
    def rol(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `rol` (3 operands)."""
    def rolw(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `rolw` (3 operands)."""
    def ror(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `ror` (3 operands)."""
    def rori(self, op0: X, op1: X, op2: _Imm, /) -> None:
        """Emit `rori` (3 operands)."""
    def roriw(self, op0: X, op1: X, op2: _Imm, /) -> None:
        """Emit `roriw` (3 operands)."""
    def rorw(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `rorw` (3 operands)."""
    @overload
    def sb(self, op0: X, op1: MemExpr, /) -> None:
        """Emit `sb` (2 or 3 operands)."""
    @overload
    def sb(self, op0: X, op1: _Target, op2: X, /) -> None: ...
    sc: _sc_method
    @overload
    def sd(self, op0: X, op1: MemExpr, /) -> None:
        """Emit `sd` (2 or 3 operands)."""
    @overload
    def sd(self, op0: X, op1: _Target, op2: X, /) -> None: ...
    def seqz(self, op0: X, op1: X, /) -> None:
        """Emit `seqz` (2 operands)."""
    sext: _sext_method
    def sgt(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `sgt` (3 operands)."""
    def sgtu(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `sgtu` (3 operands)."""
    def sgtz(self, op0: X, op1: X, /) -> None:
        """Emit `sgtz` (2 operands)."""
    @overload
    def sh(self, op0: X, op1: MemExpr, /) -> None:
        """Emit `sh` (2 or 3 operands)."""
    @overload
    def sh(self, op0: X, op1: _Target, op2: X, /) -> None: ...
    sh1add: _sh1add_method
    sh2add: _sh2add_method
    sh3add: _sh3add_method
    def sll(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `sll` (3 operands)."""
    slli: _slli_method
    def slliw(self, op0: X, op1: X, op2: _Imm, /) -> None:
        """Emit `slliw` (3 operands)."""
    def sllw(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `sllw` (3 operands)."""
    def slt(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `slt` (3 operands)."""
    def slti(self, op0: X, op1: X, op2: _Imm, /) -> None:
        """Emit `slti` (3 operands)."""
    def sltiu(self, op0: X, op1: X, op2: _Imm, /) -> None:
        """Emit `sltiu` (3 operands)."""
    def sltu(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `sltu` (3 operands)."""
    def sltz(self, op0: X, op1: X, /) -> None:
        """Emit `sltz` (2 operands)."""
    def snez(self, op0: X, op1: X, /) -> None:
        """Emit `snez` (2 operands)."""
    def sra(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `sra` (3 operands)."""
    def srai(self, op0: X, op1: X, op2: _Imm, /) -> None:
        """Emit `srai` (3 operands)."""
    def sraiw(self, op0: X, op1: X, op2: _Imm, /) -> None:
        """Emit `sraiw` (3 operands)."""
    def sraw(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `sraw` (3 operands)."""
    def srl(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `srl` (3 operands)."""
    def srli(self, op0: X, op1: X, op2: _Imm, /) -> None:
        """Emit `srli` (3 operands)."""
    def srliw(self, op0: X, op1: X, op2: _Imm, /) -> None:
        """Emit `srliw` (3 operands)."""
    def srlw(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `srlw` (3 operands)."""
    def sub(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `sub` (3 operands)."""
    def subw(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `subw` (3 operands)."""
    @overload
    def sw(self, op0: X, op1: MemExpr, /) -> None:
        """Emit `sw` (2 or 3 operands)."""
    @overload
    def sw(self, op0: X, op1: _Target, op2: X, /) -> None: ...
    def tail(self, op0: _Target, /) -> None:
        """Emit `tail` (1 operands)."""
    def unimp(self) -> None:
        """Emit `unimp` (0 operands)."""
    def xnor(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `xnor` (3 operands)."""
    def xor(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `xor` (3 operands)."""
    def xori(self, op0: X, op1: X, op2: _Imm, /) -> None:
        """Emit `xori` (3 operands)."""
    zext: _zext_method

add: _add
def addi(op0: X, op1: X, op2: _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `addi` (3 operands)."""
def addiw(op0: X, op1: X, op2: _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `addiw` (3 operands)."""
def addw(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `addw` (3 operands)."""
amoadd: _amoadd
amoand: _amoand
amomax: _amomax
amomaxu: _amomaxu
amomin: _amomin
amominu: _amominu
amoor: _amoor
amoswap: _amoswap
amoxor: _amoxor
def and_(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `and` (3 operands)."""
def andi(op0: X, op1: X, op2: _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `andi` (3 operands)."""
def andn(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `andn` (3 operands)."""
def auipc(op0: X, op1: _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `auipc` (2 operands)."""
def beq(op0: X, op1: X, op2: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `beq` (3 operands)."""
def beqz(op0: X, op1: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `beqz` (2 operands)."""
def bge(op0: X, op1: X, op2: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `bge` (3 operands)."""
def bgeu(op0: X, op1: X, op2: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `bgeu` (3 operands)."""
def bgez(op0: X, op1: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `bgez` (2 operands)."""
def bgt(op0: X, op1: X, op2: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `bgt` (3 operands)."""
def bgtu(op0: X, op1: X, op2: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `bgtu` (3 operands)."""
def bgtz(op0: X, op1: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `bgtz` (2 operands)."""
def ble(op0: X, op1: X, op2: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `ble` (3 operands)."""
def bleu(op0: X, op1: X, op2: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `bleu` (3 operands)."""
def blez(op0: X, op1: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `blez` (2 operands)."""
def blt(op0: X, op1: X, op2: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `blt` (3 operands)."""
def bltu(op0: X, op1: X, op2: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `bltu` (3 operands)."""
def bltz(op0: X, op1: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `bltz` (2 operands)."""
def bne(op0: X, op1: X, op2: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `bne` (3 operands)."""
def bnez(op0: X, op1: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `bnez` (2 operands)."""
def call(op0: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `call` (1 operands)."""
def clz(op0: X, op1: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `clz` (2 operands)."""
def clzw(op0: X, op1: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `clzw` (2 operands)."""
def cpop(op0: X, op1: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `cpop` (2 operands)."""
def cpopw(op0: X, op1: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `cpopw` (2 operands)."""
def csrc(op0: _Imm | CsrName, op1: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `csrc` (2 operands)."""
def csrci(op0: _Imm | CsrName, op1: _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `csrci` (2 operands)."""
def csrr(op0: X, op1: _Imm | CsrName, /, *, asm: Assembler | None = None) -> None:
    """Emit `csrr` (2 operands)."""
def csrrc(op0: X, op1: _Imm | CsrName, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `csrrc` (3 operands)."""
def csrrci(op0: X, op1: _Imm | CsrName, op2: _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `csrrci` (3 operands)."""
def csrrs(op0: X, op1: _Imm | CsrName, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `csrrs` (3 operands)."""
def csrrsi(op0: X, op1: _Imm | CsrName, op2: _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `csrrsi` (3 operands)."""
def csrrw(op0: X, op1: _Imm | CsrName, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `csrrw` (3 operands)."""
def csrrwi(op0: X, op1: _Imm | CsrName, op2: _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `csrrwi` (3 operands)."""
def csrs(op0: _Imm | CsrName, op1: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `csrs` (2 operands)."""
def csrsi(op0: _Imm | CsrName, op1: _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `csrsi` (2 operands)."""
def csrw(op0: _Imm | CsrName, op1: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `csrw` (2 operands)."""
def csrwi(op0: _Imm | CsrName, op1: _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `csrwi` (2 operands)."""
def ctz(op0: X, op1: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `ctz` (2 operands)."""
def ctzw(op0: X, op1: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `ctzw` (2 operands)."""
def div(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `div` (3 operands)."""
def divu(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `divu` (3 operands)."""
def divuw(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `divuw` (3 operands)."""
def divw(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `divw` (3 operands)."""
def ebreak(*, asm: Assembler | None = None) -> None:
    """Emit `ebreak` (0 operands)."""
def ecall(*, asm: Assembler | None = None) -> None:
    """Emit `ecall` (0 operands)."""
fabs: _fabs
fadd: _fadd
fclass: _fclass
fcvt: _fcvt
fdiv: _fdiv
fence: _fence
feq: _feq
fge: _fge
fgt: _fgt
@overload
def fld(op0: F, op1: MemExpr, /, *, asm: Assembler | None = None) -> None:
    """Emit `fld` (2 or 3 operands)."""
@overload
def fld(op0: F, op1: _Target, op2: X, /, *, asm: Assembler | None = None) -> None: ...
fle: _fle
flt: _flt
@overload
def flw(op0: F, op1: MemExpr, /, *, asm: Assembler | None = None) -> None:
    """Emit `flw` (2 or 3 operands)."""
@overload
def flw(op0: F, op1: _Target, op2: X, /, *, asm: Assembler | None = None) -> None: ...
fmadd: _fmadd
fmax: _fmax
fmin: _fmin
fmsub: _fmsub
fmul: _fmul
fmv: _fmv
fneg: _fneg
fnmadd: _fnmadd
fnmsub: _fnmsub
def frcsr(op0: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `frcsr` (1 operands)."""
def frflags(op0: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `frflags` (1 operands)."""
def frrm(op0: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `frrm` (1 operands)."""
@overload
def fscsr(op0: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `fscsr` (1 or 2 operands)."""
@overload
def fscsr(op0: X, op1: X, /, *, asm: Assembler | None = None) -> None: ...
@overload
def fsd(op0: F, op1: MemExpr, /, *, asm: Assembler | None = None) -> None:
    """Emit `fsd` (2 or 3 operands)."""
@overload
def fsd(op0: F, op1: _Target, op2: X, /, *, asm: Assembler | None = None) -> None: ...
@overload
def fsflags(op0: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `fsflags` (1 or 2 operands)."""
@overload
def fsflags(op0: X, op1: X, /, *, asm: Assembler | None = None) -> None: ...
@overload
def fsflagsi(op0: _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `fsflagsi` (1 or 2 operands)."""
@overload
def fsflagsi(op0: X, op1: _Imm, /, *, asm: Assembler | None = None) -> None: ...
fsgnj: _fsgnj
fsgnjn: _fsgnjn
fsgnjx: _fsgnjx
fsqrt: _fsqrt
@overload
def fsrm(op0: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `fsrm` (1 or 2 operands)."""
@overload
def fsrm(op0: X, op1: X, /, *, asm: Assembler | None = None) -> None: ...
@overload
def fsrmi(op0: _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `fsrmi` (1 or 2 operands)."""
@overload
def fsrmi(op0: X, op1: _Imm, /, *, asm: Assembler | None = None) -> None: ...
fsub: _fsub
@overload
def fsw(op0: F, op1: MemExpr, /, *, asm: Assembler | None = None) -> None:
    """Emit `fsw` (2 or 3 operands)."""
@overload
def fsw(op0: F, op1: _Target, op2: X, /, *, asm: Assembler | None = None) -> None: ...
def j(op0: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `j` (1 operands)."""
@overload
def jal(op0: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `jal` (1 or 2 operands)."""
@overload
def jal(op0: X, op1: _Target, /, *, asm: Assembler | None = None) -> None: ...
@overload
def jalr(op0: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `jalr` (1 or 2 or 3 operands)."""
@overload
def jalr(op0: X, op1: X | _Imm | MemExpr, /, *, asm: Assembler | None = None) -> None: ...
@overload
def jalr(op0: X, op1: X, op2: _Imm, /, *, asm: Assembler | None = None) -> None: ...
@overload
def jr(op0: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `jr` (1 or 2 operands)."""
@overload
def jr(op0: X, op1: _Imm, /, *, asm: Assembler | None = None) -> None: ...
def la(op0: X, op1: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `la` (2 operands)."""
def lb(op0: X, op1: MemExpr | _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `lb` (2 operands)."""
def lbu(op0: X, op1: MemExpr | _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `lbu` (2 operands)."""
def ld(op0: X, op1: MemExpr | _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `ld` (2 operands)."""
def lh(op0: X, op1: MemExpr | _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `lh` (2 operands)."""
def lhu(op0: X, op1: MemExpr | _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `lhu` (2 operands)."""
def li(op0: X, op1: _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `li` (2 operands)."""
def lla(op0: X, op1: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `lla` (2 operands)."""
lr: _lr
def lui(op0: X, op1: _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `lui` (2 operands)."""
def lw(op0: X, op1: MemExpr | _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `lw` (2 operands)."""
def lwu(op0: X, op1: MemExpr | _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `lwu` (2 operands)."""
def max_(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `max` (3 operands)."""
def maxu(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `maxu` (3 operands)."""
def min_(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `min` (3 operands)."""
def minu(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `minu` (3 operands)."""
def mul(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `mul` (3 operands)."""
def mulh(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `mulh` (3 operands)."""
def mulhsu(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `mulhsu` (3 operands)."""
def mulhu(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `mulhu` (3 operands)."""
def mulw(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `mulw` (3 operands)."""
def mv(op0: X, op1: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `mv` (2 operands)."""
def neg(op0: X, op1: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `neg` (2 operands)."""
def negw(op0: X, op1: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `negw` (2 operands)."""
def nop(*, asm: Assembler | None = None) -> None:
    """Emit `nop` (0 operands)."""
def not_(op0: X, op1: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `not` (2 operands)."""
def or_(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `or` (3 operands)."""
orc: _orc
def ori(op0: X, op1: X, op2: _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `ori` (3 operands)."""
def orn(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `orn` (3 operands)."""
def rdcycle(op0: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `rdcycle` (1 operands)."""
def rdinstret(op0: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `rdinstret` (1 operands)."""
def rdtime(op0: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `rdtime` (1 operands)."""
def rem(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `rem` (3 operands)."""
def remu(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `remu` (3 operands)."""
def remuw(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `remuw` (3 operands)."""
def remw(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `remw` (3 operands)."""
def ret(*, asm: Assembler | None = None) -> None:
    """Emit `ret` (0 operands)."""
def rev8(op0: X, op1: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `rev8` (2 operands)."""
def rol(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `rol` (3 operands)."""
def rolw(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `rolw` (3 operands)."""
def ror(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `ror` (3 operands)."""
def rori(op0: X, op1: X, op2: _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `rori` (3 operands)."""
def roriw(op0: X, op1: X, op2: _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `roriw` (3 operands)."""
def rorw(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `rorw` (3 operands)."""
@overload
def sb(op0: X, op1: MemExpr, /, *, asm: Assembler | None = None) -> None:
    """Emit `sb` (2 or 3 operands)."""
@overload
def sb(op0: X, op1: _Target, op2: X, /, *, asm: Assembler | None = None) -> None: ...
sc: _sc
@overload
def sd(op0: X, op1: MemExpr, /, *, asm: Assembler | None = None) -> None:
    """Emit `sd` (2 or 3 operands)."""
@overload
def sd(op0: X, op1: _Target, op2: X, /, *, asm: Assembler | None = None) -> None: ...
def seqz(op0: X, op1: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `seqz` (2 operands)."""
sext: _sext
def sgt(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `sgt` (3 operands)."""
def sgtu(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `sgtu` (3 operands)."""
def sgtz(op0: X, op1: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `sgtz` (2 operands)."""
@overload
def sh(op0: X, op1: MemExpr, /, *, asm: Assembler | None = None) -> None:
    """Emit `sh` (2 or 3 operands)."""
@overload
def sh(op0: X, op1: _Target, op2: X, /, *, asm: Assembler | None = None) -> None: ...
sh1add: _sh1add
sh2add: _sh2add
sh3add: _sh3add
def sll(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `sll` (3 operands)."""
slli: _slli
def slliw(op0: X, op1: X, op2: _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `slliw` (3 operands)."""
def sllw(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `sllw` (3 operands)."""
def slt(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `slt` (3 operands)."""
def slti(op0: X, op1: X, op2: _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `slti` (3 operands)."""
def sltiu(op0: X, op1: X, op2: _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `sltiu` (3 operands)."""
def sltu(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `sltu` (3 operands)."""
def sltz(op0: X, op1: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `sltz` (2 operands)."""
def snez(op0: X, op1: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `snez` (2 operands)."""
def sra(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `sra` (3 operands)."""
def srai(op0: X, op1: X, op2: _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `srai` (3 operands)."""
def sraiw(op0: X, op1: X, op2: _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `sraiw` (3 operands)."""
def sraw(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `sraw` (3 operands)."""
def srl(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `srl` (3 operands)."""
def srli(op0: X, op1: X, op2: _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `srli` (3 operands)."""
def srliw(op0: X, op1: X, op2: _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `srliw` (3 operands)."""
def srlw(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `srlw` (3 operands)."""
def sub(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `sub` (3 operands)."""
def subw(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `subw` (3 operands)."""
@overload
def sw(op0: X, op1: MemExpr, /, *, asm: Assembler | None = None) -> None:
    """Emit `sw` (2 or 3 operands)."""
@overload
def sw(op0: X, op1: _Target, op2: X, /, *, asm: Assembler | None = None) -> None: ...
def tail(op0: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `tail` (1 operands)."""
def unimp(*, asm: Assembler | None = None) -> None:
    """Emit `unimp` (0 operands)."""
def xnor(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `xnor` (3 operands)."""
def xor(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `xor` (3 operands)."""
def xori(op0: X, op1: X, op2: _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `xori` (3 operands)."""
zext: _zext

__all__ = [
    "add",
    "addi",
    "addiw",
    "addw",
    "amoadd",
    "amoand",
    "amomax",
    "amomaxu",
    "amomin",
    "amominu",
    "amoor",
    "amoswap",
    "amoxor",
    "and_",
    "andi",
    "andn",
    "auipc",
    "beq",
    "beqz",
    "bge",
    "bgeu",
    "bgez",
    "bgt",
    "bgtu",
    "bgtz",
    "ble",
    "bleu",
    "blez",
    "blt",
    "bltu",
    "bltz",
    "bne",
    "bnez",
    "call",
    "clz",
    "clzw",
    "cpop",
    "cpopw",
    "csrc",
    "csrci",
    "csrr",
    "csrrc",
    "csrrci",
    "csrrs",
    "csrrsi",
    "csrrw",
    "csrrwi",
    "csrs",
    "csrsi",
    "csrw",
    "csrwi",
    "ctz",
    "ctzw",
    "div",
    "divu",
    "divuw",
    "divw",
    "ebreak",
    "ecall",
    "fabs",
    "fadd",
    "fclass",
    "fcvt",
    "fdiv",
    "fence",
    "feq",
    "fge",
    "fgt",
    "fld",
    "fle",
    "flt",
    "flw",
    "fmadd",
    "fmax",
    "fmin",
    "fmsub",
    "fmul",
    "fmv",
    "fneg",
    "fnmadd",
    "fnmsub",
    "frcsr",
    "frflags",
    "frrm",
    "fscsr",
    "fsd",
    "fsflags",
    "fsflagsi",
    "fsgnj",
    "fsgnjn",
    "fsgnjx",
    "fsqrt",
    "fsrm",
    "fsrmi",
    "fsub",
    "fsw",
    "j",
    "jal",
    "jalr",
    "jr",
    "la",
    "lb",
    "lbu",
    "ld",
    "lh",
    "lhu",
    "li",
    "lla",
    "lr",
    "lui",
    "lw",
    "lwu",
    "max_",
    "maxu",
    "min_",
    "minu",
    "mul",
    "mulh",
    "mulhsu",
    "mulhu",
    "mulw",
    "mv",
    "neg",
    "negw",
    "nop",
    "not_",
    "or_",
    "orc",
    "ori",
    "orn",
    "rdcycle",
    "rdinstret",
    "rdtime",
    "rem",
    "remu",
    "remuw",
    "remw",
    "ret",
    "rev8",
    "rol",
    "rolw",
    "ror",
    "rori",
    "roriw",
    "rorw",
    "sb",
    "sc",
    "sd",
    "seqz",
    "sext",
    "sgt",
    "sgtu",
    "sgtz",
    "sh",
    "sh1add",
    "sh2add",
    "sh3add",
    "sll",
    "slli",
    "slliw",
    "sllw",
    "slt",
    "slti",
    "sltiu",
    "sltu",
    "sltz",
    "snez",
    "sra",
    "srai",
    "sraiw",
    "sraw",
    "srl",
    "srli",
    "srliw",
    "srlw",
    "sub",
    "subw",
    "sw",
    "tail",
    "unimp",
    "xnor",
    "xor",
    "xori",
    "zext",
]
