"""Generate the type stubs of the jita architecture packages.

    uv run python tools/gen_stubs.py            write the stubs
    uv run python tools/gen_stubs.py --check    exit 1 if a stub is stale

The mnemonic functions are created at import time from the DynASM
template tables, so a type checker cannot see them. This script writes
`insns.pyi` and `__init__.pyi` for `jita.x64`, `jita.aarch64`,
`jita.riscv64` and `jita.loongarch64`, with one `@overload` per accepted
combination of operand classes (register width classes, sized memory
classes, immediates, labels, ...).

The real encoder decides what is accepted. For every mnemonic and arity
the script tries each tuple of operand classes with a few representative
operands per class, and a tuple becomes part of the stub if any
combination of representatives encodes. Tuples that differ in one
position are then merged into unions. So the stubs accept only what the
encoder accepts for some operands of those classes; value checks
(immediate ranges, specific registers) stay runtime errors.

`tests/test_typing.py` checks that the checked-in stubs match a fresh
generation and runs pyright and mypy over a corpus built from the same
accepted tuples (`corpus`).
"""

import argparse
import functools
import itertools
import sys
from collections.abc import Callable, Iterable, Sequence
from contextlib import AbstractContextManager, nullcontext
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from jita.aarch64 import encoder as a64_encoder  # noqa: E402
from jita.aarch64 import insns as a64_insns  # noqa: E402
from jita.aarch64 import regs as a64_regs  # noqa: E402
from jita.aarch64.mem import mem  # noqa: E402
from jita.aarch64.table import MAP_ALIAS as A64_ALIAS  # noqa: E402
from jita.aarch64.table import MAP_COND as A64_COND  # noqa: E402
from jita.aarch64.table import MAP_OP as A64_OP  # noqa: E402
from jita.core.errors import EncodeError  # noqa: E402
from jita.core.labels import Label  # noqa: E402
from jita.loongarch64 import encoder as la_encoder  # noqa: E402
from jita.loongarch64 import insns as la_insns  # noqa: E402
from jita.loongarch64 import regs as la_regs  # noqa: E402
from jita.loongarch64.table import MAP_OP as LA_OP  # noqa: E402
from jita.riscv64 import encoder as rv_encoder  # noqa: E402
from jita.riscv64 import insns as rv_insns  # noqa: E402
from jita.riscv64 import regs as rv_regs  # noqa: E402
from jita.riscv64.mem import mem as rv_mem  # noqa: E402
from jita.riscv64.table import MAP_OP as RV_OP  # noqa: E402
from jita.x64 import encoder as x64_encoder  # noqa: E402
from jita.x64 import insns as x64_insns  # noqa: E402
from jita.x64 import mem as x64_mem  # noqa: E402
from jita.x64 import regs as x64_regs  # noqa: E402
from jita.x64.table import MAP_OP as X64_OP  # noqa: E402

# A signature: per operand position, the set of accepted class names.
type Sig = tuple[frozenset[str], ...]
# A point: one class name per operand position.
type Point = tuple[str, ...]

HEADER = "# Generated by tools/gen_stubs.py from the encoder tables. Do not edit.\n"


class _Sink:
    """Stands in for an Assembler: the encoders emit into it and it keeps
    nothing, so the oracle is cheap."""

    def pos(self) -> int:
        return 0

    def emit(self, data: object) -> None:
        pass

    def emit_patch(self, kind: object, target: object, addend: int = 0) -> None:
        pass

    def add_patch(self, offset: int, kind: object, target: object, addend: int = 0) -> None:
        pass

    def note_insn(self, start: int, mnemonic: str, ops: tuple[object, ...] = ()) -> None:
        pass

    def named(self, name: str) -> Label:
        return Label(name)

    def _forget_names_on_error(self) -> AbstractContextManager[None]:
        return nullcontext()


_SINK = _Sink()


# -- merging -----------------------------------------------------------------


def merge(points: Iterable[Point]) -> list[Sig]:
    """Merge points into signatures (a partition of the points): points
    that differ in one position become one signature with a union there,
    repeatedly, position by position."""
    cur: list[Sig] = [tuple(frozenset([c]) for c in p) for p in sorted(set(points))]
    if not cur or not cur[0]:
        return cur
    changed = True
    while changed:
        changed = False
        for k in range(len(cur[0])):
            groups: dict[Sig, set[str]] = {}
            for t in cur:
                groups.setdefault(t[:k] + t[k + 1 :], set()).update(t[k])
            new = [key[:k] + (frozenset(v),) + key[k:] for key, v in groups.items()]
            if len(new) < len(cur):
                cur, changed = new, True
    return cur


def _accepts(encode: Callable[[Sequence[object]], object], reps: Sequence[Sequence[object]]) -> bool:
    for ops in itertools.product(*reps):
        try:
            encode(ops)
        except (EncodeError, TypeError):
            continue
        return True
    return False


# -- x64 -----------------------------------------------------------------------

X64_CLASSES = [
    "Gp8", "Gp16", "Gp32", "Gp64", "Xmm", "Ymm", "St",
    "Mem8", "Mem16", "Mem32", "Mem64", "Mem80", "Mem128", "Mem256", "MemAny",
    "int", "Target",
]  # fmt: skip


def _x64_reps() -> dict[str, list[Any]]:
    r, m = x64_regs, x64_mem

    def sized(prefix: Any) -> list[Any]:
        return [prefix[r.rbx], prefix[0x1000]]

    return {
        # al (mode R), cl (C), sil and r9b (REX), ah (high).
        "Gp8": [r.al, r.cl, r.bl, r.sil, r.r9b, r.ah],
        "Gp16": [r.ax, r.bx, r.r9w],
        "Gp32": [r.eax, r.ebx, r.r9d],
        "Gp64": [r.rax, r.rbx, r.r9],
        "Xmm": [r.xmm0, r.xmm1, r.xmm9],
        "Ymm": [r.ymm0, r.ymm1, r.ymm9],
        "St": [r.st0, r.st1],
        "Mem8": sized(m.byte),
        "Mem16": sized(m.word),
        "Mem32": sized(m.dword),
        "Mem64": sized(m.qword),
        "Mem80": sized(m.tword),
        "Mem128": sized(m.oword),
        "Mem256": sized(m.yword),
        "MemAny": sized(m.ptr),
        "int": [0, 1, 3, 127, 200, 0x1234, 0x12345678, -1, 1 << 40],
        # str and Extern classify like a Label.
        "Target": [Label("target")],
    }


X64_REPS = _x64_reps()

# Mnemonics that `encode` special-cases before template matching.
X64_SPECIAL = frozenset(["mov", "xchg", "mov64", "movabs"])


def _x64_modes() -> dict[str, list[str]]:
    return {c: [x64_encoder._classify(op, "", ()).mode for op in reps] for c, reps in X64_REPS.items()}


def _x64_opsizes() -> dict[str, str | None]:
    out: dict[str, str | None] = {}
    for c, reps in X64_REPS.items():
        sizes = {x64_encoder._classify(op, "", ()).opsize for op in reps}
        assert len(sizes) == 1, (c, sizes)
        out[c] = sizes.pop()
    return out


def _x64_matches(template: str, point: Point, modes: dict[str, list[str]], opsize: dict[str, str | None]) -> bool:
    """The template matching of `encoder._encode_template` at the class
    level: can some alternative match the modes and sizes of some
    representatives? A necessary condition for encoding, and cheap, so
    the oracle only runs on tuples that pass it. The operand size of a
    class does not depend on the representative, and a letter check that
    passes for some representative only makes this more permissive."""
    n = len(point)
    sz: str | None = None
    szmix = False
    for c in point:
        nsz = opsize[c]
        if nsz is not None:
            if sz is not None and sz != nsz:
                szmix = True
            else:
                sz = nsz
    for tm in template.split("|"):
        if not tm:
            continue
        if not all(tm[i] == "." or any(tm[i] in md for md in modes[c]) for i, c in enumerate(point)):
            continue
        szm = tm[n : tm.index(":", n)]
        prefix = szm[:1]
        if prefix == "/":
            if all(opsize[point[j - 1]] == szm[j] for j in range(1, len(szm))):
                return True
            continue
        szp = sz
        if szm == "":
            szm = "qdwb"
        if prefix == "1":
            szp = opsize[point[0]]
            szmix = False
        elif prefix == "2":
            szp = opsize[point[1]]
            szmix = False
        if not szmix and (prefix == "." or (szp is not None and szp in szm)):
            return True
    return False


def _x64_viable(template: str, n: int, modes: dict[str, list[str]], opsize: dict[str, str | None]) -> list[Point]:
    """Class tuples worth asking the encoder about for `template`."""
    per_pos: list[set[str]] = [set() for _ in range(n)]
    for tm in template.split("|"):
        if not tm:
            continue
        for i in range(n):
            ch = tm[i]
            per_pos[i].update(c for c in X64_CLASSES if ch == "." or any(ch in md for md in modes[c]))
    ordered = [sorted(p, key=X64_CLASSES.index) for p in per_pos]
    return [p for p in itertools.product(*ordered) if _x64_matches(template, p, modes, opsize)]


class X64Result:
    """Accepted points per Python name: `sigs[py][n]` for the call, and
    `short[py]` for `.short` on the rel8 branches."""

    def __init__(self) -> None:
        self.points: dict[str, dict[int, list[Point]]] = {}
        self.short: dict[str, list[Point]] = {}


@functools.cache
def x64_oracle(filtered: bool = True, max_arity: int | None = None) -> X64Result:
    """Accepted points for every x64 mnemonic. `filtered=False` skips the
    class level prefilter and asks the encoder about every class tuple
    (slow; the tests use it with `max_arity` to check the prefilter).
    `max_arity` leaves out forms with more operands."""
    modes, opsize = _x64_modes(), _x64_opsizes()

    def viable(template: str, n: int) -> Iterable[Point]:
        if filtered:
            return _x64_viable(template, n, modes, opsize)
        return itertools.product(X64_CLASSES, repeat=n)

    res = X64Result()
    memo: dict[tuple[str, int], list[Point]] = {}
    short_memo: dict[str, list[Point]] = {}
    keys: dict[str, list[int]] = {}
    for key in X64_OP:
        mn, _, n = key.rpartition("_")
        keys.setdefault(mn, []).append(int(n))
    keys["mov64"] = keys["movabs"] = [2]

    def run(mn: str, n: int, candidates: Iterable[Point], short: bool = False) -> list[Point]:
        def enc(ops: Sequence[object]) -> None:
            x64_encoder.encode(_SINK, mn, ops, short)

        return sorted(p for p in candidates if _accepts(enc, [X64_REPS[c] for c in p]))

    for mn in sorted(keys):
        py = x64_insns.PY_NAMES.get(mn, mn)
        per_n: dict[int, list[Point]] = {}
        for n in sorted(keys[mn]):
            if max_arity is not None and n > max_arity:
                continue
            if n == 0:
                per_n[0] = [()]
                continue
            if mn in X64_SPECIAL:
                per_n[n] = run(mn, n, itertools.product(X64_CLASSES, repeat=n))
                continue
            template = X64_OP[f"{mn}_{n}"]
            hit = memo.get((template, n))
            if hit is None:
                hit = memo[(template, n)] = run(mn, n, viable(template, n))
            per_n[n] = hit
        res.points[py] = per_n
        if mn in x64_insns.SHORT_BRANCHES:
            template = X64_OP[f"{mn}_1"]
            hit = short_memo.get(template)
            if hit is None:
                hit = short_memo[template] = run(mn, 1, viable(template, 1), short=True)
            res.short[py] = hit
    return res


# -- aarch64 -------------------------------------------------------------------

A64_CLASSES = [
    "X", "W", "Sp", "S", "D", "Q", "RegModX", "RegModW", "Mod",
    "int", "float", "Mem", "Target", "Cond", "Bti",
]  # fmt: skip


def _a64_reps() -> dict[str, list[Any]]:
    r = a64_regs
    Mod = r.Mod
    return {
        # Two different registers per class: ldp rejects loading one twice.
        "X": [r.x1, r.x2, r.xzr],
        "W": [r.w1, r.w2, r.wzr],
        "Sp": [r.sp],
        "S": [r.s1, r.s2],
        "D": [r.d1, r.d2],
        "Q": [r.q1, r.q2],
        "RegModX": [r.x5 << 3, r.x5.lsl(0), r.x5.sxtx(), r.x5.asr(2), r.x5.uxtx(2), r.x5 >> 2],
        "RegModW": [r.w5.uxtw(), r.w5.sxtw(2), r.w5 << 3, r.w5.uxtb()],
        "Mod": [Mod("lsl", 16), Mod("lsl", 0), Mod("lsl", 3), Mod("uxtw", None), Mod("sxtx", 2), Mod("asr", 2)],
        "int": [0, 1, 3, 8, 16, 63, 0xFF, 0xFFFF, 0x1000, 0xFF00, 0xFFFF0000, -1],
        "float": [1.5, 0.0],
        # x3 and x4 as base and index do not overlap the transfer registers.
        "Mem": [
            mem[r.x3],
            mem[r.x3 + 8],
            mem.pre[r.x3 + 16],
            mem.post[r.x3, 8],
            mem[r.x3 + (r.x4 << 3)],
            mem[r.x3 + r.w4.uxtw()],
            mem[r.sp],
        ],
        "Target": [Label("target")],
        "Cond": ["eq", "al"],
        "Bti": ["c"],
    }


A64_REPS = _a64_reps()

_A64_REG = ["X", "W", "Sp", "S", "D", "Q"]
_A64_LETTER: dict[str, list[str]] = {
    "D": _A64_REG, "N": _A64_REG, "M": _A64_REG, "A": _A64_REG,
    "L": ["Mem"], "P": ["Mem"], "B": ["Target"],
    "I": ["int"], "i": ["int"], "W": ["int"], "T": ["int"], "1": ["int"], "2": ["int"],
    "5": ["int"], "V": ["int"], "F": ["float", "int"], "Z": ["float", "int"],
    "S": ["Mod"], "X": ["Mod"], "R": ["Mod"], "C": ["Cond"], "c": ["Cond"], "t": ["Bti"],
}  # fmt: skip


def _a64_positions(mn: str) -> dict[int, list[set[str]]]:
    """Python arity -> candidate classes per position, from the template
    letters, both with the modifier as its own operand and merged into
    the register before it (`x2 << 3`)."""
    pos: dict[int, list[set[str]]] = {}

    def add(letters: list[str]) -> None:
        cur = pos.setdefault(len(letters), [set() for _ in letters])
        for i, ch in enumerate(letters):
            cur[i] |= set(_A64_LETTER[ch])
            if ch in "DNMA":
                cur[i] |= {"RegModX", "RegModW"}

    for key, tpl in A64_OP.items():
        if key.rpartition("_")[0] != mn:
            continue
        for alt in tpl.split("|"):
            letters = [ch for ch in alt[8:] if ch in _A64_LETTER]
            add(letters)
            add([ch for ch in letters if ch not in "SX"])
    for key in A64_ALIAS:
        name, _, n = key.rpartition("_")
        if name == mn:
            add(["D", "N"] + ["I"] * (int(n) - 2))
    return pos


_A64_RT = {"X": "x", "W": "w", "Sp": "x", "S": "s", "D": "d", "Q": "q"}


def _a64_alt_ok(t: str, params: list[str]) -> bool:
    """`encoder._parse_template` at the class level: the operand kinds and
    register types of one alternative, without the value checks. A
    necessary condition for encoding."""
    n = 0
    rtype: str | None = None
    sp_ok: set[int] = set()

    def reg(i: int) -> bool:
        nonlocal rtype
        if i >= len(params) or params[i] not in _A64_RT:
            return False
        if params[i] == "Sp" and i not in sp_ok:
            return False
        rt = _A64_RT[params[i]]
        if not rtype:
            rtype = rt
        return rtype == rt

    def value(kinds: tuple[str, ...]) -> bool:
        return n < len(params) and params[n] in kinds

    for p in t[8:]:
        if p in "DNMA":
            if not reg(n):
                return False
            n += 1
        elif p == "m":
            if not reg(n - 1):
                return False
        elif p == "p":
            sp_ok.add(n)
        elif p == "g" or p == "f":
            if rtype not in (("x", "w") if p == "g" else ("d", "s")):
                return False
            rtype = None
        elif p in "xwdsq":
            if rtype != p:
                return False
            rtype = None
        elif p in "LP":
            if not value(("Mem",)) or n + 1 < len(params) or (rtype and rtype != "x"):
                return False
            rtype = None
            n = len(params)
        else:
            kinds = {
                "B": ("Target",), "F": ("int", "float"), "Z": ("int", "float"),
                "S": ("Mod",), "X": ("Mod",), "R": ("Mod",), "C": ("Cond",), "c": ("Cond",),
                "t": ("Bti",),
            }.get(p, ("int",))  # fmt: skip
            if not value(kinds):
                return False
            n += 1
    return n >= len(params) and rtype in (None, "x", "w")


def _a64_matches(mn: str, point: Point) -> bool:
    """Class level version of `encoder.encode`: flatten RegMod into a
    register and a Mod, apply the aliases, try the alternatives."""
    params: list[str] = []
    for c in point:
        if c == "RegModX":
            params += ["X", "Mod"]
        elif c == "RegModW":
            params += ["W", "Mod"]
        else:
            params.append(c)
    key = f"{mn}_{len(params)}"
    alias = A64_ALIAS.get(key)
    if alias is not None and (key != "lsl_3" or params[2] == "int"):
        if params[0] not in _A64_RT or any(c != "int" for c in params[2:]):
            return False
        key = alias[0]
        if alias[1] == "lsl":
            params = [*params, "int"]
    template = A64_OP.get(key) or A64_OP.get(f"{mn}_*")
    return template is not None and any(_a64_alt_ok(t, params) for t in template.split("|"))


class A64Result:
    """Accepted points per Python name and arity, and per condition for
    `b.<cond>`."""

    def __init__(self) -> None:
        self.points: dict[str, dict[int, list[Point]]] = {}
        self.cond: dict[str, list[Point]] = {}


@functools.cache
def a64_oracle(filtered: bool = True, max_arity: int | None = None) -> A64Result:
    """Accepted points for every aarch64 mnemonic; `filtered` and
    `max_arity` as for `x64_oracle`. Unfiltered, every class is tried in
    every position of the arities the templates allow."""
    res = A64Result()
    names = sorted({k.rpartition("_")[0] for k in (*A64_OP, *A64_ALIAS)})
    for mn in names:
        py = a64_insns.PY_NAMES.get(mn, mn)

        def enc(ops: Sequence[object], mn: str = mn) -> None:
            a64_encoder.encode(_SINK, mn, ops)

        per_n: dict[int, list[Point]] = {}
        for n, sets in sorted(_a64_positions(mn).items()):
            if max_arity is not None and n > max_arity:
                continue
            if n == 0:
                per_n[0] = [()]
                continue
            if not filtered:
                viable: Iterable[Point] = itertools.product(A64_CLASSES, repeat=n)
            else:
                combos = itertools.product(*(sorted(s, key=A64_CLASSES.index) for s in sets))
                viable = [p for p in combos if _a64_matches(mn, p)]
            per_n[n] = sorted(p for p in viable if _accepts(enc, [A64_REPS[c] for c in p]))
        res.points[py] = per_n
    for cond in A64_COND:
        res.cond[cond] = res.points["b" + cond][1]
    return res


# -- riscv64 -------------------------------------------------------------------

RV_CLASSES = ["X", "F", "int", "Mem", "Target", "Csr", "Fence"]


def _rv_reps() -> dict[str, list[Any]]:
    r = rv_regs
    return {
        "X": [r.a1, r.a2],
        "F": [r.fa1, r.fa2],
        "int": [0, 1, 3, 31, 63, 2047, -1, 0xFFFFF, 1 << 40],
        # a3 as the base does not overlap the transfer registers.
        "Mem": [rv_mem[r.a3], rv_mem[r.a3 + 8]],
        "Target": [Label("target")],
        "Csr": ["fflags"],
        "Fence": ["rw"],
    }


RV_REPS = _rv_reps()

_RV_LETTER: dict[str, list[str]] = {
    "D": ["X"], "N": ["X"], "M": ["X"], "d": ["F"], "n": ["F"], "m": ["F"], "a": ["F"],
    "I": ["int"], "U": ["int"], "H": ["int"], "W": ["int"], "K": ["int"], "#": ["int"],
    "C": ["int", "Csr"], "L": ["Mem"], "S": ["Mem"], "A": ["Mem"],
    "B": ["Target"], "J": ["Target"], "G": ["Target"], "g": ["Target"], "P": ["Fence"], "Q": ["Fence"],
}  # fmt: skip


def _rv_alts(mn: str) -> dict[int, list[list[set[str]]]]:
    """Arity -> per alternative, the classes each operand may have. The
    riscv64 templates check the kind of every operand exactly, so this is
    the class level version of `encoder._parse_template`."""
    out: dict[int, list[list[set[str]]]] = {}
    for key, tpl in RV_OP.items():
        name, _, n = key.rpartition("_")
        if name != mn:
            continue
        for alt in tpl.split("|"):
            out.setdefault(int(n), []).append([set(_RV_LETTER[ch]) for ch in alt[8:] if ch in _RV_LETTER])
    return out


class RvResult:
    """Accepted points per mnemonic (dotted, "fadd.d") and arity."""

    def __init__(self) -> None:
        self.points: dict[str, dict[int, list[Point]]] = {}


@functools.cache
def rv_oracle(filtered: bool = True, max_arity: int | None = None) -> RvResult:
    """Accepted points for every riscv64 mnemonic; `filtered` and
    `max_arity` as for `x64_oracle`."""
    res = RvResult()
    for mn in sorted(rv_encoder.MNEMONIC_ARGC):

        def enc(ops: Sequence[object], mn: str = mn) -> None:
            rv_encoder.encode(_SINK, mn, ops)

        per_n: dict[int, list[Point]] = {}
        for n, alts in sorted(_rv_alts(mn).items()):
            if max_arity is not None and n > max_arity:
                continue
            if n == 0:
                per_n[0] = [()]
                continue
            if filtered:
                viable: Iterable[Point] = sorted(
                    {p for sets in alts for p in itertools.product(*(sorted(s, key=RV_CLASSES.index) for s in sets))}
                )
            else:
                viable = itertools.product(RV_CLASSES, repeat=n)
            per_n[n] = sorted(p for p in viable if _accepts(enc, [RV_REPS[c] for c in p]))
        res.points[mn] = per_n
    return res


# -- loongarch64 -----------------------------------------------------------------

LA_CLASSES = ["R", "F", "Fcc", "Fcsr", "int", "Target"]


def _la_reps() -> dict[str, list[Any]]:
    r = la_regs
    return {
        # Three integer registers, so an am* rd can differ from rk and rj.
        "R": [r.a1, r.a2, r.a3],
        "F": [r.fa1, r.fa2],
        "Fcc": [r.fcc1],
        "Fcsr": [r.fcsr1],
        "int": [0, 1, 4, 31, 63, 2047, -1, 0x7FFFF, 1 << 40],
        "Target": [Label("target")],
    }


LA_REPS = _la_reps()

# Template letter -> the classes of the operands it takes (M and N take two).
_LA_LETTER: dict[str, list[list[str]]] = {
    **{c: [["R"]] for c in "DJK"},
    **{c: [["F"]] for c in "djka"},
    **{c: [["Fcc"]] for c in "CcE"},
    **{c: [["Fcsr"]] for c in "Ss"},
    **{c: [["int"]] for c in "iuhzwxpoqyYUPX#%"},
    **{c: [["int"], ["int"]] for c in "MN"},
    **{c: [["Target"]] for c in "BRTVLlO"},
}


def _la_alts(mn: str) -> dict[int, list[list[set[str]]]]:
    """Arity -> per alternative, the classes each operand may have, the
    class level version of `encoder._parse_template`."""
    out: dict[int, list[list[set[str]]]] = {}
    for key, tpl in LA_OP.items():
        name, _, n = key.rpartition("_")
        if name != mn:
            continue
        for alt in tpl.split("|"):
            ops = [set(cls) for ch in alt[8:] for cls in _LA_LETTER.get(ch, [])]
            out.setdefault(int(n), []).append(ops)
    return out


@functools.cache
def la_oracle(filtered: bool = True, max_arity: int | None = None) -> RvResult:
    """Accepted points for every loongarch64 mnemonic (dotted, "add.d");
    `filtered` and `max_arity` as for `x64_oracle`."""
    res = RvResult()
    for mn in sorted(la_encoder.MNEMONIC_ARGC):

        def enc(ops: Sequence[object], mn: str = mn) -> None:
            la_encoder.encode(_SINK, mn, ops)

        per_n: dict[int, list[Point]] = {}
        for n, alts in sorted(_la_alts(mn).items()):
            if max_arity is not None and n > max_arity:
                continue
            if n == 0:
                per_n[0] = [()]
                continue
            if filtered:
                viable: Iterable[Point] = sorted(
                    {p for sets in alts for p in itertools.product(*(sorted(s, key=LA_CLASSES.index) for s in sets))}
                )
            else:
                viable = itertools.product(LA_CLASSES, repeat=n)
            per_n[n] = sorted(p for p in viable if _accepts(enc, [LA_REPS[c] for c in p]))
        res.points[mn] = per_n
    return res


# -- rendering -----------------------------------------------------------------


def _union(classes: frozenset[str], order: list[str], names: dict[str, str]) -> str:
    out: list[str] = []
    for c in sorted(classes, key=order.index):
        t = names.get(c, c)
        if t not in out:
            out.append(t)
    return " | ".join(out)


def _params(sig: Sig, order: list[str], names: dict[str, str]) -> str:
    return "".join(f"op{i}: {_union(p, order, names)}, " for i, p in enumerate(sig))


def _defs(
    name: str,
    sigs_by_n: dict[int, list[Sig]],
    doc: str,
    order: list[str],
    names: dict[str, str],
    *,
    method: bool,
    kwonly: str = "",
    indent: str = "",
) -> list[str]:
    """`def` lines for one mnemonic, as a module function (with `asm=`)
    or as a method. One def per signature, `@overload` when several."""
    tail = kwonly
    if not method:
        tail += "asm: Assembler | None = None, "
    sigs = [s for n in sorted(sigs_by_n) for s in sigs_by_n[n]]
    lines: list[str] = []
    for i, sig in enumerate(sigs):
        params = ("self, " if method else "") + _params(sig, order, names)
        if sig:
            params += "/, "
        if tail:
            params += "*, " + tail
        params = params.rstrip(", ")
        if len(sigs) > 1:
            lines.append(f"{indent}@overload")
        # Hover shows the first overload's docstring for all of them.
        if i == 0:
            lines.append(f"{indent}def {name}({params}) -> None:")
            lines.append(f'{indent}    """{doc}"""')
        else:
            lines.append(f"{indent}def {name}({params}) -> None: ...")
    if not sigs:
        raise ValueError(f"{name} accepts nothing")
    return lines


def _merge_all(points: dict[int, list[Point]]) -> dict[int, list[Sig]]:
    return {n: merge(p) for n, p in points.items() if p}


def _all_literal(names: Iterable[str]) -> str:
    body = "".join(f'    "{n}",\n' for n in names)
    return f"__all__ = [\n{body}]\n"


X64_NAMES = {"int": "_Imm", "Target": "_Target"}


# Misspelled mnemonics: Assembler.__getattr__ (a bound mnemonic) would accept
# any name, so the arch assemblers narrow it to a type that cannot be called.
_NOT_AN_INSN = (
    "\nclass _NotAnInstruction:\n"
    '    """What an unknown attribute of an arch assembler is to a type checker:\n'
    '    not callable, so `a.movv(...)` is reported."""\n'
)
_GETATTR = (
    "    def __getattr__(self, name: str) -> _NotAnInstruction:  # type: ignore[override]  "
    "# pyright: ignore[reportIncompatibleMethodOverride]\n"
    '        """Unknown names are not instructions."""\n'
)


def render_x64_insns(res: X64Result) -> str:
    insns = x64_insns.INSNS
    order, names = X64_CLASSES, X64_NAMES
    merged = {py: _merge_all(p) for py, p in res.points.items()}
    short = {py: merge(p) for py, p in res.short.items()}
    doc = x64_insns.__doc__ or ""
    out = [HEADER + f'"""{doc.strip()}\n"""\n']
    out.append(
        "from collections.abc import Callable\n"
        "from typing import Protocol, overload\n\n"
        "from ..core.assembler import Assembler\n"
        "from ..core.labels import Extern, Label\n"
        "from ..core.operand import Imm\n"
        "from .mem import Mem8, Mem16, Mem32, Mem64, Mem80, Mem128, Mem256, MemAny\n"
        "from .regs import Gp8, Gp16, Gp32, Gp64, St, Xmm, Ymm\n\n"
        "# Annotations inside X64Assembler go through these aliases: its `int`\n"
        "# method would shadow the builtin.\n"
        "type _Imm = int | Imm\n"
        "type _Target = Label | Extern | str\n\n"
        "PY_NAMES: dict[str, str]\n"
        "SHORT_BRANCHES: frozenset[str]\n"
        "INSNS: dict[str, Callable[..., None]]\n\n"
        "def nop_fill(n: int) -> bytes: ...\n"
    )
    # Protocols for the branches with a `.short` attribute.
    for py in sorted(short):
        fn = insns[py]
        sdoc = getattr(fn, "short").__doc__ or ""
        for method, suffix in ((False, ""), (True, "_method")):
            out.append(f"\nclass _{py}{suffix}(Protocol):")
            out.append(f'    """{fn.__doc__}"""\n')
            out += _defs("__call__", merged[py], fn.__doc__ or "", order, names, method=True,
                         kwonly="" if method else "asm: Assembler | None = None, ", indent="    ")
            out += _defs("short", {1: short[py]}, sdoc, order, names, method=True,
                         kwonly="" if method else "asm: Assembler | None = None, ", indent="    ")
    out.append(_NOT_AN_INSN)
    out.append("\nclass X64Assembler(Assembler):")
    out.append('    """An Assembler for x64. `Assembler("x64")` returns one; its mnemonic\n'
               '    methods are typed in the stub."""\n')
    out.append(_GETATTR)
    for py in sorted(insns):
        src = "int_" if py == "int" else py
        if src in short:
            out.append(f"    {py}: _{src}_method")
            continue
        out += _defs(py, merged[src], insns[py].__doc__ or "", order, names, method=True, indent="    ")
    out.append("")
    for py in x64_insns.__all__:
        if py in short:
            out.append(f"{py}: _{py}")
            continue
        out += _defs(py, merged[py], insns[py].__doc__ or "", order, names, method=False)
    out.append("")
    out.append(_all_literal(x64_insns.__all__))
    return "\n".join(out)


A64_NAMES = {
    "int": "_Imm",
    "Target": "_Target",
    "RegModX": "RegMod[X]",
    "RegModW": "RegMod[W]",
    "Mem": "MemExpr",
    "Bti": "_Bti",
}
_A64_WIDE = frozenset(["movz", "movn", "movk"])


def render_a64_insns(res: A64Result) -> str:
    insns = a64_insns.INSNS
    order, names = A64_CLASSES, A64_NAMES
    merged = {py: _merge_all(p) for py, p in res.points.items()}
    cond = {c: merge(p) for c, p in res.cond.items()}
    doc = a64_insns.__doc__ or ""
    out = [HEADER + f'"""{doc.strip()}\n"""\n']
    out.append(
        "from collections.abc import Callable\n"
        "from typing import Literal, Protocol, overload\n\n"
        "from ..core.assembler import Assembler\n"
        "from ..core.labels import Extern, Label\n"
        "from ..core.operand import Imm\n"
        "from .mem import MemExpr\n"
        "from .regs import Cond, D, Mod, Q, RegMod, S, Sp, W, X\n\n"
        "# Annotations inside Aarch64Assembler go through these aliases: its\n"
        "# `str` method would shadow the builtin.\n"
        "type _Imm = int | Imm\n"
        "type _Target = Label | Extern | str\n"
        'type _Bti = Literal["c", "j", "jc"]\n\n'
        "PY_NAMES: dict[str, str]\n"
        "INSNS: dict[str, Callable[..., None]]\n"
    )
    b = insns["b"]
    for method, suffix in ((False, ""), (True, "_method")):
        kw = "" if method else "asm: Assembler | None = None, "
        out.append(f"\nclass _b{suffix}(Protocol):")
        out.append(f'    """{b.__doc__} `b.eq(...)` and friends are the conditional forms."""\n')
        out += _defs("__call__", merged["b"], b.__doc__ or "", order, names, method=True, kwonly=kw,
                     indent="    ")
        for c in A64_COND:
            cdoc = getattr(b, c).__doc__ or ""
            out += _defs(c, {1: cond[c]}, cdoc, order, names, method=True, kwonly=kw, indent="    ")
    out.append(_NOT_AN_INSN)
    out.append("\nclass Aarch64Assembler(Assembler):")
    out.append('    """An Assembler for aarch64. `Assembler("aarch64")` returns one; its\n'
               '    mnemonic methods are typed in the stub."""\n')
    out.append(_GETATTR)
    for py in sorted(insns):
        src = "str_" if py == "str" else py
        if src == "b":
            out.append("    b: _b_method")
            continue
        kw = "lsl: int | None = None, " if src in _A64_WIDE else ""
        out += _defs(py, merged[src], insns[py].__doc__ or "", order, names, method=True, kwonly=kw,
                     indent="    ")
    out.append("")
    for py in a64_insns.__all__:
        if py == "b":
            out.append("b: _b")
            continue
        kw = "lsl: int | None = None, " if py in _A64_WIDE else ""
        out += _defs(py, merged[py], insns[py].__doc__ or "", order, names, method=False, kwonly=kw)
    out.append("")
    out.append(_all_literal(a64_insns.__all__))
    return "\n".join(out)


RV_NAMES = {"int": "_Imm", "Target": "_Target", "Mem": "MemExpr", "Csr": "CsrName", "Fence": "FenceSet"}


class _DotNode:
    """A dotted name in a mnemonic tree (riscv64, loongarch64): `fcvt`,
    `fcvt.w`, `fcvt.w.d`. `mnemonic` is set when the name is an
    instruction; `children` are keyed by their Python spelling."""

    def __init__(self, path: str):
        self.path = path
        self.mnemonic: str | None = None
        self.children: dict[str, _DotNode] = {}

    @property
    def proto(self) -> str:
        return "_" + self.path.replace(".", "_")


class _Dotted:
    """What the dotted stub renderer needs from one architecture."""

    def __init__(self, insns: Any, argc: dict[str, tuple[int, ...]], classes: list[str], names: dict[str, str],
                 part: Callable[[str], str] = lambda p: p, kw: Callable[[str | None], str] = lambda mn: ""):
        self.insns, self.argc, self.classes, self.names = insns, argc, classes, names
        self.part = part  # Python spelling of one dotted part
        self.kw = kw  # keywords of a mnemonic before `asm`

    def tree(self) -> dict[str, _DotNode]:
        top: dict[str, _DotNode] = {}
        for mn in sorted(self.argc):
            parts = mn.split(".")
            node = top.setdefault(parts[0], _DotNode(parts[0]))
            for i, part in enumerate(parts[1:], 2):
                node = node.children.setdefault(self.part(part), _DotNode(".".join(parts[:i])))
            node.mnemonic = mn
        return top

    def kwonly(self, mn: str | None, method: bool) -> str:
        # Keywords before `asm`: `_defs` adds `asm` to module functions
        # itself, protocol methods get it here unless `method`.
        kw = self.kw(mn)
        return kw if method else kw + "asm: Assembler | None = None, "

    def group(self, path: str) -> Any:
        obj: Any = self.insns.INSNS[path.split(".")[0]]
        for part in path.split(".")[1:]:
            obj = getattr(obj, self.part(part))
        return obj

    def protocols(self, node: _DotNode, merged: dict[str, dict[int, list[Sig]]], method: bool) -> list[str]:
        """Protocol classes for a node with children, and for its subtrees."""
        order, names = self.classes, self.names
        suffix = "_method" if method else ""
        obj: Any = self.insns.MNEMONICS[node.mnemonic] if node.mnemonic else self.group(node.path)
        out = [f"\nclass {node.proto}{suffix}(Protocol):", f'    """{obj.__doc__}"""\n']
        if node.mnemonic:
            out += _defs("__call__", merged[node.mnemonic], obj.__doc__ or "", order, names, method=True,
                         kwonly=self.kwonly(node.mnemonic, method), indent="    ")
        nested: list[_DotNode] = []
        for part, child in node.children.items():
            if child.children:
                out.append(f"    {part}: {child.proto}{suffix}")
                nested.append(child)
                continue
            assert child.mnemonic is not None
            doc = self.insns.MNEMONICS[child.mnemonic].__doc__ or ""
            out += _defs(part, merged[child.mnemonic], doc, order, names, method=True,
                         kwonly=self.kwonly(child.mnemonic, method), indent="    ")
        for child in nested:
            out += self.protocols(child, merged, method)
        return out

    def render(self, points: dict[str, dict[int, list[Point]]], imports: str, assembler: str) -> str:
        """insns.pyi: `imports` after the core imports, `assembler` the
        class statement and docstring of the arch's Assembler."""
        order, names, insns = self.classes, self.names, self.insns
        merged = {mn: _merge_all(p) for mn, p in points.items()}
        pynames = {insns.PY_NAMES.get(k, k): node for k, node in self.tree().items()}
        doc = insns.__doc__ or ""
        out = [HEADER + f'"""{doc.strip()}\n"""\n']
        cls = assembler.split("class ", 1)[1].split("(", 1)[0]
        extra = getattr(insns, "py_part", None)
        part = "" if extra is None else (
            f'def py_part(part: str) -> str:\n    """{" ".join((extra.__doc__ or "").split())}"""\n\n'
        )
        out.append(
            "from collections.abc import Callable\n"
            "from typing import Protocol, overload\n\n"
            "from ..core.assembler import Assembler\n"
            "from ..core.labels import Extern, Label\n"
            "from ..core.operand import Imm\n"
            + imports
            + f"\n# Annotations inside {cls} go through these aliases, as on\n"
            "# the other architectures.\n"
            "type _Imm = int | Imm\n"
            "type _Target = Label | Extern | str\n\n"
            "PY_NAMES: dict[str, str]\n"
            "INSNS: dict[str, Callable[..., None]]\n"
            "MNEMONICS: dict[str, Callable[..., None]]\n\n"
            + part
            + "class Group:\n"
            f'    """{" ".join((insns.Group.__doc__ or "").split())}"""\n\n'
            "    def __init__(self, name: str) -> None: ...\n"
            "    def __call__(self, *ops: object, **kw: object) -> None: ...\n"
        )
        for method in (False, True):
            for node in pynames.values():
                if node.children:
                    out += self.protocols(node, merged, method)
        out.append(_NOT_AN_INSN)
        out.append(assembler)
        out.append(_GETATTR)
        for py in sorted(insns.INSNS):
            node = pynames[insns.PY_NAMES.get(py, py)]
            if node.children:
                out.append(f"    {py}: {node.proto}_method")
                continue
            assert node.mnemonic is not None
            out += _defs(py, merged[node.mnemonic], insns.INSNS[py].__doc__ or "", order, names, method=True,
                         kwonly=self.kwonly(node.mnemonic, True), indent="    ")
        out.append("")
        for py in insns.__all__:
            node = pynames[py]
            if node.children:
                out.append(f"{py}: {node.proto}")
                continue
            assert node.mnemonic is not None
            out += _defs(py, merged[node.mnemonic], insns.INSNS[py].__doc__ or "", order, names, method=False,
                         kwonly=self.kwonly(node.mnemonic, True))
        out.append("")
        out.append(_all_literal(insns.__all__))
        return "\n".join(out)


RV_DOTTED = _Dotted(
    rv_insns, rv_encoder.MNEMONIC_ARGC, RV_CLASSES, RV_NAMES,
    kw=lambda mn: "rm: Rm | None = None, " if mn in rv_encoder.RM_MNEMONICS else "",
)


def render_rv_insns(res: RvResult) -> str:
    return RV_DOTTED.render(
        res.points,
        "from .mem import MemExpr\n"
        "from .regs import CsrName, F, FenceSet, Rm, X\n",
        "\nclass Riscv64Assembler(Assembler):\n"
        '    """An Assembler for riscv64. `Assembler("riscv64")` returns one; its\n'
        '    mnemonic methods are typed in the stub."""\n',
    )


LA_NAMES = {"int": "_Imm", "Target": "_Target"}

LA_DOTTED = _Dotted(la_insns, la_encoder.MNEMONIC_ARGC, LA_CLASSES, LA_NAMES, part=la_insns.py_part)


def render_la_insns(res: RvResult) -> str:
    return LA_DOTTED.render(
        res.points,
        "from .regs import F, Fcc, Fcsr, R\n",
        "\nclass Loongarch64Assembler(Assembler):\n"
        '    """An Assembler for loongarch64. `Assembler("loongarch64")` returns\n'
        '    one; its mnemonic methods are typed in the stub."""\n',
    )


def render_x64_init() -> str:
    import jita.x64 as pkg

    return (
        HEADER
        + f'"""{(pkg.__doc__ or "").strip()}"""\n\n'
        + "from collections.abc import Callable\n"
        "from typing import Any\n\n"
        "from ..core.arch import Arch\n"
        "from ..core.assembler import label as label\n"
        "from .insns import *\n"
        "from .insns import X64Assembler as X64Assembler\n"
        "from .mem import *\n"
        "from .regs import *\n"
        "from .structs import typed as typed\n\n"
        "class X64Arch(Arch):\n"
        "    @property\n"
        "    def insns(self) -> dict[str, Callable[..., Any]]: ...\n"
        "    @property\n"
        "    def assembler_class(self) -> type[X64Assembler]: ...\n"
        "    def nop_fill(self, n: int) -> bytes: ...\n"
        "    def icache_flush(self, addr: int, size: int) -> None: ...\n\n"
        "ARCH: X64Arch\n\n" + _all_literal(pkg.__all__)
    )


def render_a64_init() -> str:
    import jita.aarch64 as pkg

    return (
        HEADER
        + f'"""{(pkg.__doc__ or "").strip()}"""\n\n'
        + "from collections.abc import Callable\n"
        "from typing import Any\n\n"
        "from ..core.arch import Arch\n"
        "from ..core.assembler import label as label\n"
        "from .insns import *\n"
        "from .insns import Aarch64Assembler as Aarch64Assembler\n"
        "from .mem import *\n"
        "from .regs import *\n\n"
        "NOP: bytes\n\n"
        "class Aarch64Arch(Arch):\n"
        "    def __init__(self) -> None: ...\n"
        "    @property\n"
        "    def insns(self) -> dict[str, Callable[..., Any]]: ...\n"
        "    @property\n"
        "    def assembler_class(self) -> type[Aarch64Assembler]: ...\n"
        "    def nop_fill(self, n: int) -> bytes: ...\n"
        "    def icache_flush(self, addr: int, size: int) -> None: ...\n\n"
        "ARCH: Aarch64Arch\n\n" + _all_literal(pkg.__all__)
    )


def render_rv_init() -> str:
    import jita.riscv64 as pkg

    return (
        HEADER
        + f'"""{(pkg.__doc__ or "").strip()}"""\n\n'
        + "from collections.abc import Callable\n"
        "from typing import Any\n\n"
        "from ..core.arch import Arch\n"
        "from ..core.assembler import label as label\n"
        "from .insns import *\n"
        "from .insns import Riscv64Assembler as Riscv64Assembler\n"
        "from .mem import *\n"
        "from .regs import *\n\n"
        "NOP: bytes\n"
        "SYS_RISCV_FLUSH_ICACHE: int\n\n"
        "class Riscv64Arch(Arch):\n"
        "    def __init__(self) -> None: ...\n"
        "    @property\n"
        "    def insns(self) -> dict[str, Callable[..., Any]]: ...\n"
        "    @property\n"
        "    def assembler_class(self) -> type[Riscv64Assembler]: ...\n"
        "    def nop_fill(self, n: int) -> bytes: ...\n"
        "    def icache_flush(self, addr: int, size: int) -> None: ...\n\n"
        "ARCH: Riscv64Arch\n\n"
        "def _find_flush() -> Callable[[int, int], None]: ...\n"
        "def _syscall_flush() -> Callable[[int, int], None]: ...\n\n" + _all_literal(pkg.__all__)
    )


def render_la_init() -> str:
    import jita.loongarch64 as pkg

    return (
        HEADER
        + f'"""{(pkg.__doc__ or "").strip()}"""\n\n'
        + "from collections.abc import Callable\n"
        "from typing import Any\n\n"
        "from ..core.arch import Arch\n"
        "from ..core.assembler import label as label\n"
        "from .insns import *\n"
        "from .insns import Loongarch64Assembler as Loongarch64Assembler\n"
        "from .regs import *\n\n"
        "NOP: bytes\n"
        "IBAR_RET: bytes\n\n"
        "class Loongarch64Arch(Arch):\n"
        "    def __init__(self) -> None: ...\n"
        "    @property\n"
        "    def insns(self) -> dict[str, Callable[..., Any]]: ...\n"
        "    @property\n"
        "    def assembler_class(self) -> type[Loongarch64Assembler]: ...\n"
        "    def nop_fill(self, n: int) -> bytes: ...\n"
        "    def icache_flush(self, addr: int, size: int) -> None: ...\n\n"
        "ARCH: Loongarch64Arch\n\n"
        "def _find_flush() -> Callable[[int, int], None]: ...\n"
        "def _stub_flush() -> Callable[[int, int], None]: ...\n\n" + _all_literal(pkg.__all__)
    )


# -- accepted corpus -----------------------------------------------------------

X64_EXPR = {
    "Gp8": "bl", "Gp16": "bx", "Gp32": "ebx", "Gp64": "rbx", "Xmm": "xmm1", "Ymm": "ymm1",
    "St": "st1", "Mem8": "byte[rbx]", "Mem16": "word[rbx]", "Mem32": "dword[rbx]",
    "Mem64": "qword[rbx]", "Mem80": "tword[rbx]", "Mem128": "oword[rbx]",
    "Mem256": "yword[rbx]", "MemAny": "ptr[rbx]", "int": "1", "Target": '"lbl"',
}  # fmt: skip
A64_EXPR = {
    "X": "x1", "W": "w1", "Sp": "sp", "S": "s1", "D": "d1", "Q": "q1",
    "RegModX": "(x2 << 3)", "RegModW": "w2.uxtw()", "Mod": 'Mod("lsl", 16)', "int": "1",
    "float": "1.5", "Mem": "mem[x3]", "Target": '"lbl"', "Cond": '"eq"', "Bti": '"c"',
}  # fmt: skip
LA_EXPR = {"R": "a1", "F": "fa1", "Fcc": "fcc1", "Fcsr": "fcsr1", "int": "1", "Target": '"lbl"'}
RV_EXPR = {
    "X": "a1", "F": "fa1", "int": "1", "Mem": "mem[a3]", "Target": '"lbl"', "Csr": '"fflags"',
    "Fence": '"rw"',
}  # fmt: skip


def _calls(fn: str, points: Iterable[Point], expr: dict[str, str]) -> list[str]:
    return [f"{fn}({', '.join(expr[c] for c in p)})" for p in points]


def _corpus_file(arch: str, calls: list[str]) -> str:
    # Calls go into functions of 50 lines: pyright checks a long module
    # level flow several times slower.
    out = [
        HEADER.rstrip(),
        f'"""Accepted {arch} calls, one per accepted class tuple (tools/gen_stubs.py)."""',
        "",
        "from jita import Assembler",
        f"from jita.{arch} import *  # noqa: F403",
        "",
        f'a = Assembler("{arch}")',
    ]
    for i in range(0, len(calls), 50):
        out += ["", "", f"def _calls{i // 50}() -> None:"]
        out += [f"    {c}" for c in calls[i : i + 50]]
    return "\n".join(out) + "\n"


def corpus() -> dict[str, str]:
    """File name -> source of the accepted corpus: one call per accepted
    class tuple, as a module function and as an assembler method. Every
    call must type check."""
    x, a = x64_oracle(), a64_oracle()
    xc: list[str] = []
    for py, per_n in sorted(x.points.items()):
        pts = [p for n in sorted(per_n) for p in per_n[n]]
        xc += _calls(py, pts, X64_EXPR) + _calls(f"a.{py}", pts, X64_EXPR)
        if py in x.short:
            xc += _calls(f"{py}.short", x.short[py], X64_EXPR) + _calls(f"a.{py}.short", x.short[py], X64_EXPR)
    xc += _calls("a.int", x.points["int_"][1], X64_EXPR)
    ac: list[str] = []
    for py, per_n in sorted(a.points.items()):
        pts = [p for n in sorted(per_n) for p in per_n[n]]
        ac += _calls(py, pts, A64_EXPR) + _calls(f"a.{py}", pts, A64_EXPR)
    for c, pts in a.cond.items():
        ac += _calls(f"b.{c}", pts, A64_EXPR) + _calls(f"a.b.{c}", pts, A64_EXPR)
    ac += _calls("a.str", a.points["str_"][2], A64_EXPR)
    ac += ["movz(x1, 1, lsl=16)", "a.movk(w1, 1, lsl=16)"]
    rc: list[str] = []
    for mn, per_n in sorted(rv_oracle().points.items()):
        pts = [p for n in sorted(per_n) for p in per_n[n]]
        parts = mn.split(".")
        py = ".".join([rv_insns.PY_NAMES.get(parts[0], parts[0]), *parts[1:]])
        rc += _calls(py, pts, RV_EXPR) + _calls(f"a.{py}", pts, RV_EXPR)
    rc += _calls("a.min", rv_oracle().points["min"][3], RV_EXPR) + _calls("a.max", rv_oracle().points["max"][3], RV_EXPR)
    rc += ['fadd.d(fa1, fa1, fa1, rm="rtz")', 'a.fcvt.w.d(a1, fa1, rm="rne")']
    lc: list[str] = []
    for mn, per_n in sorted(la_oracle().points.items()):
        pts = [p for n in sorted(per_n) for p in per_n[n]]
        parts = mn.split(".")
        py = ".".join([la_insns.PY_NAMES.get(parts[0], parts[0]), *map(la_insns.py_part, parts[1:])])
        lc += _calls(py, pts, LA_EXPR) + _calls(f"a.{py}", pts, LA_EXPR)
    return {
        "accepted_x64.py": _corpus_file("x64", xc),
        "accepted_aarch64.py": _corpus_file("aarch64", ac),
        "accepted_riscv64.py": _corpus_file("riscv64", rc),
        "accepted_loongarch64.py": _corpus_file("loongarch64", lc),
    }


# -- prefilter check ---------------------------------------------------------------

# Classes whose values the static type of another class already covers:
# condition, bti, CSR and fence set names are strings, and a str is a label
# name.
_COVERED_BY = {"Cond": "Target", "Bti": "Target", "Csr": "Target", "Fence": "Target"}


def _covered(point: Point, accepted: set[Point]) -> bool:
    return tuple(_COVERED_BY.get(c, c) for c in point) in accepted


def prefilter_drift(max_arity: int = 2) -> list[str]:
    """Compare the oracles with and without the class level prefilter,
    for forms with at most `max_arity` operands. Returns one line per
    difference; empty when the prefilter drops nothing the encoder
    accepts (and adds nothing, which it cannot)."""
    out: list[str] = []
    pairs: list[tuple[str, dict[str, dict[int, list[Point]]], dict[str, dict[int, list[Point]]]]] = []
    xf, xu = x64_oracle(True, max_arity), x64_oracle(False, max_arity)
    pairs.append(("x64", xf.points, xu.points))
    pairs.append(("x64 .short", {k: {1: v} for k, v in xf.short.items()}, {k: {1: v} for k, v in xu.short.items()}))
    af, au = a64_oracle(True, max_arity), a64_oracle(False, max_arity)
    pairs.append(("aarch64", af.points, au.points))
    rf, ru = rv_oracle(True, max_arity), rv_oracle(False, max_arity)
    pairs.append(("riscv64", rf.points, ru.points))
    lf, lu = la_oracle(True, max_arity), la_oracle(False, max_arity)
    pairs.append(("loongarch64", lf.points, lu.points))
    for arch, filt, unfilt in pairs:
        for py in sorted(set(filt) | set(unfilt)):
            for n in sorted(set(filt.get(py, {})) | set(unfilt.get(py, {}))):
                f = set(filt.get(py, {}).get(n, []))
                u = set(unfilt.get(py, {}).get(n, []))
                missing = sorted(p for p in u - f if not _covered(p, f))
                extra = sorted(f - u)
                if missing:
                    out.append(f"{arch} {py}/{n}: prefilter drops {missing}")
                if extra:
                    out.append(f"{arch} {py}/{n}: only with prefilter {extra}")
    return out


# -- entry points ----------------------------------------------------------------


def generate() -> dict[Path, str]:
    """Stub path -> generated text."""
    return {
        ROOT / "jita/x64/insns.pyi": render_x64_insns(x64_oracle()),
        ROOT / "jita/x64/__init__.pyi": render_x64_init(),
        ROOT / "jita/aarch64/insns.pyi": render_a64_insns(a64_oracle()),
        ROOT / "jita/aarch64/__init__.pyi": render_a64_init(),
        ROOT / "jita/riscv64/insns.pyi": render_rv_insns(rv_oracle()),
        ROOT / "jita/riscv64/__init__.pyi": render_rv_init(),
        ROOT / "jita/loongarch64/insns.pyi": render_la_insns(la_oracle()),
        ROOT / "jita/loongarch64/__init__.pyi": render_la_init(),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="only report stale stubs")
    parser.add_argument(
        "--unfiltered",
        type=int,
        metavar="N",
        help="instead of writing stubs, ask the encoder about every class tuple of up to N operands "
        "without the class level prefilter and report where the two disagree (N=2 takes a few seconds)",
    )
    args = parser.parse_args(argv)
    if args.unfiltered is not None:
        drift = prefilter_drift(args.unfiltered)
        for line in drift:
            print(line)
        return 1 if drift else 0
    stale = []
    for path, text in generate().items():
        old = path.read_text() if path.exists() else None
        if old == text:
            continue
        stale.append(path)
        if not args.check:
            path.write_text(text)
    for path in stale:
        print(f"{'stale' if args.check else 'wrote'} {path.relative_to(ROOT)}")
    return 1 if args.check and stale else 0


if __name__ == "__main__":
    sys.exit(main())
