# Generated by tools/gen_stubs.py from the encoder tables. Do not edit.
"""Module-level aarch64 mnemonic functions, generated from the template table.

Every mnemonic in `jita.aarch64.table.MAP_OP` becomes a function
`name(*ops, asm=None)` that encodes into `asm`, or into the current
Assembler when `asm` is None. `and` and `str` are spelled `and_` and
`str_` (a Python keyword and a builtin); `a.str(...)` also works as a
method.

Conditional branches exist both as DynASM spells them (`beq`, `bne`,
`bhs`, ...) and as attributes of `b`: `b.eq(lbl)`, `b.ne("loop")`.

`movz`, `movn` and `movk` take the halfword shift as a keyword:
`movk(x0, 0x1234, lsl=16)` is `movk x0, #0x1234, lsl #16`.

Type checkers read `insns.pyi` next to this module, which
`tools/gen_stubs.py` generates with one overload per accepted combination
of operand classes.
"""

from collections.abc import Callable
from typing import Literal, Protocol, overload

from ..core.assembler import Assembler
from ..core.labels import Extern, Label
from ..core.operand import Imm
from .mem import MemExpr
from .regs import Cond, D, Mod, Q, RegMod, S, Sp, W, X

# Annotations inside Aarch64Assembler go through these aliases: its
# `str` method would shadow the builtin.
type _Imm = int | Imm
type _Target = Label | Extern | str
type _Bti = Literal["c", "j", "jc"]

PY_NAMES: dict[str, str]
INSNS: dict[str, Callable[..., None]]


class _b(Protocol):
    """Emit `b` (1 operands). `b.eq(...)` and friends are the conditional forms."""

    def __call__(self, op0: _Target, /, *, asm: Assembler | None = None) -> None:
        """Emit `b` (1 operands)."""
    def eq(self, op0: _Target, /, *, asm: Assembler | None = None) -> None:
        """Emit `b.eq` (1 operands)."""
    def ne(self, op0: _Target, /, *, asm: Assembler | None = None) -> None:
        """Emit `b.ne` (1 operands)."""
    def cs(self, op0: _Target, /, *, asm: Assembler | None = None) -> None:
        """Emit `b.cs` (1 operands)."""
    def cc(self, op0: _Target, /, *, asm: Assembler | None = None) -> None:
        """Emit `b.cc` (1 operands)."""
    def mi(self, op0: _Target, /, *, asm: Assembler | None = None) -> None:
        """Emit `b.mi` (1 operands)."""
    def pl(self, op0: _Target, /, *, asm: Assembler | None = None) -> None:
        """Emit `b.pl` (1 operands)."""
    def vs(self, op0: _Target, /, *, asm: Assembler | None = None) -> None:
        """Emit `b.vs` (1 operands)."""
    def vc(self, op0: _Target, /, *, asm: Assembler | None = None) -> None:
        """Emit `b.vc` (1 operands)."""
    def hi(self, op0: _Target, /, *, asm: Assembler | None = None) -> None:
        """Emit `b.hi` (1 operands)."""
    def ls(self, op0: _Target, /, *, asm: Assembler | None = None) -> None:
        """Emit `b.ls` (1 operands)."""
    def ge(self, op0: _Target, /, *, asm: Assembler | None = None) -> None:
        """Emit `b.ge` (1 operands)."""
    def lt(self, op0: _Target, /, *, asm: Assembler | None = None) -> None:
        """Emit `b.lt` (1 operands)."""
    def gt(self, op0: _Target, /, *, asm: Assembler | None = None) -> None:
        """Emit `b.gt` (1 operands)."""
    def le(self, op0: _Target, /, *, asm: Assembler | None = None) -> None:
        """Emit `b.le` (1 operands)."""
    def al(self, op0: _Target, /, *, asm: Assembler | None = None) -> None:
        """Emit `b.al` (1 operands)."""
    def hs(self, op0: _Target, /, *, asm: Assembler | None = None) -> None:
        """Emit `b.hs` (1 operands)."""
    def lo(self, op0: _Target, /, *, asm: Assembler | None = None) -> None:
        """Emit `b.lo` (1 operands)."""

class _b_method(Protocol):
    """Emit `b` (1 operands). `b.eq(...)` and friends are the conditional forms."""

    def __call__(self, op0: _Target, /) -> None:
        """Emit `b` (1 operands)."""
    def eq(self, op0: _Target, /) -> None:
        """Emit `b.eq` (1 operands)."""
    def ne(self, op0: _Target, /) -> None:
        """Emit `b.ne` (1 operands)."""
    def cs(self, op0: _Target, /) -> None:
        """Emit `b.cs` (1 operands)."""
    def cc(self, op0: _Target, /) -> None:
        """Emit `b.cc` (1 operands)."""
    def mi(self, op0: _Target, /) -> None:
        """Emit `b.mi` (1 operands)."""
    def pl(self, op0: _Target, /) -> None:
        """Emit `b.pl` (1 operands)."""
    def vs(self, op0: _Target, /) -> None:
        """Emit `b.vs` (1 operands)."""
    def vc(self, op0: _Target, /) -> None:
        """Emit `b.vc` (1 operands)."""
    def hi(self, op0: _Target, /) -> None:
        """Emit `b.hi` (1 operands)."""
    def ls(self, op0: _Target, /) -> None:
        """Emit `b.ls` (1 operands)."""
    def ge(self, op0: _Target, /) -> None:
        """Emit `b.ge` (1 operands)."""
    def lt(self, op0: _Target, /) -> None:
        """Emit `b.lt` (1 operands)."""
    def gt(self, op0: _Target, /) -> None:
        """Emit `b.gt` (1 operands)."""
    def le(self, op0: _Target, /) -> None:
        """Emit `b.le` (1 operands)."""
    def al(self, op0: _Target, /) -> None:
        """Emit `b.al` (1 operands)."""
    def hs(self, op0: _Target, /) -> None:
        """Emit `b.hs` (1 operands)."""
    def lo(self, op0: _Target, /) -> None:
        """Emit `b.lo` (1 operands)."""

class Aarch64Assembler(Assembler):
    """An Assembler for aarch64. `Assembler("aarch64")` returns one; its
    mnemonic methods are typed in the stub."""

    @overload
    def adc(self, op0: W, op1: W, op2: W, /) -> None:
        """Emit `adc` (3 operands)."""
    @overload
    def adc(self, op0: X, op1: X, op2: X, /) -> None: ...
    @overload
    def adcs(self, op0: W, op1: W, op2: W, /) -> None:
        """Emit `adcs` (3 operands)."""
    @overload
    def adcs(self, op0: X, op1: X, op2: X, /) -> None: ...
    @overload
    def add(self, op0: X | Sp, op1: X | Sp, op2: X | RegMod[X] | RegMod[W] | _Imm, /) -> None:
        """Emit `add` (3 or 4 operands)."""
    @overload
    def add(self, op0: W, op1: W, op2: W | RegMod[W] | _Imm, /) -> None: ...
    @overload
    def add(self, op0: X | Sp, op1: X | Sp, op2: X | W, op3: Mod, /) -> None: ...
    @overload
    def add(self, op0: W, op1: W, op2: W, op3: Mod, /) -> None: ...
    @overload
    def adds(self, op0: W, op1: W, op2: W | RegMod[W] | _Imm, /) -> None:
        """Emit `adds` (3 or 4 operands)."""
    @overload
    def adds(self, op0: X, op1: X | Sp, op2: X | RegMod[X] | RegMod[W] | _Imm, /) -> None: ...
    @overload
    def adds(self, op0: W, op1: W, op2: W, op3: Mod, /) -> None: ...
    @overload
    def adds(self, op0: X, op1: X | Sp, op2: X | W, op3: Mod, /) -> None: ...
    def adr(self, op0: X, op1: _Target, /) -> None:
        """Emit `adr` (2 operands)."""
    def adrp(self, op0: X, op1: _Target, /) -> None:
        """Emit `adrp` (2 operands)."""
    @overload
    def and_(self, op0: X | Sp, op1: X, op2: _Imm, /) -> None:
        """Emit `and` (3 or 4 operands)."""
    @overload
    def and_(self, op0: W, op1: W, op2: W | RegMod[W] | _Imm, /) -> None: ...
    @overload
    def and_(self, op0: X, op1: X, op2: X | RegMod[X], /) -> None: ...
    @overload
    def and_(self, op0: W, op1: W, op2: W, op3: Mod, /) -> None: ...
    @overload
    def and_(self, op0: X, op1: X, op2: X, op3: Mod, /) -> None: ...
    @overload
    def ands(self, op0: W, op1: W, op2: W | RegMod[W] | _Imm, /) -> None:
        """Emit `ands` (3 or 4 operands)."""
    @overload
    def ands(self, op0: X, op1: X, op2: X | RegMod[X] | _Imm, /) -> None: ...
    @overload
    def ands(self, op0: W, op1: W, op2: W, op3: Mod, /) -> None: ...
    @overload
    def ands(self, op0: X, op1: X, op2: X, op3: Mod, /) -> None: ...
    @overload
    def asr(self, op0: W, op1: W, op2: W | _Imm, /) -> None:
        """Emit `asr` (3 operands)."""
    @overload
    def asr(self, op0: X, op1: X, op2: X | _Imm, /) -> None: ...
    def autiasp(self) -> None:
        """Emit `autiasp` (0 operands)."""
    def autibsp(self) -> None:
        """Emit `autibsp` (0 operands)."""
    b: _b_method
    def bal(self, op0: _Target, /) -> None:
        """Emit `b.al` (1 operands)."""
    def bcc(self, op0: _Target, /) -> None:
        """Emit `b.cc` (1 operands)."""
    def bcs(self, op0: _Target, /) -> None:
        """Emit `b.cs` (1 operands)."""
    def beq(self, op0: _Target, /) -> None:
        """Emit `b.eq` (1 operands)."""
    @overload
    def bfi(self, op0: W, op1: W, op2: _Imm, op3: _Imm, /) -> None:
        """Emit `bfi` (4 operands)."""
    @overload
    def bfi(self, op0: X, op1: X, op2: _Imm, op3: _Imm, /) -> None: ...
    @overload
    def bfm(self, op0: W, op1: W, op2: _Imm, op3: _Imm, /) -> None:
        """Emit `bfm` (4 operands)."""
    @overload
    def bfm(self, op0: X, op1: X, op2: _Imm, op3: _Imm, /) -> None: ...
    @overload
    def bfxil(self, op0: W, op1: W, op2: _Imm, op3: _Imm, /) -> None:
        """Emit `bfxil` (4 operands)."""
    @overload
    def bfxil(self, op0: X, op1: X, op2: _Imm, op3: _Imm, /) -> None: ...
    def bge(self, op0: _Target, /) -> None:
        """Emit `b.ge` (1 operands)."""
    def bgt(self, op0: _Target, /) -> None:
        """Emit `b.gt` (1 operands)."""
    def bhi(self, op0: _Target, /) -> None:
        """Emit `b.hi` (1 operands)."""
    def bhs(self, op0: _Target, /) -> None:
        """Emit `b.hs` (1 operands)."""
    @overload
    def bic(self, op0: W, op1: W, op2: W | RegMod[W], /) -> None:
        """Emit `bic` (3 or 4 operands)."""
    @overload
    def bic(self, op0: X, op1: X, op2: X | RegMod[X], /) -> None: ...
    @overload
    def bic(self, op0: W, op1: W, op2: W, op3: Mod, /) -> None: ...
    @overload
    def bic(self, op0: X, op1: X, op2: X, op3: Mod, /) -> None: ...
    @overload
    def bics(self, op0: W, op1: W, op2: W | RegMod[W], /) -> None:
        """Emit `bics` (3 or 4 operands)."""
    @overload
    def bics(self, op0: X, op1: X, op2: X | RegMod[X], /) -> None: ...
    @overload
    def bics(self, op0: W, op1: W, op2: W, op3: Mod, /) -> None: ...
    @overload
    def bics(self, op0: X, op1: X, op2: X, op3: Mod, /) -> None: ...
    def bl(self, op0: _Target, /) -> None:
        """Emit `bl` (1 operands)."""
    def ble(self, op0: _Target, /) -> None:
        """Emit `b.le` (1 operands)."""
    def blo(self, op0: _Target, /) -> None:
        """Emit `b.lo` (1 operands)."""
    def blr(self, op0: X, /) -> None:
        """Emit `blr` (1 operands)."""
    def blraaz(self, op0: X, /) -> None:
        """Emit `blraaz` (1 operands)."""
    def blrabz(self, op0: X, /) -> None:
        """Emit `blrabz` (1 operands)."""
    def bls(self, op0: _Target, /) -> None:
        """Emit `b.ls` (1 operands)."""
    def blt(self, op0: _Target, /) -> None:
        """Emit `b.lt` (1 operands)."""
    def bmi(self, op0: _Target, /) -> None:
        """Emit `b.mi` (1 operands)."""
    def bne(self, op0: _Target, /) -> None:
        """Emit `b.ne` (1 operands)."""
    def bpl(self, op0: _Target, /) -> None:
        """Emit `b.pl` (1 operands)."""
    def br(self, op0: X, /) -> None:
        """Emit `br` (1 operands)."""
    def braa(self, op0: X, op1: X, /) -> None:
        """Emit `braa` (2 operands)."""
    def braaz(self, op0: X, /) -> None:
        """Emit `braaz` (1 operands)."""
    def brab(self, op0: X, op1: X, /) -> None:
        """Emit `brab` (2 operands)."""
    def brabz(self, op0: X, /) -> None:
        """Emit `brabz` (1 operands)."""
    @overload
    def brk(self) -> None:
        """Emit `brk` (0 or 1 operands)."""
    @overload
    def brk(self, op0: _Imm, /) -> None: ...
    def bti(self, op0: _Bti, /) -> None:
        """Emit `bti` (1 operands)."""
    def bvc(self, op0: _Target, /) -> None:
        """Emit `b.vc` (1 operands)."""
    def bvs(self, op0: _Target, /) -> None:
        """Emit `b.vs` (1 operands)."""
    def cbnz(self, op0: X | W, op1: _Target, /) -> None:
        """Emit `cbnz` (2 operands)."""
    def cbz(self, op0: X | W, op1: _Target, /) -> None:
        """Emit `cbz` (2 operands)."""
    @overload
    def ccmn(self, op0: W, op1: W, op2: _Imm, op3: Cond, /) -> None:
        """Emit `ccmn` (4 operands)."""
    @overload
    def ccmn(self, op0: X | W, op1: _Imm, op2: _Imm, op3: Cond, /) -> None: ...
    @overload
    def ccmn(self, op0: X, op1: X, op2: _Imm, op3: Cond, /) -> None: ...
    @overload
    def ccmp(self, op0: W, op1: W, op2: _Imm, op3: Cond, /) -> None:
        """Emit `ccmp` (4 operands)."""
    @overload
    def ccmp(self, op0: X | W, op1: _Imm, op2: _Imm, op3: Cond, /) -> None: ...
    @overload
    def ccmp(self, op0: X, op1: X, op2: _Imm, op3: Cond, /) -> None: ...
    @overload
    def cinc(self, op0: W, op1: W, op2: Cond, /) -> None:
        """Emit `cinc` (3 operands)."""
    @overload
    def cinc(self, op0: X, op1: X, op2: Cond, /) -> None: ...
    @overload
    def cinv(self, op0: W, op1: W, op2: Cond, /) -> None:
        """Emit `cinv` (3 operands)."""
    @overload
    def cinv(self, op0: X, op1: X, op2: Cond, /) -> None: ...
    @overload
    def cls(self, op0: W, op1: W, /) -> None:
        """Emit `cls` (2 operands)."""
    @overload
    def cls(self, op0: X, op1: X, /) -> None: ...
    @overload
    def clz(self, op0: W, op1: W, /) -> None:
        """Emit `clz` (2 operands)."""
    @overload
    def clz(self, op0: X, op1: X, /) -> None: ...
    @overload
    def cmn(self, op0: X | W | Sp, op1: RegMod[W] | _Imm, /) -> None:
        """Emit `cmn` (2 or 3 operands)."""
    @overload
    def cmn(self, op0: X | Sp, op1: X | RegMod[X], /) -> None: ...
    @overload
    def cmn(self, op0: W, op1: W, /) -> None: ...
    @overload
    def cmn(self, op0: X | W | Sp, op1: W, op2: Mod, /) -> None: ...
    @overload
    def cmn(self, op0: X | Sp, op1: X, op2: Mod, /) -> None: ...
    @overload
    def cmp(self, op0: X | W | Sp, op1: RegMod[W] | _Imm, /) -> None:
        """Emit `cmp` (2 or 3 operands)."""
    @overload
    def cmp(self, op0: X | Sp, op1: X | RegMod[X], /) -> None: ...
    @overload
    def cmp(self, op0: W, op1: W, /) -> None: ...
    @overload
    def cmp(self, op0: X | W | Sp, op1: W, op2: Mod, /) -> None: ...
    @overload
    def cmp(self, op0: X | Sp, op1: X, op2: Mod, /) -> None: ...
    @overload
    def cneg(self, op0: W, op1: W, op2: Cond, /) -> None:
        """Emit `cneg` (3 operands)."""
    @overload
    def cneg(self, op0: X, op1: X, op2: Cond, /) -> None: ...
    @overload
    def csel(self, op0: W, op1: W, op2: W, op3: Cond, /) -> None:
        """Emit `csel` (4 operands)."""
    @overload
    def csel(self, op0: X, op1: X, op2: X, op3: Cond, /) -> None: ...
    def cset(self, op0: X | W, op1: Cond, /) -> None:
        """Emit `cset` (2 operands)."""
    def csetm(self, op0: X | W, op1: Cond, /) -> None:
        """Emit `csetm` (2 operands)."""
    @overload
    def csinc(self, op0: W, op1: W, op2: W, op3: Cond, /) -> None:
        """Emit `csinc` (4 operands)."""
    @overload
    def csinc(self, op0: X, op1: X, op2: X, op3: Cond, /) -> None: ...
    @overload
    def csinv(self, op0: W, op1: W, op2: W, op3: Cond, /) -> None:
        """Emit `csinv` (4 operands)."""
    @overload
    def csinv(self, op0: X, op1: X, op2: X, op3: Cond, /) -> None: ...
    @overload
    def csneg(self, op0: W, op1: W, op2: W, op3: Cond, /) -> None:
        """Emit `csneg` (4 operands)."""
    @overload
    def csneg(self, op0: X, op1: X, op2: X, op3: Cond, /) -> None: ...
    @overload
    def eon(self, op0: W, op1: W, op2: W | RegMod[W], /) -> None:
        """Emit `eon` (3 or 4 operands)."""
    @overload
    def eon(self, op0: X, op1: X, op2: X | RegMod[X], /) -> None: ...
    @overload
    def eon(self, op0: W, op1: W, op2: W, op3: Mod, /) -> None: ...
    @overload
    def eon(self, op0: X, op1: X, op2: X, op3: Mod, /) -> None: ...
    @overload
    def eor(self, op0: X | Sp, op1: X, op2: _Imm, /) -> None:
        """Emit `eor` (3 or 4 operands)."""
    @overload
    def eor(self, op0: W, op1: W, op2: W | RegMod[W] | _Imm, /) -> None: ...
    @overload
    def eor(self, op0: X, op1: X, op2: X | RegMod[X], /) -> None: ...
    @overload
    def eor(self, op0: W, op1: W, op2: W, op3: Mod, /) -> None: ...
    @overload
    def eor(self, op0: X, op1: X, op2: X, op3: Mod, /) -> None: ...
    @overload
    def extr(self, op0: W, op1: W, op2: W, op3: _Imm, /) -> None:
        """Emit `extr` (4 operands)."""
    @overload
    def extr(self, op0: X, op1: X, op2: X, op3: _Imm, /) -> None: ...
    @overload
    def fabs(self, op0: D, op1: D, /) -> None:
        """Emit `fabs` (2 operands)."""
    @overload
    def fabs(self, op0: S, op1: S, /) -> None: ...
    @overload
    def fadd(self, op0: D, op1: D, op2: D, /) -> None:
        """Emit `fadd` (3 operands)."""
    @overload
    def fadd(self, op0: S, op1: S, op2: S, /) -> None: ...
    @overload
    def fccmp(self, op0: D, op1: D, op2: _Imm, op3: Cond, /) -> None:
        """Emit `fccmp` (4 operands)."""
    @overload
    def fccmp(self, op0: S, op1: S, op2: _Imm, op3: Cond, /) -> None: ...
    @overload
    def fccmpe(self, op0: D, op1: D, op2: _Imm, op3: Cond, /) -> None:
        """Emit `fccmpe` (4 operands)."""
    @overload
    def fccmpe(self, op0: S, op1: S, op2: _Imm, op3: Cond, /) -> None: ...
    @overload
    def fcmp(self, op0: D, op1: D, /) -> None:
        """Emit `fcmp` (2 operands)."""
    @overload
    def fcmp(self, op0: S | D, op1: _Imm | float, /) -> None: ...
    @overload
    def fcmp(self, op0: S, op1: S, /) -> None: ...
    @overload
    def fcmpe(self, op0: D, op1: D, /) -> None:
        """Emit `fcmpe` (2 operands)."""
    @overload
    def fcmpe(self, op0: S | D, op1: _Imm | float, /) -> None: ...
    @overload
    def fcmpe(self, op0: S, op1: S, /) -> None: ...
    @overload
    def fcsel(self, op0: D, op1: D, op2: D, op3: Cond, /) -> None:
        """Emit `fcsel` (4 operands)."""
    @overload
    def fcsel(self, op0: S, op1: S, op2: S, op3: Cond, /) -> None: ...
    @overload
    def fcvt(self, op0: D, op1: S, /) -> None:
        """Emit `fcvt` (2 operands)."""
    @overload
    def fcvt(self, op0: S, op1: D, /) -> None: ...
    def fcvtas(self, op0: X | W, op1: S | D, /) -> None:
        """Emit `fcvtas` (2 operands)."""
    def fcvtau(self, op0: X | W, op1: S | D, /) -> None:
        """Emit `fcvtau` (2 operands)."""
    def fcvtms(self, op0: X | W, op1: S | D, /) -> None:
        """Emit `fcvtms` (2 operands)."""
    def fcvtmu(self, op0: X | W, op1: S | D, /) -> None:
        """Emit `fcvtmu` (2 operands)."""
    def fcvtns(self, op0: X | W, op1: S | D, /) -> None:
        """Emit `fcvtns` (2 operands)."""
    def fcvtnu(self, op0: X | W, op1: S | D, /) -> None:
        """Emit `fcvtnu` (2 operands)."""
    def fcvtps(self, op0: X | W, op1: S | D, /) -> None:
        """Emit `fcvtps` (2 operands)."""
    def fcvtpu(self, op0: X | W, op1: S | D, /) -> None:
        """Emit `fcvtpu` (2 operands)."""
    def fcvtzs(self, op0: X | W, op1: S | D, /) -> None:
        """Emit `fcvtzs` (2 operands)."""
    def fcvtzu(self, op0: X | W, op1: S | D, /) -> None:
        """Emit `fcvtzu` (2 operands)."""
    @overload
    def fdiv(self, op0: D, op1: D, op2: D, /) -> None:
        """Emit `fdiv` (3 operands)."""
    @overload
    def fdiv(self, op0: S, op1: S, op2: S, /) -> None: ...
    @overload
    def fmadd(self, op0: D, op1: D, op2: D, op3: D, /) -> None:
        """Emit `fmadd` (4 operands)."""
    @overload
    def fmadd(self, op0: S, op1: S, op2: S, op3: S, /) -> None: ...
    @overload
    def fmax(self, op0: D, op1: D, op2: D, /) -> None:
        """Emit `fmax` (3 operands)."""
    @overload
    def fmax(self, op0: S, op1: S, op2: S, /) -> None: ...
    @overload
    def fmaxnm(self, op0: D, op1: D, op2: D, /) -> None:
        """Emit `fmaxnm` (3 operands)."""
    @overload
    def fmaxnm(self, op0: S, op1: S, op2: S, /) -> None: ...
    @overload
    def fmin(self, op0: D, op1: D, op2: D, /) -> None:
        """Emit `fmin` (3 operands)."""
    @overload
    def fmin(self, op0: S, op1: S, op2: S, /) -> None: ...
    @overload
    def fminnm(self, op0: D, op1: D, op2: D, /) -> None:
        """Emit `fminnm` (3 operands)."""
    @overload
    def fminnm(self, op0: S, op1: S, op2: S, /) -> None: ...
    @overload
    def fmov(self, op0: X | D, op1: D, /) -> None:
        """Emit `fmov` (2 operands)."""
    @overload
    def fmov(self, op0: D, op1: X, /) -> None: ...
    @overload
    def fmov(self, op0: S | D, op1: _Imm | float, /) -> None: ...
    @overload
    def fmov(self, op0: W | S, op1: S, /) -> None: ...
    @overload
    def fmov(self, op0: S, op1: W, /) -> None: ...
    @overload
    def fmsub(self, op0: D, op1: D, op2: D, op3: D, /) -> None:
        """Emit `fmsub` (4 operands)."""
    @overload
    def fmsub(self, op0: S, op1: S, op2: S, op3: S, /) -> None: ...
    @overload
    def fmul(self, op0: D, op1: D, op2: D, /) -> None:
        """Emit `fmul` (3 operands)."""
    @overload
    def fmul(self, op0: S, op1: S, op2: S, /) -> None: ...
    @overload
    def fneg(self, op0: D, op1: D, /) -> None:
        """Emit `fneg` (2 operands)."""
    @overload
    def fneg(self, op0: S, op1: S, /) -> None: ...
    @overload
    def fnmadd(self, op0: D, op1: D, op2: D, op3: D, /) -> None:
        """Emit `fnmadd` (4 operands)."""
    @overload
    def fnmadd(self, op0: S, op1: S, op2: S, op3: S, /) -> None: ...
    @overload
    def fnmsub(self, op0: D, op1: D, op2: D, op3: D, /) -> None:
        """Emit `fnmsub` (4 operands)."""
    @overload
    def fnmsub(self, op0: S, op1: S, op2: S, op3: S, /) -> None: ...
    @overload
    def fnmul(self, op0: D, op1: D, op2: D, /) -> None:
        """Emit `fnmul` (3 operands)."""
    @overload
    def fnmul(self, op0: S, op1: S, op2: S, /) -> None: ...
    @overload
    def frinta(self, op0: D, op1: D, /) -> None:
        """Emit `frinta` (2 operands)."""
    @overload
    def frinta(self, op0: S, op1: S, /) -> None: ...
    @overload
    def frinti(self, op0: D, op1: D, /) -> None:
        """Emit `frinti` (2 operands)."""
    @overload
    def frinti(self, op0: S, op1: S, /) -> None: ...
    @overload
    def frintm(self, op0: D, op1: D, /) -> None:
        """Emit `frintm` (2 operands)."""
    @overload
    def frintm(self, op0: S, op1: S, /) -> None: ...
    @overload
    def frintn(self, op0: D, op1: D, /) -> None:
        """Emit `frintn` (2 operands)."""
    @overload
    def frintn(self, op0: S, op1: S, /) -> None: ...
    @overload
    def frintp(self, op0: D, op1: D, /) -> None:
        """Emit `frintp` (2 operands)."""
    @overload
    def frintp(self, op0: S, op1: S, /) -> None: ...
    @overload
    def frintx(self, op0: D, op1: D, /) -> None:
        """Emit `frintx` (2 operands)."""
    @overload
    def frintx(self, op0: S, op1: S, /) -> None: ...
    @overload
    def frintz(self, op0: D, op1: D, /) -> None:
        """Emit `frintz` (2 operands)."""
    @overload
    def frintz(self, op0: S, op1: S, /) -> None: ...
    @overload
    def fsqrt(self, op0: D, op1: D, /) -> None:
        """Emit `fsqrt` (2 operands)."""
    @overload
    def fsqrt(self, op0: S, op1: S, /) -> None: ...
    @overload
    def fsub(self, op0: D, op1: D, op2: D, /) -> None:
        """Emit `fsub` (3 operands)."""
    @overload
    def fsub(self, op0: S, op1: S, op2: S, /) -> None: ...
    @overload
    def ldp(self, op0: D, op1: D, op2: MemExpr, /) -> None:
        """Emit `ldp` (any number of operands)."""
    @overload
    def ldp(self, op0: Q, op1: Q, op2: MemExpr, /) -> None: ...
    @overload
    def ldp(self, op0: S, op1: S, op2: MemExpr, /) -> None: ...
    @overload
    def ldp(self, op0: W, op1: W, op2: MemExpr, /) -> None: ...
    @overload
    def ldp(self, op0: X, op1: X, op2: MemExpr, /) -> None: ...
    def ldpsw(self, op0: X, op1: X, op2: MemExpr, /) -> None:
        """Emit `ldpsw` (any number of operands)."""
    def ldr(self, op0: X | W | S | D, op1: MemExpr | _Target, /) -> None:
        """Emit `ldr` (any number of operands)."""
    def ldrb(self, op0: W, op1: MemExpr, /) -> None:
        """Emit `ldrb` (any number of operands)."""
    def ldrh(self, op0: W, op1: MemExpr, /) -> None:
        """Emit `ldrh` (any number of operands)."""
    def ldrsb(self, op0: X | W, op1: MemExpr, /) -> None:
        """Emit `ldrsb` (any number of operands)."""
    def ldrsh(self, op0: X | W, op1: MemExpr, /) -> None:
        """Emit `ldrsh` (any number of operands)."""
    def ldrsw(self, op0: X, op1: MemExpr | _Target, /) -> None:
        """Emit `ldrsw` (any number of operands)."""
    @overload
    def lsl(self, op0: W, op1: W, op2: W | _Imm, /) -> None:
        """Emit `lsl` (3 operands)."""
    @overload
    def lsl(self, op0: X, op1: X, op2: X | _Imm, /) -> None: ...
    @overload
    def lsr(self, op0: W, op1: W, op2: W | _Imm, /) -> None:
        """Emit `lsr` (3 operands)."""
    @overload
    def lsr(self, op0: X, op1: X, op2: X | _Imm, /) -> None: ...
    @overload
    def madd(self, op0: W, op1: W, op2: W, op3: W, /) -> None:
        """Emit `madd` (4 operands)."""
    @overload
    def madd(self, op0: X, op1: X, op2: X, op3: X, /) -> None: ...
    @overload
    def mneg(self, op0: W, op1: W, op2: W, /) -> None:
        """Emit `mneg` (3 operands)."""
    @overload
    def mneg(self, op0: X, op1: X, op2: X, /) -> None: ...
    @overload
    def mov(self, op0: X | Sp, op1: X | Sp, /) -> None:
        """Emit `mov` (2 or 3 operands)."""
    @overload
    def mov(self, op0: X | W | Sp, op1: _Imm, /) -> None: ...
    @overload
    def mov(self, op0: W, op1: W | RegMod[W], /) -> None: ...
    @overload
    def mov(self, op0: X, op1: RegMod[X], /) -> None: ...
    @overload
    def mov(self, op0: W, op1: W, op2: Mod, /) -> None: ...
    @overload
    def mov(self, op0: X, op1: X, op2: Mod, /) -> None: ...
    @overload
    def movk(self, op0: X | W, op1: _Imm, /, *, lsl: int | None = None) -> None:
        """Emit `movk` (2 or 3 operands)."""
    @overload
    def movk(self, op0: X | W, op1: _Imm, op2: Mod, /, *, lsl: int | None = None) -> None: ...
    @overload
    def movn(self, op0: X | W, op1: _Imm, /, *, lsl: int | None = None) -> None:
        """Emit `movn` (2 or 3 operands)."""
    @overload
    def movn(self, op0: X | W, op1: _Imm, op2: Mod, /, *, lsl: int | None = None) -> None: ...
    @overload
    def movz(self, op0: X | W, op1: _Imm, /, *, lsl: int | None = None) -> None:
        """Emit `movz` (2 or 3 operands)."""
    @overload
    def movz(self, op0: X | W, op1: _Imm, op2: Mod, /, *, lsl: int | None = None) -> None: ...
    @overload
    def msub(self, op0: W, op1: W, op2: W, op3: W, /) -> None:
        """Emit `msub` (4 operands)."""
    @overload
    def msub(self, op0: X, op1: X, op2: X, op3: X, /) -> None: ...
    @overload
    def mul(self, op0: W, op1: W, op2: W, /) -> None:
        """Emit `mul` (3 operands)."""
    @overload
    def mul(self, op0: X, op1: X, op2: X, /) -> None: ...
    @overload
    def mvn(self, op0: W, op1: W | RegMod[W], /) -> None:
        """Emit `mvn` (2 or 3 operands)."""
    @overload
    def mvn(self, op0: X, op1: X | RegMod[X], /) -> None: ...
    @overload
    def mvn(self, op0: W, op1: W, op2: Mod, /) -> None: ...
    @overload
    def mvn(self, op0: X, op1: X, op2: Mod, /) -> None: ...
    @overload
    def neg(self, op0: W, op1: W | RegMod[W], /) -> None:
        """Emit `neg` (2 or 3 operands)."""
    @overload
    def neg(self, op0: X, op1: X | RegMod[X], /) -> None: ...
    @overload
    def neg(self, op0: W, op1: W, op2: Mod, /) -> None: ...
    @overload
    def neg(self, op0: X, op1: X, op2: Mod, /) -> None: ...
    @overload
    def negs(self, op0: W, op1: W | RegMod[W], /) -> None:
        """Emit `negs` (2 or 3 operands)."""
    @overload
    def negs(self, op0: X, op1: X | RegMod[X], /) -> None: ...
    @overload
    def negs(self, op0: W, op1: W, op2: Mod, /) -> None: ...
    @overload
    def negs(self, op0: X, op1: X, op2: Mod, /) -> None: ...
    @overload
    def ngc(self, op0: W, op1: W, /) -> None:
        """Emit `ngc` (2 operands)."""
    @overload
    def ngc(self, op0: X, op1: X, /) -> None: ...
    @overload
    def ngcs(self, op0: W, op1: W, /) -> None:
        """Emit `ngcs` (2 operands)."""
    @overload
    def ngcs(self, op0: X, op1: X, /) -> None: ...
    def nop(self) -> None:
        """Emit `nop` (0 operands)."""
    @overload
    def orn(self, op0: W, op1: W, op2: W | RegMod[W], /) -> None:
        """Emit `orn` (3 or 4 operands)."""
    @overload
    def orn(self, op0: X, op1: X, op2: X | RegMod[X], /) -> None: ...
    @overload
    def orn(self, op0: W, op1: W, op2: W, op3: Mod, /) -> None: ...
    @overload
    def orn(self, op0: X, op1: X, op2: X, op3: Mod, /) -> None: ...
    @overload
    def orr(self, op0: X | Sp, op1: X, op2: _Imm, /) -> None:
        """Emit `orr` (3 or 4 operands)."""
    @overload
    def orr(self, op0: W, op1: W, op2: W | RegMod[W] | _Imm, /) -> None: ...
    @overload
    def orr(self, op0: X, op1: X, op2: X | RegMod[X], /) -> None: ...
    @overload
    def orr(self, op0: W, op1: W, op2: W, op3: Mod, /) -> None: ...
    @overload
    def orr(self, op0: X, op1: X, op2: X, op3: Mod, /) -> None: ...
    def paciasp(self) -> None:
        """Emit `paciasp` (0 operands)."""
    def pacibsp(self) -> None:
        """Emit `pacibsp` (0 operands)."""
    @overload
    def rbit(self, op0: W, op1: W, /) -> None:
        """Emit `rbit` (2 operands)."""
    @overload
    def rbit(self, op0: X, op1: X, /) -> None: ...
    @overload
    def ret(self) -> None:
        """Emit `ret` (0 or 1 operands)."""
    @overload
    def ret(self, op0: X, /) -> None: ...
    def retaa(self) -> None:
        """Emit `retaa` (0 operands)."""
    def retab(self) -> None:
        """Emit `retab` (0 operands)."""
    @overload
    def rev(self, op0: W, op1: W, /) -> None:
        """Emit `rev` (2 operands)."""
    @overload
    def rev(self, op0: X, op1: X, /) -> None: ...
    @overload
    def rev16(self, op0: W, op1: W, /) -> None:
        """Emit `rev16` (2 operands)."""
    @overload
    def rev16(self, op0: X, op1: X, /) -> None: ...
    def rev32(self, op0: X, op1: X, /) -> None:
        """Emit `rev32` (2 operands)."""
    @overload
    def ror(self, op0: W, op1: W, op2: W | _Imm, /) -> None:
        """Emit `ror` (3 operands)."""
    @overload
    def ror(self, op0: X, op1: X, op2: X | _Imm, /) -> None: ...
    @overload
    def sbc(self, op0: W, op1: W, op2: W, /) -> None:
        """Emit `sbc` (3 operands)."""
    @overload
    def sbc(self, op0: X, op1: X, op2: X, /) -> None: ...
    @overload
    def sbcs(self, op0: W, op1: W, op2: W, /) -> None:
        """Emit `sbcs` (3 operands)."""
    @overload
    def sbcs(self, op0: X, op1: X, op2: X, /) -> None: ...
    @overload
    def sbfiz(self, op0: W, op1: W, op2: _Imm, op3: _Imm, /) -> None:
        """Emit `sbfiz` (4 operands)."""
    @overload
    def sbfiz(self, op0: X, op1: X, op2: _Imm, op3: _Imm, /) -> None: ...
    @overload
    def sbfm(self, op0: W, op1: W, op2: _Imm, op3: _Imm, /) -> None:
        """Emit `sbfm` (4 operands)."""
    @overload
    def sbfm(self, op0: X, op1: X, op2: _Imm, op3: _Imm, /) -> None: ...
    @overload
    def sbfx(self, op0: W, op1: W, op2: _Imm, op3: _Imm, /) -> None:
        """Emit `sbfx` (4 operands)."""
    @overload
    def sbfx(self, op0: X, op1: X, op2: _Imm, op3: _Imm, /) -> None: ...
    def scvtf(self, op0: S | D, op1: X | W, /) -> None:
        """Emit `scvtf` (2 operands)."""
    @overload
    def sdiv(self, op0: W, op1: W, op2: W, /) -> None:
        """Emit `sdiv` (3 operands)."""
    @overload
    def sdiv(self, op0: X, op1: X, op2: X, /) -> None: ...
    def smaddl(self, op0: X, op1: W, op2: W, op3: X, /) -> None:
        """Emit `smaddl` (4 operands)."""
    def smnegl(self, op0: X, op1: W, op2: W, /) -> None:
        """Emit `smnegl` (3 operands)."""
    def smsubl(self, op0: X, op1: W, op2: W, op3: X, /) -> None:
        """Emit `smsubl` (4 operands)."""
    def smulh(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `smulh` (3 operands)."""
    def smull(self, op0: X, op1: W, op2: W, /) -> None:
        """Emit `smull` (3 operands)."""
    @overload
    def stp(self, op0: D, op1: D, op2: MemExpr, /) -> None:
        """Emit `stp` (any number of operands)."""
    @overload
    def stp(self, op0: Q, op1: Q, op2: MemExpr, /) -> None: ...
    @overload
    def stp(self, op0: S, op1: S, op2: MemExpr, /) -> None: ...
    @overload
    def stp(self, op0: W, op1: W, op2: MemExpr, /) -> None: ...
    @overload
    def stp(self, op0: X, op1: X, op2: MemExpr, /) -> None: ...
    def str(self, op0: X | W | S | D, op1: MemExpr, /) -> None:
        """Emit `str` (any number of operands)."""
    def str_(self, op0: X | W | S | D, op1: MemExpr, /) -> None:
        """Emit `str` (any number of operands)."""
    def strb(self, op0: W, op1: MemExpr, /) -> None:
        """Emit `strb` (any number of operands)."""
    def strh(self, op0: W, op1: MemExpr, /) -> None:
        """Emit `strh` (any number of operands)."""
    @overload
    def sub(self, op0: X | Sp, op1: X | Sp, op2: X | RegMod[X] | RegMod[W] | _Imm, /) -> None:
        """Emit `sub` (3 or 4 operands)."""
    @overload
    def sub(self, op0: W, op1: W, op2: W | RegMod[W] | _Imm, /) -> None: ...
    @overload
    def sub(self, op0: X | Sp, op1: X | Sp, op2: X | W, op3: Mod, /) -> None: ...
    @overload
    def sub(self, op0: W, op1: W, op2: W, op3: Mod, /) -> None: ...
    @overload
    def subs(self, op0: W, op1: W, op2: W | RegMod[W] | _Imm, /) -> None:
        """Emit `subs` (3 or 4 operands)."""
    @overload
    def subs(self, op0: X, op1: X | Sp, op2: X | RegMod[X] | RegMod[W] | _Imm, /) -> None: ...
    @overload
    def subs(self, op0: W, op1: W, op2: W, op3: Mod, /) -> None: ...
    @overload
    def subs(self, op0: X, op1: X | Sp, op2: X | W, op3: Mod, /) -> None: ...
    @overload
    def sxtb(self, op0: W, op1: W, /) -> None:
        """Emit `sxtb` (2 operands)."""
    @overload
    def sxtb(self, op0: X, op1: X, /) -> None: ...
    @overload
    def sxth(self, op0: W, op1: W, /) -> None:
        """Emit `sxth` (2 operands)."""
    @overload
    def sxth(self, op0: X, op1: X, /) -> None: ...
    def sxtw(self, op0: X, op1: W, /) -> None:
        """Emit `sxtw` (2 operands)."""
    def tbnz(self, op0: X | W, op1: _Imm, op2: _Target, /) -> None:
        """Emit `tbnz` (3 operands)."""
    def tbz(self, op0: X | W, op1: _Imm, op2: _Target, /) -> None:
        """Emit `tbz` (3 operands)."""
    @overload
    def tst(self, op0: W, op1: W | RegMod[W], /) -> None:
        """Emit `tst` (2 or 3 operands)."""
    @overload
    def tst(self, op0: X | W, op1: _Imm, /) -> None: ...
    @overload
    def tst(self, op0: X, op1: X | RegMod[X], /) -> None: ...
    @overload
    def tst(self, op0: W, op1: W, op2: Mod, /) -> None: ...
    @overload
    def tst(self, op0: X, op1: X, op2: Mod, /) -> None: ...
    @overload
    def ubfiz(self, op0: W, op1: W, op2: _Imm, op3: _Imm, /) -> None:
        """Emit `ubfiz` (4 operands)."""
    @overload
    def ubfiz(self, op0: X, op1: X, op2: _Imm, op3: _Imm, /) -> None: ...
    @overload
    def ubfm(self, op0: W, op1: W, op2: _Imm, op3: _Imm, /) -> None:
        """Emit `ubfm` (4 operands)."""
    @overload
    def ubfm(self, op0: X, op1: X, op2: _Imm, op3: _Imm, /) -> None: ...
    @overload
    def ubfx(self, op0: W, op1: W, op2: _Imm, op3: _Imm, /) -> None:
        """Emit `ubfx` (4 operands)."""
    @overload
    def ubfx(self, op0: X, op1: X, op2: _Imm, op3: _Imm, /) -> None: ...
    def ucvtf(self, op0: S | D, op1: X | W, /) -> None:
        """Emit `ucvtf` (2 operands)."""
    @overload
    def udiv(self, op0: W, op1: W, op2: W, /) -> None:
        """Emit `udiv` (3 operands)."""
    @overload
    def udiv(self, op0: X, op1: X, op2: X, /) -> None: ...
    def umaddl(self, op0: X, op1: W, op2: W, op3: X, /) -> None:
        """Emit `umaddl` (4 operands)."""
    def umnegl(self, op0: X, op1: W, op2: W, /) -> None:
        """Emit `umnegl` (3 operands)."""
    def umsubl(self, op0: X, op1: W, op2: W, op3: X, /) -> None:
        """Emit `umsubl` (4 operands)."""
    def umulh(self, op0: X, op1: X, op2: X, /) -> None:
        """Emit `umulh` (3 operands)."""
    def umull(self, op0: X, op1: W, op2: W, /) -> None:
        """Emit `umull` (3 operands)."""
    def uxtb(self, op0: W, op1: W, /) -> None:
        """Emit `uxtb` (2 operands)."""
    def uxth(self, op0: W, op1: W, /) -> None:
        """Emit `uxth` (2 operands)."""

@overload
def adc(op0: W, op1: W, op2: W, /, *, asm: Assembler | None = None) -> None:
    """Emit `adc` (3 operands)."""
@overload
def adc(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None: ...
@overload
def adcs(op0: W, op1: W, op2: W, /, *, asm: Assembler | None = None) -> None:
    """Emit `adcs` (3 operands)."""
@overload
def adcs(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None: ...
@overload
def add(op0: X | Sp, op1: X | Sp, op2: X | RegMod[X] | RegMod[W] | _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `add` (3 or 4 operands)."""
@overload
def add(op0: W, op1: W, op2: W | RegMod[W] | _Imm, /, *, asm: Assembler | None = None) -> None: ...
@overload
def add(op0: X | Sp, op1: X | Sp, op2: X | W, op3: Mod, /, *, asm: Assembler | None = None) -> None: ...
@overload
def add(op0: W, op1: W, op2: W, op3: Mod, /, *, asm: Assembler | None = None) -> None: ...
@overload
def adds(op0: W, op1: W, op2: W | RegMod[W] | _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `adds` (3 or 4 operands)."""
@overload
def adds(op0: X, op1: X | Sp, op2: X | RegMod[X] | RegMod[W] | _Imm, /, *, asm: Assembler | None = None) -> None: ...
@overload
def adds(op0: W, op1: W, op2: W, op3: Mod, /, *, asm: Assembler | None = None) -> None: ...
@overload
def adds(op0: X, op1: X | Sp, op2: X | W, op3: Mod, /, *, asm: Assembler | None = None) -> None: ...
def adr(op0: X, op1: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `adr` (2 operands)."""
def adrp(op0: X, op1: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `adrp` (2 operands)."""
@overload
def and_(op0: X | Sp, op1: X, op2: _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `and` (3 or 4 operands)."""
@overload
def and_(op0: W, op1: W, op2: W | RegMod[W] | _Imm, /, *, asm: Assembler | None = None) -> None: ...
@overload
def and_(op0: X, op1: X, op2: X | RegMod[X], /, *, asm: Assembler | None = None) -> None: ...
@overload
def and_(op0: W, op1: W, op2: W, op3: Mod, /, *, asm: Assembler | None = None) -> None: ...
@overload
def and_(op0: X, op1: X, op2: X, op3: Mod, /, *, asm: Assembler | None = None) -> None: ...
@overload
def ands(op0: W, op1: W, op2: W | RegMod[W] | _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `ands` (3 or 4 operands)."""
@overload
def ands(op0: X, op1: X, op2: X | RegMod[X] | _Imm, /, *, asm: Assembler | None = None) -> None: ...
@overload
def ands(op0: W, op1: W, op2: W, op3: Mod, /, *, asm: Assembler | None = None) -> None: ...
@overload
def ands(op0: X, op1: X, op2: X, op3: Mod, /, *, asm: Assembler | None = None) -> None: ...
@overload
def asr(op0: W, op1: W, op2: W | _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `asr` (3 operands)."""
@overload
def asr(op0: X, op1: X, op2: X | _Imm, /, *, asm: Assembler | None = None) -> None: ...
def autiasp(*, asm: Assembler | None = None) -> None:
    """Emit `autiasp` (0 operands)."""
def autibsp(*, asm: Assembler | None = None) -> None:
    """Emit `autibsp` (0 operands)."""
b: _b
def bal(op0: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `b.al` (1 operands)."""
def bcc(op0: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `b.cc` (1 operands)."""
def bcs(op0: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `b.cs` (1 operands)."""
def beq(op0: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `b.eq` (1 operands)."""
@overload
def bfi(op0: W, op1: W, op2: _Imm, op3: _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `bfi` (4 operands)."""
@overload
def bfi(op0: X, op1: X, op2: _Imm, op3: _Imm, /, *, asm: Assembler | None = None) -> None: ...
@overload
def bfm(op0: W, op1: W, op2: _Imm, op3: _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `bfm` (4 operands)."""
@overload
def bfm(op0: X, op1: X, op2: _Imm, op3: _Imm, /, *, asm: Assembler | None = None) -> None: ...
@overload
def bfxil(op0: W, op1: W, op2: _Imm, op3: _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `bfxil` (4 operands)."""
@overload
def bfxil(op0: X, op1: X, op2: _Imm, op3: _Imm, /, *, asm: Assembler | None = None) -> None: ...
def bge(op0: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `b.ge` (1 operands)."""
def bgt(op0: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `b.gt` (1 operands)."""
def bhi(op0: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `b.hi` (1 operands)."""
def bhs(op0: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `b.hs` (1 operands)."""
@overload
def bic(op0: W, op1: W, op2: W | RegMod[W], /, *, asm: Assembler | None = None) -> None:
    """Emit `bic` (3 or 4 operands)."""
@overload
def bic(op0: X, op1: X, op2: X | RegMod[X], /, *, asm: Assembler | None = None) -> None: ...
@overload
def bic(op0: W, op1: W, op2: W, op3: Mod, /, *, asm: Assembler | None = None) -> None: ...
@overload
def bic(op0: X, op1: X, op2: X, op3: Mod, /, *, asm: Assembler | None = None) -> None: ...
@overload
def bics(op0: W, op1: W, op2: W | RegMod[W], /, *, asm: Assembler | None = None) -> None:
    """Emit `bics` (3 or 4 operands)."""
@overload
def bics(op0: X, op1: X, op2: X | RegMod[X], /, *, asm: Assembler | None = None) -> None: ...
@overload
def bics(op0: W, op1: W, op2: W, op3: Mod, /, *, asm: Assembler | None = None) -> None: ...
@overload
def bics(op0: X, op1: X, op2: X, op3: Mod, /, *, asm: Assembler | None = None) -> None: ...
def bl(op0: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `bl` (1 operands)."""
def ble(op0: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `b.le` (1 operands)."""
def blo(op0: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `b.lo` (1 operands)."""
def blr(op0: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `blr` (1 operands)."""
def blraaz(op0: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `blraaz` (1 operands)."""
def blrabz(op0: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `blrabz` (1 operands)."""
def bls(op0: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `b.ls` (1 operands)."""
def blt(op0: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `b.lt` (1 operands)."""
def bmi(op0: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `b.mi` (1 operands)."""
def bne(op0: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `b.ne` (1 operands)."""
def bpl(op0: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `b.pl` (1 operands)."""
def br(op0: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `br` (1 operands)."""
def braa(op0: X, op1: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `braa` (2 operands)."""
def braaz(op0: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `braaz` (1 operands)."""
def brab(op0: X, op1: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `brab` (2 operands)."""
def brabz(op0: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `brabz` (1 operands)."""
@overload
def brk(*, asm: Assembler | None = None) -> None:
    """Emit `brk` (0 or 1 operands)."""
@overload
def brk(op0: _Imm, /, *, asm: Assembler | None = None) -> None: ...
def bti(op0: _Bti, /, *, asm: Assembler | None = None) -> None:
    """Emit `bti` (1 operands)."""
def bvc(op0: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `b.vc` (1 operands)."""
def bvs(op0: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `b.vs` (1 operands)."""
def cbnz(op0: X | W, op1: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `cbnz` (2 operands)."""
def cbz(op0: X | W, op1: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `cbz` (2 operands)."""
@overload
def ccmn(op0: W, op1: W, op2: _Imm, op3: Cond, /, *, asm: Assembler | None = None) -> None:
    """Emit `ccmn` (4 operands)."""
@overload
def ccmn(op0: X | W, op1: _Imm, op2: _Imm, op3: Cond, /, *, asm: Assembler | None = None) -> None: ...
@overload
def ccmn(op0: X, op1: X, op2: _Imm, op3: Cond, /, *, asm: Assembler | None = None) -> None: ...
@overload
def ccmp(op0: W, op1: W, op2: _Imm, op3: Cond, /, *, asm: Assembler | None = None) -> None:
    """Emit `ccmp` (4 operands)."""
@overload
def ccmp(op0: X | W, op1: _Imm, op2: _Imm, op3: Cond, /, *, asm: Assembler | None = None) -> None: ...
@overload
def ccmp(op0: X, op1: X, op2: _Imm, op3: Cond, /, *, asm: Assembler | None = None) -> None: ...
@overload
def cinc(op0: W, op1: W, op2: Cond, /, *, asm: Assembler | None = None) -> None:
    """Emit `cinc` (3 operands)."""
@overload
def cinc(op0: X, op1: X, op2: Cond, /, *, asm: Assembler | None = None) -> None: ...
@overload
def cinv(op0: W, op1: W, op2: Cond, /, *, asm: Assembler | None = None) -> None:
    """Emit `cinv` (3 operands)."""
@overload
def cinv(op0: X, op1: X, op2: Cond, /, *, asm: Assembler | None = None) -> None: ...
@overload
def cls(op0: W, op1: W, /, *, asm: Assembler | None = None) -> None:
    """Emit `cls` (2 operands)."""
@overload
def cls(op0: X, op1: X, /, *, asm: Assembler | None = None) -> None: ...
@overload
def clz(op0: W, op1: W, /, *, asm: Assembler | None = None) -> None:
    """Emit `clz` (2 operands)."""
@overload
def clz(op0: X, op1: X, /, *, asm: Assembler | None = None) -> None: ...
@overload
def cmn(op0: X | W | Sp, op1: RegMod[W] | _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `cmn` (2 or 3 operands)."""
@overload
def cmn(op0: X | Sp, op1: X | RegMod[X], /, *, asm: Assembler | None = None) -> None: ...
@overload
def cmn(op0: W, op1: W, /, *, asm: Assembler | None = None) -> None: ...
@overload
def cmn(op0: X | W | Sp, op1: W, op2: Mod, /, *, asm: Assembler | None = None) -> None: ...
@overload
def cmn(op0: X | Sp, op1: X, op2: Mod, /, *, asm: Assembler | None = None) -> None: ...
@overload
def cmp(op0: X | W | Sp, op1: RegMod[W] | _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `cmp` (2 or 3 operands)."""
@overload
def cmp(op0: X | Sp, op1: X | RegMod[X], /, *, asm: Assembler | None = None) -> None: ...
@overload
def cmp(op0: W, op1: W, /, *, asm: Assembler | None = None) -> None: ...
@overload
def cmp(op0: X | W | Sp, op1: W, op2: Mod, /, *, asm: Assembler | None = None) -> None: ...
@overload
def cmp(op0: X | Sp, op1: X, op2: Mod, /, *, asm: Assembler | None = None) -> None: ...
@overload
def cneg(op0: W, op1: W, op2: Cond, /, *, asm: Assembler | None = None) -> None:
    """Emit `cneg` (3 operands)."""
@overload
def cneg(op0: X, op1: X, op2: Cond, /, *, asm: Assembler | None = None) -> None: ...
@overload
def csel(op0: W, op1: W, op2: W, op3: Cond, /, *, asm: Assembler | None = None) -> None:
    """Emit `csel` (4 operands)."""
@overload
def csel(op0: X, op1: X, op2: X, op3: Cond, /, *, asm: Assembler | None = None) -> None: ...
def cset(op0: X | W, op1: Cond, /, *, asm: Assembler | None = None) -> None:
    """Emit `cset` (2 operands)."""
def csetm(op0: X | W, op1: Cond, /, *, asm: Assembler | None = None) -> None:
    """Emit `csetm` (2 operands)."""
@overload
def csinc(op0: W, op1: W, op2: W, op3: Cond, /, *, asm: Assembler | None = None) -> None:
    """Emit `csinc` (4 operands)."""
@overload
def csinc(op0: X, op1: X, op2: X, op3: Cond, /, *, asm: Assembler | None = None) -> None: ...
@overload
def csinv(op0: W, op1: W, op2: W, op3: Cond, /, *, asm: Assembler | None = None) -> None:
    """Emit `csinv` (4 operands)."""
@overload
def csinv(op0: X, op1: X, op2: X, op3: Cond, /, *, asm: Assembler | None = None) -> None: ...
@overload
def csneg(op0: W, op1: W, op2: W, op3: Cond, /, *, asm: Assembler | None = None) -> None:
    """Emit `csneg` (4 operands)."""
@overload
def csneg(op0: X, op1: X, op2: X, op3: Cond, /, *, asm: Assembler | None = None) -> None: ...
@overload
def eon(op0: W, op1: W, op2: W | RegMod[W], /, *, asm: Assembler | None = None) -> None:
    """Emit `eon` (3 or 4 operands)."""
@overload
def eon(op0: X, op1: X, op2: X | RegMod[X], /, *, asm: Assembler | None = None) -> None: ...
@overload
def eon(op0: W, op1: W, op2: W, op3: Mod, /, *, asm: Assembler | None = None) -> None: ...
@overload
def eon(op0: X, op1: X, op2: X, op3: Mod, /, *, asm: Assembler | None = None) -> None: ...
@overload
def eor(op0: X | Sp, op1: X, op2: _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `eor` (3 or 4 operands)."""
@overload
def eor(op0: W, op1: W, op2: W | RegMod[W] | _Imm, /, *, asm: Assembler | None = None) -> None: ...
@overload
def eor(op0: X, op1: X, op2: X | RegMod[X], /, *, asm: Assembler | None = None) -> None: ...
@overload
def eor(op0: W, op1: W, op2: W, op3: Mod, /, *, asm: Assembler | None = None) -> None: ...
@overload
def eor(op0: X, op1: X, op2: X, op3: Mod, /, *, asm: Assembler | None = None) -> None: ...
@overload
def extr(op0: W, op1: W, op2: W, op3: _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `extr` (4 operands)."""
@overload
def extr(op0: X, op1: X, op2: X, op3: _Imm, /, *, asm: Assembler | None = None) -> None: ...
@overload
def fabs(op0: D, op1: D, /, *, asm: Assembler | None = None) -> None:
    """Emit `fabs` (2 operands)."""
@overload
def fabs(op0: S, op1: S, /, *, asm: Assembler | None = None) -> None: ...
@overload
def fadd(op0: D, op1: D, op2: D, /, *, asm: Assembler | None = None) -> None:
    """Emit `fadd` (3 operands)."""
@overload
def fadd(op0: S, op1: S, op2: S, /, *, asm: Assembler | None = None) -> None: ...
@overload
def fccmp(op0: D, op1: D, op2: _Imm, op3: Cond, /, *, asm: Assembler | None = None) -> None:
    """Emit `fccmp` (4 operands)."""
@overload
def fccmp(op0: S, op1: S, op2: _Imm, op3: Cond, /, *, asm: Assembler | None = None) -> None: ...
@overload
def fccmpe(op0: D, op1: D, op2: _Imm, op3: Cond, /, *, asm: Assembler | None = None) -> None:
    """Emit `fccmpe` (4 operands)."""
@overload
def fccmpe(op0: S, op1: S, op2: _Imm, op3: Cond, /, *, asm: Assembler | None = None) -> None: ...
@overload
def fcmp(op0: D, op1: D, /, *, asm: Assembler | None = None) -> None:
    """Emit `fcmp` (2 operands)."""
@overload
def fcmp(op0: S | D, op1: _Imm | float, /, *, asm: Assembler | None = None) -> None: ...
@overload
def fcmp(op0: S, op1: S, /, *, asm: Assembler | None = None) -> None: ...
@overload
def fcmpe(op0: D, op1: D, /, *, asm: Assembler | None = None) -> None:
    """Emit `fcmpe` (2 operands)."""
@overload
def fcmpe(op0: S | D, op1: _Imm | float, /, *, asm: Assembler | None = None) -> None: ...
@overload
def fcmpe(op0: S, op1: S, /, *, asm: Assembler | None = None) -> None: ...
@overload
def fcsel(op0: D, op1: D, op2: D, op3: Cond, /, *, asm: Assembler | None = None) -> None:
    """Emit `fcsel` (4 operands)."""
@overload
def fcsel(op0: S, op1: S, op2: S, op3: Cond, /, *, asm: Assembler | None = None) -> None: ...
@overload
def fcvt(op0: D, op1: S, /, *, asm: Assembler | None = None) -> None:
    """Emit `fcvt` (2 operands)."""
@overload
def fcvt(op0: S, op1: D, /, *, asm: Assembler | None = None) -> None: ...
def fcvtas(op0: X | W, op1: S | D, /, *, asm: Assembler | None = None) -> None:
    """Emit `fcvtas` (2 operands)."""
def fcvtau(op0: X | W, op1: S | D, /, *, asm: Assembler | None = None) -> None:
    """Emit `fcvtau` (2 operands)."""
def fcvtms(op0: X | W, op1: S | D, /, *, asm: Assembler | None = None) -> None:
    """Emit `fcvtms` (2 operands)."""
def fcvtmu(op0: X | W, op1: S | D, /, *, asm: Assembler | None = None) -> None:
    """Emit `fcvtmu` (2 operands)."""
def fcvtns(op0: X | W, op1: S | D, /, *, asm: Assembler | None = None) -> None:
    """Emit `fcvtns` (2 operands)."""
def fcvtnu(op0: X | W, op1: S | D, /, *, asm: Assembler | None = None) -> None:
    """Emit `fcvtnu` (2 operands)."""
def fcvtps(op0: X | W, op1: S | D, /, *, asm: Assembler | None = None) -> None:
    """Emit `fcvtps` (2 operands)."""
def fcvtpu(op0: X | W, op1: S | D, /, *, asm: Assembler | None = None) -> None:
    """Emit `fcvtpu` (2 operands)."""
def fcvtzs(op0: X | W, op1: S | D, /, *, asm: Assembler | None = None) -> None:
    """Emit `fcvtzs` (2 operands)."""
def fcvtzu(op0: X | W, op1: S | D, /, *, asm: Assembler | None = None) -> None:
    """Emit `fcvtzu` (2 operands)."""
@overload
def fdiv(op0: D, op1: D, op2: D, /, *, asm: Assembler | None = None) -> None:
    """Emit `fdiv` (3 operands)."""
@overload
def fdiv(op0: S, op1: S, op2: S, /, *, asm: Assembler | None = None) -> None: ...
@overload
def fmadd(op0: D, op1: D, op2: D, op3: D, /, *, asm: Assembler | None = None) -> None:
    """Emit `fmadd` (4 operands)."""
@overload
def fmadd(op0: S, op1: S, op2: S, op3: S, /, *, asm: Assembler | None = None) -> None: ...
@overload
def fmax(op0: D, op1: D, op2: D, /, *, asm: Assembler | None = None) -> None:
    """Emit `fmax` (3 operands)."""
@overload
def fmax(op0: S, op1: S, op2: S, /, *, asm: Assembler | None = None) -> None: ...
@overload
def fmaxnm(op0: D, op1: D, op2: D, /, *, asm: Assembler | None = None) -> None:
    """Emit `fmaxnm` (3 operands)."""
@overload
def fmaxnm(op0: S, op1: S, op2: S, /, *, asm: Assembler | None = None) -> None: ...
@overload
def fmin(op0: D, op1: D, op2: D, /, *, asm: Assembler | None = None) -> None:
    """Emit `fmin` (3 operands)."""
@overload
def fmin(op0: S, op1: S, op2: S, /, *, asm: Assembler | None = None) -> None: ...
@overload
def fminnm(op0: D, op1: D, op2: D, /, *, asm: Assembler | None = None) -> None:
    """Emit `fminnm` (3 operands)."""
@overload
def fminnm(op0: S, op1: S, op2: S, /, *, asm: Assembler | None = None) -> None: ...
@overload
def fmov(op0: X | D, op1: D, /, *, asm: Assembler | None = None) -> None:
    """Emit `fmov` (2 operands)."""
@overload
def fmov(op0: D, op1: X, /, *, asm: Assembler | None = None) -> None: ...
@overload
def fmov(op0: S | D, op1: _Imm | float, /, *, asm: Assembler | None = None) -> None: ...
@overload
def fmov(op0: W | S, op1: S, /, *, asm: Assembler | None = None) -> None: ...
@overload
def fmov(op0: S, op1: W, /, *, asm: Assembler | None = None) -> None: ...
@overload
def fmsub(op0: D, op1: D, op2: D, op3: D, /, *, asm: Assembler | None = None) -> None:
    """Emit `fmsub` (4 operands)."""
@overload
def fmsub(op0: S, op1: S, op2: S, op3: S, /, *, asm: Assembler | None = None) -> None: ...
@overload
def fmul(op0: D, op1: D, op2: D, /, *, asm: Assembler | None = None) -> None:
    """Emit `fmul` (3 operands)."""
@overload
def fmul(op0: S, op1: S, op2: S, /, *, asm: Assembler | None = None) -> None: ...
@overload
def fneg(op0: D, op1: D, /, *, asm: Assembler | None = None) -> None:
    """Emit `fneg` (2 operands)."""
@overload
def fneg(op0: S, op1: S, /, *, asm: Assembler | None = None) -> None: ...
@overload
def fnmadd(op0: D, op1: D, op2: D, op3: D, /, *, asm: Assembler | None = None) -> None:
    """Emit `fnmadd` (4 operands)."""
@overload
def fnmadd(op0: S, op1: S, op2: S, op3: S, /, *, asm: Assembler | None = None) -> None: ...
@overload
def fnmsub(op0: D, op1: D, op2: D, op3: D, /, *, asm: Assembler | None = None) -> None:
    """Emit `fnmsub` (4 operands)."""
@overload
def fnmsub(op0: S, op1: S, op2: S, op3: S, /, *, asm: Assembler | None = None) -> None: ...
@overload
def fnmul(op0: D, op1: D, op2: D, /, *, asm: Assembler | None = None) -> None:
    """Emit `fnmul` (3 operands)."""
@overload
def fnmul(op0: S, op1: S, op2: S, /, *, asm: Assembler | None = None) -> None: ...
@overload
def frinta(op0: D, op1: D, /, *, asm: Assembler | None = None) -> None:
    """Emit `frinta` (2 operands)."""
@overload
def frinta(op0: S, op1: S, /, *, asm: Assembler | None = None) -> None: ...
@overload
def frinti(op0: D, op1: D, /, *, asm: Assembler | None = None) -> None:
    """Emit `frinti` (2 operands)."""
@overload
def frinti(op0: S, op1: S, /, *, asm: Assembler | None = None) -> None: ...
@overload
def frintm(op0: D, op1: D, /, *, asm: Assembler | None = None) -> None:
    """Emit `frintm` (2 operands)."""
@overload
def frintm(op0: S, op1: S, /, *, asm: Assembler | None = None) -> None: ...
@overload
def frintn(op0: D, op1: D, /, *, asm: Assembler | None = None) -> None:
    """Emit `frintn` (2 operands)."""
@overload
def frintn(op0: S, op1: S, /, *, asm: Assembler | None = None) -> None: ...
@overload
def frintp(op0: D, op1: D, /, *, asm: Assembler | None = None) -> None:
    """Emit `frintp` (2 operands)."""
@overload
def frintp(op0: S, op1: S, /, *, asm: Assembler | None = None) -> None: ...
@overload
def frintx(op0: D, op1: D, /, *, asm: Assembler | None = None) -> None:
    """Emit `frintx` (2 operands)."""
@overload
def frintx(op0: S, op1: S, /, *, asm: Assembler | None = None) -> None: ...
@overload
def frintz(op0: D, op1: D, /, *, asm: Assembler | None = None) -> None:
    """Emit `frintz` (2 operands)."""
@overload
def frintz(op0: S, op1: S, /, *, asm: Assembler | None = None) -> None: ...
@overload
def fsqrt(op0: D, op1: D, /, *, asm: Assembler | None = None) -> None:
    """Emit `fsqrt` (2 operands)."""
@overload
def fsqrt(op0: S, op1: S, /, *, asm: Assembler | None = None) -> None: ...
@overload
def fsub(op0: D, op1: D, op2: D, /, *, asm: Assembler | None = None) -> None:
    """Emit `fsub` (3 operands)."""
@overload
def fsub(op0: S, op1: S, op2: S, /, *, asm: Assembler | None = None) -> None: ...
@overload
def ldp(op0: D, op1: D, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
    """Emit `ldp` (any number of operands)."""
@overload
def ldp(op0: Q, op1: Q, op2: MemExpr, /, *, asm: Assembler | None = None) -> None: ...
@overload
def ldp(op0: S, op1: S, op2: MemExpr, /, *, asm: Assembler | None = None) -> None: ...
@overload
def ldp(op0: W, op1: W, op2: MemExpr, /, *, asm: Assembler | None = None) -> None: ...
@overload
def ldp(op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None: ...
def ldpsw(op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
    """Emit `ldpsw` (any number of operands)."""
def ldr(op0: X | W | S | D, op1: MemExpr | _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `ldr` (any number of operands)."""
def ldrb(op0: W, op1: MemExpr, /, *, asm: Assembler | None = None) -> None:
    """Emit `ldrb` (any number of operands)."""
def ldrh(op0: W, op1: MemExpr, /, *, asm: Assembler | None = None) -> None:
    """Emit `ldrh` (any number of operands)."""
def ldrsb(op0: X | W, op1: MemExpr, /, *, asm: Assembler | None = None) -> None:
    """Emit `ldrsb` (any number of operands)."""
def ldrsh(op0: X | W, op1: MemExpr, /, *, asm: Assembler | None = None) -> None:
    """Emit `ldrsh` (any number of operands)."""
def ldrsw(op0: X, op1: MemExpr | _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `ldrsw` (any number of operands)."""
@overload
def lsl(op0: W, op1: W, op2: W | _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `lsl` (3 operands)."""
@overload
def lsl(op0: X, op1: X, op2: X | _Imm, /, *, asm: Assembler | None = None) -> None: ...
@overload
def lsr(op0: W, op1: W, op2: W | _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `lsr` (3 operands)."""
@overload
def lsr(op0: X, op1: X, op2: X | _Imm, /, *, asm: Assembler | None = None) -> None: ...
@overload
def madd(op0: W, op1: W, op2: W, op3: W, /, *, asm: Assembler | None = None) -> None:
    """Emit `madd` (4 operands)."""
@overload
def madd(op0: X, op1: X, op2: X, op3: X, /, *, asm: Assembler | None = None) -> None: ...
@overload
def mneg(op0: W, op1: W, op2: W, /, *, asm: Assembler | None = None) -> None:
    """Emit `mneg` (3 operands)."""
@overload
def mneg(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None: ...
@overload
def mov(op0: X | Sp, op1: X | Sp, /, *, asm: Assembler | None = None) -> None:
    """Emit `mov` (2 or 3 operands)."""
@overload
def mov(op0: X | W | Sp, op1: _Imm, /, *, asm: Assembler | None = None) -> None: ...
@overload
def mov(op0: W, op1: W | RegMod[W], /, *, asm: Assembler | None = None) -> None: ...
@overload
def mov(op0: X, op1: RegMod[X], /, *, asm: Assembler | None = None) -> None: ...
@overload
def mov(op0: W, op1: W, op2: Mod, /, *, asm: Assembler | None = None) -> None: ...
@overload
def mov(op0: X, op1: X, op2: Mod, /, *, asm: Assembler | None = None) -> None: ...
@overload
def movk(op0: X | W, op1: _Imm, /, *, lsl: int | None = None, asm: Assembler | None = None) -> None:
    """Emit `movk` (2 or 3 operands)."""
@overload
def movk(op0: X | W, op1: _Imm, op2: Mod, /, *, lsl: int | None = None, asm: Assembler | None = None) -> None: ...
@overload
def movn(op0: X | W, op1: _Imm, /, *, lsl: int | None = None, asm: Assembler | None = None) -> None:
    """Emit `movn` (2 or 3 operands)."""
@overload
def movn(op0: X | W, op1: _Imm, op2: Mod, /, *, lsl: int | None = None, asm: Assembler | None = None) -> None: ...
@overload
def movz(op0: X | W, op1: _Imm, /, *, lsl: int | None = None, asm: Assembler | None = None) -> None:
    """Emit `movz` (2 or 3 operands)."""
@overload
def movz(op0: X | W, op1: _Imm, op2: Mod, /, *, lsl: int | None = None, asm: Assembler | None = None) -> None: ...
@overload
def msub(op0: W, op1: W, op2: W, op3: W, /, *, asm: Assembler | None = None) -> None:
    """Emit `msub` (4 operands)."""
@overload
def msub(op0: X, op1: X, op2: X, op3: X, /, *, asm: Assembler | None = None) -> None: ...
@overload
def mul(op0: W, op1: W, op2: W, /, *, asm: Assembler | None = None) -> None:
    """Emit `mul` (3 operands)."""
@overload
def mul(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None: ...
@overload
def mvn(op0: W, op1: W | RegMod[W], /, *, asm: Assembler | None = None) -> None:
    """Emit `mvn` (2 or 3 operands)."""
@overload
def mvn(op0: X, op1: X | RegMod[X], /, *, asm: Assembler | None = None) -> None: ...
@overload
def mvn(op0: W, op1: W, op2: Mod, /, *, asm: Assembler | None = None) -> None: ...
@overload
def mvn(op0: X, op1: X, op2: Mod, /, *, asm: Assembler | None = None) -> None: ...
@overload
def neg(op0: W, op1: W | RegMod[W], /, *, asm: Assembler | None = None) -> None:
    """Emit `neg` (2 or 3 operands)."""
@overload
def neg(op0: X, op1: X | RegMod[X], /, *, asm: Assembler | None = None) -> None: ...
@overload
def neg(op0: W, op1: W, op2: Mod, /, *, asm: Assembler | None = None) -> None: ...
@overload
def neg(op0: X, op1: X, op2: Mod, /, *, asm: Assembler | None = None) -> None: ...
@overload
def negs(op0: W, op1: W | RegMod[W], /, *, asm: Assembler | None = None) -> None:
    """Emit `negs` (2 or 3 operands)."""
@overload
def negs(op0: X, op1: X | RegMod[X], /, *, asm: Assembler | None = None) -> None: ...
@overload
def negs(op0: W, op1: W, op2: Mod, /, *, asm: Assembler | None = None) -> None: ...
@overload
def negs(op0: X, op1: X, op2: Mod, /, *, asm: Assembler | None = None) -> None: ...
@overload
def ngc(op0: W, op1: W, /, *, asm: Assembler | None = None) -> None:
    """Emit `ngc` (2 operands)."""
@overload
def ngc(op0: X, op1: X, /, *, asm: Assembler | None = None) -> None: ...
@overload
def ngcs(op0: W, op1: W, /, *, asm: Assembler | None = None) -> None:
    """Emit `ngcs` (2 operands)."""
@overload
def ngcs(op0: X, op1: X, /, *, asm: Assembler | None = None) -> None: ...
def nop(*, asm: Assembler | None = None) -> None:
    """Emit `nop` (0 operands)."""
@overload
def orn(op0: W, op1: W, op2: W | RegMod[W], /, *, asm: Assembler | None = None) -> None:
    """Emit `orn` (3 or 4 operands)."""
@overload
def orn(op0: X, op1: X, op2: X | RegMod[X], /, *, asm: Assembler | None = None) -> None: ...
@overload
def orn(op0: W, op1: W, op2: W, op3: Mod, /, *, asm: Assembler | None = None) -> None: ...
@overload
def orn(op0: X, op1: X, op2: X, op3: Mod, /, *, asm: Assembler | None = None) -> None: ...
@overload
def orr(op0: X | Sp, op1: X, op2: _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `orr` (3 or 4 operands)."""
@overload
def orr(op0: W, op1: W, op2: W | RegMod[W] | _Imm, /, *, asm: Assembler | None = None) -> None: ...
@overload
def orr(op0: X, op1: X, op2: X | RegMod[X], /, *, asm: Assembler | None = None) -> None: ...
@overload
def orr(op0: W, op1: W, op2: W, op3: Mod, /, *, asm: Assembler | None = None) -> None: ...
@overload
def orr(op0: X, op1: X, op2: X, op3: Mod, /, *, asm: Assembler | None = None) -> None: ...
def paciasp(*, asm: Assembler | None = None) -> None:
    """Emit `paciasp` (0 operands)."""
def pacibsp(*, asm: Assembler | None = None) -> None:
    """Emit `pacibsp` (0 operands)."""
@overload
def rbit(op0: W, op1: W, /, *, asm: Assembler | None = None) -> None:
    """Emit `rbit` (2 operands)."""
@overload
def rbit(op0: X, op1: X, /, *, asm: Assembler | None = None) -> None: ...
@overload
def ret(*, asm: Assembler | None = None) -> None:
    """Emit `ret` (0 or 1 operands)."""
@overload
def ret(op0: X, /, *, asm: Assembler | None = None) -> None: ...
def retaa(*, asm: Assembler | None = None) -> None:
    """Emit `retaa` (0 operands)."""
def retab(*, asm: Assembler | None = None) -> None:
    """Emit `retab` (0 operands)."""
@overload
def rev(op0: W, op1: W, /, *, asm: Assembler | None = None) -> None:
    """Emit `rev` (2 operands)."""
@overload
def rev(op0: X, op1: X, /, *, asm: Assembler | None = None) -> None: ...
@overload
def rev16(op0: W, op1: W, /, *, asm: Assembler | None = None) -> None:
    """Emit `rev16` (2 operands)."""
@overload
def rev16(op0: X, op1: X, /, *, asm: Assembler | None = None) -> None: ...
def rev32(op0: X, op1: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `rev32` (2 operands)."""
@overload
def ror(op0: W, op1: W, op2: W | _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `ror` (3 operands)."""
@overload
def ror(op0: X, op1: X, op2: X | _Imm, /, *, asm: Assembler | None = None) -> None: ...
@overload
def sbc(op0: W, op1: W, op2: W, /, *, asm: Assembler | None = None) -> None:
    """Emit `sbc` (3 operands)."""
@overload
def sbc(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None: ...
@overload
def sbcs(op0: W, op1: W, op2: W, /, *, asm: Assembler | None = None) -> None:
    """Emit `sbcs` (3 operands)."""
@overload
def sbcs(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None: ...
@overload
def sbfiz(op0: W, op1: W, op2: _Imm, op3: _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `sbfiz` (4 operands)."""
@overload
def sbfiz(op0: X, op1: X, op2: _Imm, op3: _Imm, /, *, asm: Assembler | None = None) -> None: ...
@overload
def sbfm(op0: W, op1: W, op2: _Imm, op3: _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `sbfm` (4 operands)."""
@overload
def sbfm(op0: X, op1: X, op2: _Imm, op3: _Imm, /, *, asm: Assembler | None = None) -> None: ...
@overload
def sbfx(op0: W, op1: W, op2: _Imm, op3: _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `sbfx` (4 operands)."""
@overload
def sbfx(op0: X, op1: X, op2: _Imm, op3: _Imm, /, *, asm: Assembler | None = None) -> None: ...
def scvtf(op0: S | D, op1: X | W, /, *, asm: Assembler | None = None) -> None:
    """Emit `scvtf` (2 operands)."""
@overload
def sdiv(op0: W, op1: W, op2: W, /, *, asm: Assembler | None = None) -> None:
    """Emit `sdiv` (3 operands)."""
@overload
def sdiv(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None: ...
def smaddl(op0: X, op1: W, op2: W, op3: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `smaddl` (4 operands)."""
def smnegl(op0: X, op1: W, op2: W, /, *, asm: Assembler | None = None) -> None:
    """Emit `smnegl` (3 operands)."""
def smsubl(op0: X, op1: W, op2: W, op3: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `smsubl` (4 operands)."""
def smulh(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `smulh` (3 operands)."""
def smull(op0: X, op1: W, op2: W, /, *, asm: Assembler | None = None) -> None:
    """Emit `smull` (3 operands)."""
@overload
def stp(op0: D, op1: D, op2: MemExpr, /, *, asm: Assembler | None = None) -> None:
    """Emit `stp` (any number of operands)."""
@overload
def stp(op0: Q, op1: Q, op2: MemExpr, /, *, asm: Assembler | None = None) -> None: ...
@overload
def stp(op0: S, op1: S, op2: MemExpr, /, *, asm: Assembler | None = None) -> None: ...
@overload
def stp(op0: W, op1: W, op2: MemExpr, /, *, asm: Assembler | None = None) -> None: ...
@overload
def stp(op0: X, op1: X, op2: MemExpr, /, *, asm: Assembler | None = None) -> None: ...
def str_(op0: X | W | S | D, op1: MemExpr, /, *, asm: Assembler | None = None) -> None:
    """Emit `str` (any number of operands)."""
def strb(op0: W, op1: MemExpr, /, *, asm: Assembler | None = None) -> None:
    """Emit `strb` (any number of operands)."""
def strh(op0: W, op1: MemExpr, /, *, asm: Assembler | None = None) -> None:
    """Emit `strh` (any number of operands)."""
@overload
def sub(op0: X | Sp, op1: X | Sp, op2: X | RegMod[X] | RegMod[W] | _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `sub` (3 or 4 operands)."""
@overload
def sub(op0: W, op1: W, op2: W | RegMod[W] | _Imm, /, *, asm: Assembler | None = None) -> None: ...
@overload
def sub(op0: X | Sp, op1: X | Sp, op2: X | W, op3: Mod, /, *, asm: Assembler | None = None) -> None: ...
@overload
def sub(op0: W, op1: W, op2: W, op3: Mod, /, *, asm: Assembler | None = None) -> None: ...
@overload
def subs(op0: W, op1: W, op2: W | RegMod[W] | _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `subs` (3 or 4 operands)."""
@overload
def subs(op0: X, op1: X | Sp, op2: X | RegMod[X] | RegMod[W] | _Imm, /, *, asm: Assembler | None = None) -> None: ...
@overload
def subs(op0: W, op1: W, op2: W, op3: Mod, /, *, asm: Assembler | None = None) -> None: ...
@overload
def subs(op0: X, op1: X | Sp, op2: X | W, op3: Mod, /, *, asm: Assembler | None = None) -> None: ...
@overload
def sxtb(op0: W, op1: W, /, *, asm: Assembler | None = None) -> None:
    """Emit `sxtb` (2 operands)."""
@overload
def sxtb(op0: X, op1: X, /, *, asm: Assembler | None = None) -> None: ...
@overload
def sxth(op0: W, op1: W, /, *, asm: Assembler | None = None) -> None:
    """Emit `sxth` (2 operands)."""
@overload
def sxth(op0: X, op1: X, /, *, asm: Assembler | None = None) -> None: ...
def sxtw(op0: X, op1: W, /, *, asm: Assembler | None = None) -> None:
    """Emit `sxtw` (2 operands)."""
def tbnz(op0: X | W, op1: _Imm, op2: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `tbnz` (3 operands)."""
def tbz(op0: X | W, op1: _Imm, op2: _Target, /, *, asm: Assembler | None = None) -> None:
    """Emit `tbz` (3 operands)."""
@overload
def tst(op0: W, op1: W | RegMod[W], /, *, asm: Assembler | None = None) -> None:
    """Emit `tst` (2 or 3 operands)."""
@overload
def tst(op0: X | W, op1: _Imm, /, *, asm: Assembler | None = None) -> None: ...
@overload
def tst(op0: X, op1: X | RegMod[X], /, *, asm: Assembler | None = None) -> None: ...
@overload
def tst(op0: W, op1: W, op2: Mod, /, *, asm: Assembler | None = None) -> None: ...
@overload
def tst(op0: X, op1: X, op2: Mod, /, *, asm: Assembler | None = None) -> None: ...
@overload
def ubfiz(op0: W, op1: W, op2: _Imm, op3: _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `ubfiz` (4 operands)."""
@overload
def ubfiz(op0: X, op1: X, op2: _Imm, op3: _Imm, /, *, asm: Assembler | None = None) -> None: ...
@overload
def ubfm(op0: W, op1: W, op2: _Imm, op3: _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `ubfm` (4 operands)."""
@overload
def ubfm(op0: X, op1: X, op2: _Imm, op3: _Imm, /, *, asm: Assembler | None = None) -> None: ...
@overload
def ubfx(op0: W, op1: W, op2: _Imm, op3: _Imm, /, *, asm: Assembler | None = None) -> None:
    """Emit `ubfx` (4 operands)."""
@overload
def ubfx(op0: X, op1: X, op2: _Imm, op3: _Imm, /, *, asm: Assembler | None = None) -> None: ...
def ucvtf(op0: S | D, op1: X | W, /, *, asm: Assembler | None = None) -> None:
    """Emit `ucvtf` (2 operands)."""
@overload
def udiv(op0: W, op1: W, op2: W, /, *, asm: Assembler | None = None) -> None:
    """Emit `udiv` (3 operands)."""
@overload
def udiv(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None: ...
def umaddl(op0: X, op1: W, op2: W, op3: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `umaddl` (4 operands)."""
def umnegl(op0: X, op1: W, op2: W, /, *, asm: Assembler | None = None) -> None:
    """Emit `umnegl` (3 operands)."""
def umsubl(op0: X, op1: W, op2: W, op3: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `umsubl` (4 operands)."""
def umulh(op0: X, op1: X, op2: X, /, *, asm: Assembler | None = None) -> None:
    """Emit `umulh` (3 operands)."""
def umull(op0: X, op1: W, op2: W, /, *, asm: Assembler | None = None) -> None:
    """Emit `umull` (3 operands)."""
def uxtb(op0: W, op1: W, /, *, asm: Assembler | None = None) -> None:
    """Emit `uxtb` (2 operands)."""
def uxth(op0: W, op1: W, /, *, asm: Assembler | None = None) -> None:
    """Emit `uxth` (2 operands)."""

__all__ = [
    "adc",
    "adcs",
    "add",
    "adds",
    "adr",
    "adrp",
    "and_",
    "ands",
    "asr",
    "autiasp",
    "autibsp",
    "b",
    "bal",
    "bcc",
    "bcs",
    "beq",
    "bfi",
    "bfm",
    "bfxil",
    "bge",
    "bgt",
    "bhi",
    "bhs",
    "bic",
    "bics",
    "bl",
    "ble",
    "blo",
    "blr",
    "blraaz",
    "blrabz",
    "bls",
    "blt",
    "bmi",
    "bne",
    "bpl",
    "br",
    "braa",
    "braaz",
    "brab",
    "brabz",
    "brk",
    "bti",
    "bvc",
    "bvs",
    "cbnz",
    "cbz",
    "ccmn",
    "ccmp",
    "cinc",
    "cinv",
    "cls",
    "clz",
    "cmn",
    "cmp",
    "cneg",
    "csel",
    "cset",
    "csetm",
    "csinc",
    "csinv",
    "csneg",
    "eon",
    "eor",
    "extr",
    "fabs",
    "fadd",
    "fccmp",
    "fccmpe",
    "fcmp",
    "fcmpe",
    "fcsel",
    "fcvt",
    "fcvtas",
    "fcvtau",
    "fcvtms",
    "fcvtmu",
    "fcvtns",
    "fcvtnu",
    "fcvtps",
    "fcvtpu",
    "fcvtzs",
    "fcvtzu",
    "fdiv",
    "fmadd",
    "fmax",
    "fmaxnm",
    "fmin",
    "fminnm",
    "fmov",
    "fmsub",
    "fmul",
    "fneg",
    "fnmadd",
    "fnmsub",
    "fnmul",
    "frinta",
    "frinti",
    "frintm",
    "frintn",
    "frintp",
    "frintx",
    "frintz",
    "fsqrt",
    "fsub",
    "ldp",
    "ldpsw",
    "ldr",
    "ldrb",
    "ldrh",
    "ldrsb",
    "ldrsh",
    "ldrsw",
    "lsl",
    "lsr",
    "madd",
    "mneg",
    "mov",
    "movk",
    "movn",
    "movz",
    "msub",
    "mul",
    "mvn",
    "neg",
    "negs",
    "ngc",
    "ngcs",
    "nop",
    "orn",
    "orr",
    "paciasp",
    "pacibsp",
    "rbit",
    "ret",
    "retaa",
    "retab",
    "rev",
    "rev16",
    "rev32",
    "ror",
    "sbc",
    "sbcs",
    "sbfiz",
    "sbfm",
    "sbfx",
    "scvtf",
    "sdiv",
    "smaddl",
    "smnegl",
    "smsubl",
    "smulh",
    "smull",
    "stp",
    "str_",
    "strb",
    "strh",
    "sub",
    "subs",
    "sxtb",
    "sxth",
    "sxtw",
    "tbnz",
    "tbz",
    "tst",
    "ubfiz",
    "ubfm",
    "ubfx",
    "ucvtf",
    "udiv",
    "umaddl",
    "umnegl",
    "umsubl",
    "umulh",
    "umull",
    "uxtb",
    "uxth",
]
